export const bn = {
  navHome: 'হোਮ',
  navSelfDeclaration: 'স্ব-ঘোষণা',
  navCandidate: 'প্রার্থী',
  navAssessor: 'মূল্যায়নকারী',
  govtInitiative: 'ভারত সরকারের উদ্যোগ',
  ministryName: 'দক্ষতা উন্নয়ন ও উদ্যোক্তা মন্ত্রক',
  rplAiAssessment: 'আরপিএল এআই দক্ষতা মূল্যায়ন',
  heroTitle: 'আপনার দক্ষতার সরকারি স্বীকৃতি পান',
  heroSub: 'কাজের মাধ্যমে শেখা কর্মীদের জন্য। কোনো প্রাতিষ্ঠানিক শিক্ষার প্রয়োজন নেই।',
  portfolioHeroH1_1: 'দক্ষতা যাচাই।',
  portfolioHeroH1_2: 'অভিজ্ঞতা',
  portfolioHeroH1_3: ' স্বীকৃতি।',
  portfolioHeroH1_4: 'RPL সম্প্রসারণ।',
  startAssessment: 'মূল্যায়ন শুরু করুন',
  assessorLogin: 'অ্যাসেসর লগইন',
  makeItClear: '০১ — স্বচ্ছ ও স্পষ্ট',
  buildShapeShip: 'শিখুন / গড়ুন / এগিয়ে যান',
  tickerAiAssisted: 'এআই-সহায়তাপ্রাপ্ত RPL',
  tickerNsqf: 'NSQF সামঞ্জস্যপূর্ণ',
  tickerHumanLoop: 'মানব যাচাইকরণ সহ',
  tickerRegional: '২২টি ভারতীয় ভাষা',
  tickerOffline: 'অফলাইন-প্রথম সিঙ্ক',
  tickerMinistry: 'দক্ষতা উন্নয়ন মন্ত্রক',
  ourWork: 'আমাদের কাজ',
  work1Title: 'সহজ অভিজ্ঞতা ম্যাপিং',
  work1Desc: 'কর্মীদের নিজের ভাষায় দক্ষতা প্রকাশের জন্য সংলাপাভিত্তিক ইন্টারফেস।',
  work2Title: 'ভিডিও ও ছবি মূল্যায়ন',
  work2Desc: 'ব্যবহারিক কাজের মূল্যায়নের জন্য চাক্ষুষ প্রমাণ সংগ্রহ।',
  work3Title: 'মানসম্মত স্কোরিং',
  work3Desc: 'মূল্যায়নকারীদের জন্য NSQF মানদণ্ড অনুযায়ী সঠিক স্কোরিং ব্যবস্থা।',
  work4Title: 'কম ইন্টারনেটেও কার্যকর',
  work4Desc: 'ইন্টারনেট না থাকলেও তথ্য ডিভাইসে সুরক্ষিত থাকে।',
  tagSelfDecl: 'স্ব-ঘোষণা',
  tagAiAssist: 'এআই সহায়তা',
  tagPractical: 'ব্যবহারিক সরঞ্জাম',
  tagMedia: 'মিডিয়া প্রমাণ',
  tagAssessor: 'পরীক্ষক সহায়তা',
  tagNsqf: 'NSQF মানদণ্ড',
  tagOffline: 'অফলাইন সক্ষম',
  tagSync: 'অটো সিঙ্ক',
  feat1Title: 'নিজের অভিজ্ঞতার কথা বলুন',
  feat1Desc: 'নিজের আঞ্চলিক ভাষায় ভয়েস ইনপুট ব্যবহার করুন',
  feat2Title: 'আপনার কাজ দেখান',
  feat2Desc: 'ছবি, ভিডিও এবং কাজের প্রমাণ সহজে আপলোড করুন',
  feat3Title: 'NSQF এর সাথে মেলানো',
  feat3Desc: 'এআই আপনার ব্যবহারিক দক্ষতাকে জাতীয় মানের সাথে যুক্ত করে',
  feat4Title: 'মানুষের চূড়ান্ত সিদ্ধান্ত',
  feat4Desc: 'এআই স্কোর প্রস্তাব করে, সার্টিফাইড বিশেষজ্ঞ চূড়ান্ত সিদ্ধান্ত নেন',
  howItWorks: 'এটি কীভাবে কাজ করে',
  howItWorksSub: 'তিনটি সহজ ধাপ। কোনো জটিল পরীক্ষা বা ফর্ম নেই।',
  step1Title: 'আপনার সম্পর্কে বলুন',
  step1Desc: 'আপনার পেশা নির্বাচন করুন। যেকোনো ভাষায় আপনার কাজের অভিজ্ঞতা বলুন।',
  step2Title: 'আপনার কাজ দেখান',
  step2Desc: 'তৈরি করা কাজের ছবি তুলুন বা একটি ছোট ভিডিও রেকর্ড করুন।',
  step3Title: 'সার্টিফিকেট পান',
  step3Desc: 'এআই দক্ষতা যাচাই করে এবং সার্টিফাইড পরীক্ষক জাতীয় শংসাপত্র জারি করেন।',
  ctaBannerTitlePortfolio: 'ভারতের শ্রমশক্তির আসল দক্ষতাকে দিন জাতীয় স্বীকৃতি।',
  ctaBannerTitleGovt: 'ভারতের কর্মীবাহিনীর কাজের দক্ষতা আছে। আসুন তা প্রমাণ করি।',
  ctaBannerSub: 'অসংগঠিত ক্ষেত্রের কর্মীদের জন্য বিশেষভাবে নির্মিত।',
  beginSelfDeclaration: 'স্ব-ঘোষণা শুরু করুন',
  welcomeCandidate: 'স্বাগতম, রমেশ 👋',
  candidateId: 'প্রার্থী আইডি: RPL-2024-8842',
  allSynced: 'সমস্ত ডেটা সিঙ্ক হয়েছে',
  newDeclaration: 'নতুন ঘোষণা',
  newDeclarationSub: 'নতুন দক্ষতা ম্যাপিং শুরু করুন',
  uploadEvidence: 'প্রমাণ আপলোড করুন',
  uploadEvidenceSub: 'ছবি বা ভিডিও যোগ করুন',
  viewCertificate: 'সার্টিফিকেট দেখুন',
  viewCertificateSub: 'আপনার NSQF সার্টিফিকেট ডাউনলোড করুন',
  yourApplications: 'আপনার আবেদনসমূহ',
  underReview: 'পর্যালোচনাধীন',
  needMoreInfo: 'আরও তথ্য প্রয়োজন',
  certified: 'প্রত্যয়িত (সার্টিফাইড)',
  nsqfLevel: 'NSQF স্তর',
  submittedAgo: '২ দিন আগে জমা দেওয়া হয়েছে',
  assessorReviewing: 'মূল্যায়নকারী আপনার প্রমাণ খতিয়ে দেখছেন…',
  needClearerVideo: 'ওয়্যারিং নিরাপত্তা পরীক্ষার আরও স্পষ্ট ভিডিও প্রয়োজন।',
  details: 'বিস্তারিত',
  uploadNow: 'এখনই আপলোড করুন',
  downloadPdf: 'পিডিএফ ডাউনলোড করুন',
  worksWithoutInternet: 'ইন্টারনেট ছাড়াই কাজ করে',
  worksWithoutInternetSub: 'ইন্টারনেট না থাকলেও আবেদন দেখুন ও তৈরি করুন। অনলাইনে এলে স্বয়ংক্রিয়ভাবে সিঙ্ক হবে।',
  pendingReview: 'পর্যালোচনার অপেক্ষায়',
  searchCandidate: 'প্রার্থী খুঁজুন…',
  aiDisclaimer: 'এআই শুধুমাত্র পরামর্শ দেয়। চূড়ান্ত সিদ্ধান্ত মানব পরীক্ষকের হাতেই থাকে।',
  photos: 'ছবি',
  video: 'ভিডিও',
  aiSuggestion: 'এআই পরামর্শ',
  competent: 'দক্ষ (উপযুক্ত)',
  needsReview: 'পুনর্বিবেচনা প্রয়োজন',
  lowMatch: 'কম মিল',
  yes: 'হ্যাঁ',
  partial: 'আংশিক',
  no: 'না',
  saveDraft: 'খসড়া সংরক্ষণ করুন',
  notYetCompetent: 'এখনও সম্পূর্ণ প্রস্তুত নয়',
  requestEvidence: 'অতিরিক্ত প্রমাণ চান',
  recommendCert: 'সার্টিফিকেশনের সুপারিশ করুন',
  selfDeclaration: 'স্ব-ঘোষণা',
  selfDeclarationSub: 'নিজের ভাষায় আপনার দক্ষতা সম্পর্কে বলুন।',
  offlineReady: 'অফলাইন প্রস্তুত',
  step: 'ধাপ',
  of: 'এর',
  yourTrade: 'আপনার পেশা',
  experience: 'অভিজ্ঞতা',
  evidence: 'প্রমাণ',
  result: 'ফলাফল',
  whatWork: 'আপনি কী কাজ করেন?',
  tapPicture: 'আপনার কাজের সাথে মিলে এমন ছবিতে স্পর্শ করুন।',
  tellAboutWork: 'আপনার কাজ সম্পর্কে বলুন',
  pressAndSpeak: 'টিপুন এবং বলুন',
  speakAnyLang: 'যেকোনো ভাষায় কথা বলুন',
  listening: '🔴 শুনছি… এবার বলুন',
  howManyYears: 'আপনি কত বছর ধরে এই কাজ করছেন?',
  whatTools: 'আপনি কী কী যন্ত্রপাতি ব্যবহার করেন?',
  whatKindWork: 'সাধারণত আপনি কী ধরণের কাজ করেন?',
  whereWork: 'আপনি কোথায় কাজ করেন?',
  showYourWork: 'আপনার কাজ দেখান',
  evidenceSub: 'ছবি ও ভিডিও পরীক্ষককে আপনার কাজের দক্ষতা বুঝতে সাহায্য করে।',
  takePhoto: 'ছবি তুলুন',
  takePhotoSub: 'আপনার কাজের',
  recordVideo: 'ভিডিও বানান',
  recordVideoSub: 'একটি ছোট ভিডিও',
  uploadPaper: 'কাগজপত্র আপলোড করুন',
  uploadPaperSub: 'সার্টিফিকেট বা অভিজ্ঞতাপত্র',
  dragFiles: 'অথবা ফাইল এখানে টেনে আনুন',
  fileTypes: 'JPG, PNG, MP4, PDF — সর্বোচ্চ ৫০ MB',
  offlineUpload: 'ইন্টারনেট ছাড়াও আপনি এটি করতে পারেন।',
  offlineUploadSub: 'ফাইল আপনার ফোনে সংরক্ষিত থাকবে এবং অনলাইনে এলে আপলোড হবে।',
  suggestedMatch: 'প্রস্তাবিত মিল',
  match: 'মিল',
  humanReview: 'মানব মূল্যায়নকারী যাচাই করে সিদ্ধান্ত নেবেন।',
  humanReviewSub: 'এটি কম্পিউটারের প্রাথমিক পরামর্শ মাত্র। প্রত্যয়িত পরীক্ষক চূড়ান্ত সিদ্ধান্ত নেবেন।',
  back: 'পেছনে',
  next: 'পরবর্তী',
  submit: 'জমা দিন',
  orTypeBelow: 'বোতাম টিপে কথা বলুন বা নিচে লিখুন।',
  electrician: 'ইলেকট্রিশিয়ান',
  plumber: 'প্লাম্বার',
  welder: 'ওয়েল্ডার',
  carpenter: 'ছুতোর',
  mason: 'রাজমিস্ত্রি',
  tailor: 'দর্জি',
  cook: 'বাবুর্চি',
  driver: 'চালক',
  other: 'অন্যান্য',
  performBasicWork: 'মৌলিক প্রযুক্তিগত কাজ করা',
  readDrawings: 'সহজ ড্রয়িং বা নকশা বোঝা',
  followSafety: 'কর্মক্ষেত্রের সুরক্ষা বিধি মেনে চলা',
  footerDesc: 'স্মার্ট ইন্ডিয়া হ্যাকাথনের অধীনে পূর্ব অর্জিত শিক্ষার স্বীকৃতির (RPL) জন্য এআই-চালিত দক্ষতা মূল্যায়ন ব্যবস্থা।',
  sponsoredBy: 'পৃষ্ঠপোষক',
  msdeFullName: 'দক্ষতা উন্নয়ন ও উদ্যোক্তা মন্ত্রক (MSDE)',
  ncvetFullName: 'জাতীয় বৃত্তিমূলক শিক্ষা ও প্রশিক্ষণ পরিষদ (NCVET)',
  project: 'প্রকল্প',
  problemId: 'সমস্যা আইডি: SIH26242',
  themeSmartEdu: 'থিম: স্মার্ট শিক্ষা',
  categorySoftware: 'বিভাগ: সফটওয়্যার',
  footerCopyright: '© ২০২৬ আরপিএল এআই মূল্যায়ন সরঞ্জাম — ভারতের দক্ষ কর্মীবাহিনীর জন্য নির্মিত'
};

export const as = {
  navHome: 'ঘৰ',
  navSelfDeclaration: 'স্ব-ঘোষণা',
  navCandidate: 'প্ৰাৰ্থী',
  navAssessor: 'মূল্যায়নকাৰী',
  govtInitiative: 'ভাৰত চৰকাৰৰ পদক্ষেপ',
  ministryName: 'দক্ষতা বিকাশ আৰু উদ্যোগ মন্ত্ৰালয়',
  rplAiAssessment: 'RPL AI দক্ষতা মূল্যায়ন',
  heroTitle: 'আপোনাৰ দক্ষতাক প্ৰমাণিত কৰক',
  heroSub: 'কামত শিকা শ্ৰমিকসকলৰ বাবে। আনুষ্ঠানিক শিক্ষাৰ প্ৰয়োজন নাই।',
  portfolioHeroH1_1: 'দক্ষতা পৰীক্ষা।',
  portfolioHeroH1_2: 'অভিজ্ঞতা',
  portfolioHeroH1_3: ' স্বীকৃতি।',
  portfolioHeroH1_4: 'RPL সম্প্ৰসাৰণ।',
  startAssessment: 'মূল্যায়ন আৰম্ভ কৰক',
  assessorLogin: 'মূল্যায়নকাৰী লগইন',
  makeItClear: '০১ — স্পষ্ট আৰু স্বচ্ছ',
  buildShapeShip: 'শিকক / গঢ়ক / আগবাঢ়ক',
  tickerAiAssisted: 'AI-সহায়তাপ্রাপ্ত RPL',
  tickerNsqf: 'NSQF মান অনুসৰি',
  tickerHumanLoop: 'মানৱ পৰীক্ষণসহ',
  tickerRegional: '২২টা ভাৰতীয় ভাষা',
  tickerOffline: 'অফলাইন-প্ৰথম সংমিশ্ৰণ',
  tickerMinistry: 'দক্ষতা বিকাশ মন্ত্ৰালয়',
  ourWork: 'আমাৰ কাম',
  work1Title: 'সহজ অভিজ্ঞতা মেপিং',
  work1Desc: 'শ্ৰমিকসকলে নিজৰ ভাষাত দক্ষতা প্ৰকাশ কৰিবলৈ কথোপকথনভিত্তিক মাধ্যম।',
  work2Title: 'ভিডিঅ’ আৰু ফটো মূল্যায়ন',
  work2Desc: 'ব্যৱহাৰিক কামৰ মূল্যায়নৰ বাবে প্ৰমাণ সংগ্ৰহ।',
  work3Title: 'মানসম্পন্ন স্ক’ৰিং',
  work3Desc: 'মূল্যায়নকাৰীসকলৰ বাবে NSQF মান অনুসৰি নিৰ্ভুল স্ক’ৰিং।',
  work4Title: 'কম ইণ্টাৰনেটতো কাৰ্যকৰী',
  work4Desc: 'ইণ্টাৰনেট নাথাকিলেও তথ্য ডিভাইচত সুৰক্ষিত থাকে।',
  tagSelfDecl: 'স্ব-ঘোষণা',
  tagAiAssist: 'AI সহায়',
  tagPractical: 'ব্যৱহাৰিক সঁজুলি',
  tagMedia: 'মিডিয়া প্ৰমাণ',
  tagAssessor: 'পৰীক্ষক সহায়',
  tagNsqf: 'NSQF মান',
  tagOffline: 'অফলাইন কাৰ্যক্ষম',
  tagSync: 'স্বয়ংক্ৰিয় সংমিশ্ৰণ',
  feat1Title: 'আপোনাৰ অভিজ্ঞতা কওক',
  feat1Desc: 'আপোনাৰ নিজৰ ভাষাত ভইচ ইনপুট ব্যৱহাৰ কৰক',
  feat2Title: 'আপোনাৰ কাম দেখুৱাওক',
  feat2Desc: 'ফটো, ভিডিঅ’ আৰু কামৰ প্ৰমাণ সহজে আপলোড কৰক',
  feat3Title: 'NSQF সৈতে মিল',
  feat3Desc: 'AI য়ে আপোনাৰ ব্যৱহাৰিক দক্ষতাক ৰাষ্ট্ৰীয় মানৰ সৈতে সংযোগ কৰে',
  feat4Title: 'মানৱ মূল্যায়নকাৰীৰ সিদ্ধান্ত',
  feat4Desc: 'AI য়ে স্ক’ৰ পৰামৰ্শ দিয়ে, প্ৰমাণিত বিশেষজ্ঞই চূড়ান্ত সিদ্ধান্ত লয়',
  howItWorks: 'ই কেনেকৈ কাম কৰে',
  howItWorksSub: 'তিনিটা সহজ পদক্ষেপ। কোনো জটিল পৰীক্ষা বা দীঘলীয়া প্ৰপত্ৰ নাই।',
  step1Title: 'আপোনাৰ বিষয়ে কওক',
  step1Desc: 'আপোনাৰ বৃত্তি বাছক। যিকোনো ভাষাত আপোনাৰ অভিজ্ঞতা কওক।',
  step2Title: 'আপোনাৰ কাম দেখুৱাওক',
  step2Desc: 'আপুনি বনোৱা সামগ্ৰীৰ ফটো তোলক বা এটা সৰু ভিডিঅ’ বনাওক।',
  step3Title: 'প্ৰমাণপত্ৰ লাভ কৰক',
  step3Desc: 'AI য়ে দক্ষতা পৰীক্ষা কৰে আৰু প্ৰমাণিত পৰীক্ষকে ৰাষ্ট্ৰীয় প্ৰমাণপত্ৰ প্ৰদান কৰে।',
  ctaBannerTitlePortfolio: 'ভাৰতৰ দক্ষ হাতক দিয়ক চৰকাৰী মৰ্যাদা।',
  ctaBannerTitleGovt: 'ভাৰতৰ শ্ৰমিকৰ দক্ষতা আছে। আহক তাক প্ৰমাণিত কৰোঁ।',
  ctaBannerSub: 'অসংগঠিত খণ্ডৰ শ্ৰমিকসকলৰ বাবে বিশেষভাৱে নিৰ্মিত।',
  beginSelfDeclaration: 'স্ব-ঘোষণা আৰম্ভ কৰক',
  welcomeCandidate: 'স্বাগতম, ৰমেশ 👋',
  candidateId: 'প্ৰাৰ্থী আইডি: RPL-2024-8842',
  allSynced: 'সকলো তথ্য সংমিশ্ৰিত হৈছে',
  newDeclaration: 'নতুন ঘোষণা',
  newDeclarationSub: 'নতুন দক্ষতা মেপিং আৰম্ভ কৰক',
  uploadEvidence: 'প্ৰমাণ আপলোড কৰক',
  uploadEvidenceSub: 'ফটো বা ভিডিঅ’ যোগ কৰক',
  viewCertificate: 'প্ৰমাণপত্ৰ চাওক',
  viewCertificateSub: 'আপোনাৰ NSQF প্ৰমাণপত্ৰ ডাউনল’ড কৰক',
  yourApplications: 'আপোনাৰ আবেদনসমূহ',
  underReview: 'পৰ্যালোচনাধীন',
  needMoreInfo: 'অধিক তথ্যৰ প্ৰয়োজন',
  certified: 'প্ৰমাণিত (চাৰ্টিফাইড)',
  nsqfLevel: 'NSQF স্তৰ',
  submittedAgo: '২ দিন আগতে দাখিল কৰা হৈছে',
  assessorReviewing: 'মূল্যায়নকাৰীয়ে আপোনাৰ প্ৰমাণ পৰীক্ষা কৰি আছে…',
  needClearerVideo: 'ৱায়াৰিং সুৰক্ষা পৰীক্ষাৰ স্পষ্ট ভিডিঅ’ প্ৰয়োজন।',
  details: 'বিৱৰণ',
  uploadNow: 'এতিয়াই আপলোড কৰক',
  downloadPdf: 'PDF ডাউনল’ড কৰক',
  worksWithoutInternet: 'ইণ্টাৰনেট অবিহনেও কাম কৰে',
  worksWithoutInternetSub: 'ইণ্টাৰনেট নথকা অৱস্থাতো আবেদন চাওক আৰু সৃষ্টি কৰক। অনলাইন হ’লে স্বয়ংক্ৰিয়ভাৱে সংমিশ্ৰণ হ’ব।',
  pendingReview: 'পৰ্যালোচনাৰ বাবে বাকী আছে',
  searchCandidate: 'প্ৰাৰ্থী সন্ধান কৰক…',
  aiDisclaimer: 'AI য়ে কেৱল পৰামৰ্শ দিয়ে। চূড়ান্ত সিদ্ধান্ত মানৱ মূল্যায়নকাৰীৰহে।',
  photos: 'ছবিসমূহ',
  video: 'ভিডিঅ’',
  aiSuggestion: 'AI পৰামৰ্শ',
  competent: 'যোগ্য (দক্ষ)',
  needsReview: 'পুনৰীক্ষণ প্ৰয়োজন',
  lowMatch: 'কম মিল',
  yes: 'হয়',
  partial: 'আংশিক',
  no: 'নহয়',
  saveDraft: 'খচৰা সংৰক্ষণ কৰক',
  notYetCompetent: 'এতিয়াও উপযুক্ত নহয়',
  requestEvidence: 'অতিৰিক্ত প্ৰমাণ বিচাৰক',
  recommendCert: 'প্ৰমাণপত্ৰৰ পৰামৰ্শ দিয়ক',
  selfDeclaration: 'স্ব-ঘোষণা',
  selfDeclarationSub: 'আপোনাৰ দক্ষতাৰ বিষয়ে কওক — নিজৰ ভাষাত।',
  offlineReady: 'অফলাইন প্ৰস্তুত',
  step: 'পদক্ষেপ',
  of: 'ৰ ভিতৰত',
  yourTrade: 'আপোনাৰ বৃত্তি',
  experience: 'অভিজ্ঞতা',
  evidence: 'প্ৰমাণ',
  result: 'ফলাফল',
  whatWork: 'আপুনি কি কাম কৰে?',
  tapPicture: 'আপোনাৰ কামৰ লগত মিল থকা ছবিত টিপক।',
  tellAboutWork: 'আপোনাৰ কামৰ বিষয়ে কওক',
  pressAndSpeak: 'টিপক আৰু কওক',
  speakAnyLang: 'যিকোনো ভাষাত কওক',
  listening: '🔴 শুনি আছোঁ… এতিয়া কওক',
  howManyYears: 'আপুনি কিমান বছৰ ধৰি এই কাম কৰি আছে?',
  whatTools: 'আপুনি কি কি সঁজুলি ব্যৱহাৰ কৰে?',
  whatKindWork: 'সাধাৰণতে আপুনি কেনে ধৰণৰ কাম কৰে?',
  whereWork: 'আপুনি ক’ত কাম কৰে?',
  showYourWork: 'আপোনাৰ কাম দেখুৱাওক',
  evidenceSub: 'ফটো আৰু ভিডিঅ’ই পৰীক্ষকক আপোনাৰ দক্ষতা বুজাত সহায় কৰে।',
  takePhoto: 'ফটো তোলক',
  takePhotoSub: 'আপোনাৰ কামৰ',
  recordVideo: 'ভিডিঅ’ বনাওক',
  recordVideoSub: 'এটা চুটি ভিডিঅ’',
  uploadPaper: 'কাগজ-পত্ৰ আপলোড কৰক',
  uploadPaperSub: 'প্ৰমাণপত্ৰ বা অভিজ্ঞতা পত্ৰ',
  dragFiles: 'বা ফাইলসমূহ ইয়ালৈ আনক',
  fileTypes: 'JPG, PNG, MP4, PDF — ৫০ MB লৈকে',
  offlineUpload: 'ইণ্টাৰনেট নোহোৱাকৈও আপুনি এইটো কৰিব পাৰে।',
  offlineUploadSub: 'ফাইলসমূহ ফোনত সংৰক্ষিত থাকিব আৰু নেট আহিলে আপলোড হ’ব।',
  suggestedMatch: 'পৰামৰ্শিত মিল',
  match: 'মিল',
  humanReview: 'মানৱ মূল্যায়নকাৰীয়ে পৰীক্ষা কৰি সিদ্ধান্ত ল’ব।',
  humanReviewSub: 'ই কম্পিউটাৰৰ প্ৰাৰম্ভিক পৰামৰ্শহে। প্ৰমাণিত বিশেষজ্ঞইহে চূড়ান্ত সিদ্ধান্ত ল’ব।',
  back: 'পিছলৈ',
  next: 'পৰৱৰ্তী',
  submit: 'দাখিল কৰক',
  orTypeBelow: 'বুটাম টিপি কওক বা তলত লিখক।',
  electrician: 'ইলেকট্ৰিচিয়ান',
  plumber: 'প্লাম্বাৰ',
  welder: 'ৱেল্ডাৰ',
  carpenter: 'বাঢ়ৈ',
  mason: 'ৰাজমিস্ত্ৰী',
  tailor: 'দৰ্জী',
  cook: 'ৰান্ধনী',
  driver: 'চালক',
  other: 'অন্যান্য',
  performBasicWork: 'মৌলিক কাৰিকৰী কাম কৰা',
  readDrawings: 'সহজ ড্ৰয়িং বুজি পোৱা',
  followSafety: 'কৰ্মক্ষেত্ৰৰ সুৰক্ষা নিয়ম পালন কৰা',
  footerDesc: 'স্মাৰ্ট ইণ্ডিয়া হেকাথনৰ অধীনত পূৰ্ব শিক্ষণৰ স্বীকৃতিৰ (RPL) বাবে AI চালিত দক্ষতা মূল্যায়ন সঁজুলি।',
  sponsoredBy: 'পৃষ্ঠপোষক',
  msdeFullName: 'দক্ষতা বিকাশ আৰু উদ্যোগ মন্ত্ৰালয় (MSDE)',
  ncvetFullName: 'ৰাষ্ট্ৰীয় বৃত্তিমূলক শিক্ষা আৰু প্ৰশিক্ষণ পৰিষদ (NCVET)',
  project: 'প্ৰকল্প',
  problemId: 'সমস্যা আইডি: SIH26242',
  themeSmartEdu: 'বিষয়বস্তু: স্মাৰ্ট শিক্ষা',
  categorySoftware: 'শ্ৰেণী: চফ্টৱেৰ',
  footerCopyright: '© ২০২৬ RPL AI মূল্যায়ন সঁজুলি — ভাৰতৰ দক্ষ শ্ৰমিকসকলৰ বাবে নিৰ্মিত'
};

export const or = {
  navHome: 'ମୂଳପୃଷ୍ଠା',
  navSelfDeclaration: 'ସ୍ୱୟଂ ଘୋଷଣା',
  navCandidate: 'ପ୍ରାର୍ଥୀ',
  navAssessor: 'ମୂଲ୍ୟାଙ୍କନକାରୀ',
  govtInitiative: 'ଭାରତ ସରକାରଙ୍କ ପଦକ୍ଷେପ',
  ministryName: 'ଦକ୍ଷତା ବିକାଶ ଓ ଉଦ୍ୟୋଗିତା ମନ୍ତ୍ରଣାଳୟ',
  rplAiAssessment: 'RPL AI ଦକ୍ଷତା ମୂଲ୍ୟାଙ୍କନ',
  heroTitle: 'ଆପଣଙ୍କ ଦକ୍ଷତାକୁ ପ୍ରମାଣିତ କରନ୍ତୁ',
  heroSub: 'କାର୍ଯ୍ୟରୁ ଶିଖିଥିବା ଶ୍ରମିକମାନଙ୍କ ପାଇଁ। କୌଣସି ଆନୁଷ୍ଠାନିକ ଶିକ୍ଷାର ଆବଶ୍ୟକତା ନାହିଁ।',
  portfolioHeroH1_1: 'ଦକ୍ଷତା ପରଖନ୍ତୁ।',
  portfolioHeroH1_2: 'ଅନୁଭବକୁ',
  portfolioHeroH1_3: ' ପ୍ରମାଣିତ କରନ୍ତୁ।',
  portfolioHeroH1_4: 'RPL ବିସ୍ତାର।',
  startAssessment: 'ମୂଲ୍ୟାଙ୍କନ ଆରମ୍ଭ କରନ୍ତୁ',
  assessorLogin: 'ପରୀକ୍ଷକ ଲଗଇନ୍',
  makeItClear: '୦୧ — ସ୍ପଷ୍ଟ ଏବଂ ସଠିକ୍',
  buildShapeShip: 'ଶିଖନ୍ତୁ / ଗଢ଼ନ୍ତୁ / ଆଗକୁ ବଢ଼ନ୍ତୁ',
  tickerAiAssisted: 'AI-ସହାୟକ RPL',
  tickerNsqf: 'NSQF ଅନୁରୂପ',
  tickerHumanLoop: 'ମାନବ ଯାଞ୍ଚ ସହିତ',
  tickerRegional: '୨୨ଟି ଭାରତୀୟ ଭାଷା',
  tickerOffline: 'ଅଫଲାଇନ୍ ସିଙ୍କ୍ ସୁବିଧା',
  tickerMinistry: 'ଦକ୍ଷତା ବିକାଶ ମନ୍ତ୍ରଣାଳୟ',
  ourWork: 'ଆମର କାର୍ଯ୍ୟ',
  work1Title: 'ସହଜ ଅନୁଭବ ମ୍ୟାପିଂ',
  work1Desc: 'ଶ୍ରମିକମାନଙ୍କ ପାଇଁ ନିଜ ଭାଷାରେ ଦକ୍ଷତା କହିବା ପାଇଁ ସହଜ ମାଧ୍ୟମ।',
  work2Title: 'ଭିଡିଓ ଏବଂ ଫଟୋ ମୂଲ୍ୟାଙ୍କନ',
  work2Desc: 'ପ୍ରାୟୋଗିକ କାମର ଆକଳନ ପାଇଁ ଦୃଶ୍ୟମାନ ପ୍ରମାଣ ସଂଗ୍ରହ।',
  work3Title: 'ମାନକ ସ୍କୋରିଂ',
  work3Desc: 'ପରୀକ୍ଷକମାନଙ୍କ ପାଇଁ NSQF ମାନଦଣ୍ଡ ଅନୁଯାୟୀ ସଠିକ୍ ମୂଲ୍ୟାଙ୍କନ।',
  work4Title: 'କମ୍ ଇଣ୍ଟରନେଟରେ ମଧ୍ୟ ସକ୍ଷମ',
  work4Desc: 'ଇଣ୍ଟରନେଟ୍ ନଥିଲେ ମଧ୍ୟ ଡାଟା ଫୋନରେ ସୁରକ୍ଷିତ ରହିଥାଏ।',
  tagSelfDecl: 'ସ୍ୱୟଂ ଘୋଷଣା',
  tagAiAssist: 'AI ସହାୟତା',
  tagPractical: 'ପ୍ରାକ୍ଟିକାଲ୍ ସାଧନ',
  tagMedia: 'ମିଡିଆ ପ୍ରମାଣ',
  tagAssessor: 'ପରୀକ୍ଷକ ସହାୟତା',
  tagNsqf: 'NSQF ମାନଦଣ୍ଡ',
  tagOffline: 'ଅଫଲାଇନ୍ କାର୍ଯ୍ୟକ୍ଷମ',
  tagSync: 'ଅଟୋ ସିଙ୍କ୍',
  feat1Title: 'ନିଜ ଅନୁଭବ କୁହନ୍ତୁ',
  feat1Desc: 'ନିଜ ଆଞ୍ଚଳିକ ଭାଷାରେ ଭଏସ୍ ଇନପୁଟ୍ ବ୍ୟବହାର କରନ୍ତୁ',
  feat2Title: 'ଆପଣଙ୍କ କାମ ଦେଖାନ୍ତୁ',
  feat2Desc: 'ଫଟୋ, ଭିଡିଓ ଏବଂ କାର୍ଯ୍ୟ ପ୍ରମାଣ ସହଜରେ ଅପଲୋଡ୍ କରନ୍ତୁ',
  feat3Title: 'NSQF ସହିତ ମେଳ',
  feat3Desc: 'AI ଆପଣଙ୍କ ଦକ୍ଷତାକୁ ଜାତୀୟ ମାନଦଣ୍ଡ ସହିତ ଯୋଡ଼ିଥାଏ',
  feat4Title: 'ମାନବ ପରୀକ୍ଷକଙ୍କ ନିଷ୍ପତ୍ତି',
  feat4Desc: 'AI ମତାମତ ଦିଏ, ପ୍ରମାଣିତ ବିଶେଷଜ୍ଞ ଚୂଡ଼ାନ୍ତ ନିଷ୍ପତ୍ତି ନିଅନ୍ତି',
  howItWorks: 'ଏହା କିପରି କାମ କରେ',
  howItWorksSub: 'ତିନୋଟି ସରଳ ପଦକ୍ଷେପ। କୌଣସି କଠିନ ପରୀକ୍ଷା ବା ଫର୍ମ ନାହିଁ।',
  step1Title: 'ଆପଣଙ୍କ ବିଷୟରେ କୁହନ୍ତୁ',
  step1Desc: 'ଆପଣଙ୍କ ବୃତ୍ତି ବାଛନ୍ତୁ। ଯେକୌଣସି ଭାଷାରେ ଆପଣଙ୍କ ଅନୁଭବ ବିଷୟରେ କୁହନ୍ତୁ।',
  step2Title: 'ଆପଣଙ୍କ କାମ ଦେଖାନ୍ତୁ',
  step2Desc: 'ଆପଣ ତିଆରି କରିଥିବା ଜିନିଷର ଫଟୋ ଉଠାନ୍ତୁ ବା ଛୋଟ ଭିଡିଓ କରନ୍ତୁ।',
  step3Title: 'ପ୍ରମାଣପତ୍ର ପାଆନ୍ତୁ',
  step3Desc: 'AI ଦକ୍ଷତା ଯାଞ୍ଚ କରେ ଏବଂ ସାର୍ଟିଫାଏଡ୍ ପରୀକ୍ଷକ ଜାତୀୟ ସାର୍ଟିଫିକେଟ୍ ପ୍ରଦାନ କରନ୍ତି।',
  ctaBannerTitlePortfolio: 'ଭାରତର କୁଶଳୀ ଶ୍ରମିକମାନଙ୍କୁ ଦିଅନ୍ତୁ ସରକାରୀ ସ୍ୱୀକୃତି।',
  ctaBannerTitleGovt: 'ଭାରତର ଶ୍ରମିକମାନଙ୍କ ପାଖରେ ହୁନର ଅଛି। ଆସନ୍ତୁ ଏହାକୁ ପ୍ରମାଣିତ କରିବା।',
  ctaBannerSub: 'ଅସଂଗଠିତ କ୍ଷେତ୍ରର ଶ୍ରମିକମାନଙ୍କ ପାଇଁ ବିଶେଷ ଭାବେ ନିର୍ମିତ।',
  beginSelfDeclaration: 'ସ୍ୱୟଂ ଘୋଷଣା ଆରମ୍ଭ କରନ୍ତୁ',
  welcomeCandidate: 'ସ୍ୱାଗତ, ରମେଶ 👋',
  candidateId: 'ପ୍ରାର୍ଥୀ ଆଇଡି: RPL-2024-8842',
  allSynced: 'ସମସ୍ତ ତଥ୍ୟ ସିଙ୍କ୍ ହୋଇଛି',
  newDeclaration: 'ନୂତନ ଘୋଷଣା',
  newDeclarationSub: 'ନୂଆ ଦକ୍ଷତା ମ୍ୟାପିଂ ଆରମ୍ଭ କରନ୍ତୁ',
  uploadEvidence: 'ପ୍ରମାଣ ଅପଲୋଡ୍ କରନ୍ତୁ',
  uploadEvidenceSub: 'ଫଟୋ ବା ଭିଡିଓ ଯୋଡ଼ନ୍ତୁ',
  viewCertificate: 'ପ୍ରମାଣପତ୍ର ଦେଖନ୍ତୁ',
  viewCertificateSub: 'ଆପଣଙ୍କ NSQF ପ୍ରମାଣପତ୍ର ଡାଉନଲୋଡ୍ କରନ୍ତୁ',
  yourApplications: 'ଆପଣଙ୍କ ଆବେଦନଗୁଡ଼ିକ',
  underReview: 'ସମୀକ୍ଷାଧୀନ',
  needMoreInfo: 'ଅଧିକ ସୂଚନା ଆବଶ୍ୟକ',
  certified: 'ପ୍ରମାଣିତ',
  nsqfLevel: 'NSQF ସ୍ତର',
  submittedAgo: '୨ ଦିନ ପୂର୍ବେ ଦାଖଲ ହୋଇଛି',
  assessorReviewing: 'ମୂଲ୍ୟାଙ୍କନକାରୀ ଆପଣଙ୍କ ପ୍ରମାଣ ଯାଞ୍ଚ କରୁଛନ୍ତି…',
  needClearerVideo: 'ୱାୟାରିଂ ସୁରକ୍ଷା ଯାଞ୍ଚର ସ୍ପଷ୍ଟ ଭିଡିଓ ଆବଶ୍ୟକ।',
  details: 'ବିବରଣୀ',
  uploadNow: 'ଏବେ ଅପଲୋଡ୍ କରନ୍ତୁ',
  downloadPdf: 'PDF ଡାଉନଲୋଡ୍ କରନ୍ତୁ',
  worksWithoutInternet: 'ଇଣ୍ଟରନେଟ୍ ବିନା ମଧ୍ୟ କାମ କରେ',
  worksWithoutInternetSub: 'ଇଣ୍ଟରନେଟ୍ ନଥିବା ସମୟରେ ମଧ୍ୟ ଆବେଦନ ଦେଖନ୍ତୁ ଓ ପ୍ରସ୍ତୁତ କରନ୍ତୁ। ଅନଲାଇନ୍ ଆସିଲେ ସ୍ୱୟଂଚାଳିତ ଭାବେ ସିଙ୍କ୍ ହେବ।',
  pendingReview: 'ସମୀକ୍ଷା ପାଇଁ ବାକି ଅଛି',
  searchCandidate: 'ପ୍ରାର୍ଥୀ ଖୋଜନ୍ତୁ…',
  aiDisclaimer: 'AI କେବଳ ପରାମର୍ଶ ଦିଏ। ଚୂଡ଼ାନ୍ତ ନିଷ୍ପତ୍ତି ମାନବ ପରୀକ୍ଷକଙ୍କର ହିଁ ରହିଥାଏ।',
  photos: 'ଫଟୋଗୁଡ଼ିକ',
  video: 'ଭିଡିଓ',
  aiSuggestion: 'AI ପରାମର୍ଶ',
  competent: 'ଦକ୍ଷ (ଯୋଗ୍ୟ)',
  needsReview: 'ପୁନର୍ବିଚାର ଆବଶ୍ୟକ',
  lowMatch: 'କମ୍ ମେଳ',
  yes: 'ହଁ',
  partial: 'ଆଂଶିକ',
  no: 'ନାହିଁ',
  saveDraft: 'ଡ୍ରାଫ୍ଟ ସେଭ୍ କରନ୍ତୁ',
  notYetCompetent: 'ଏପର୍ଯ୍ୟନ୍ତ ସମ୍ପୂର୍ଣ୍ଣ ପ୍ରସ୍ତୁତ ନୁହେଁ',
  requestEvidence: 'ଅଧିକ ପ୍ରମାଣ ମାଗନ୍ତୁ',
  recommendCert: 'ସାର୍ଟିଫିକେସନ୍ ପାଇଁ ସୁପାରିଶ କରନ୍ତୁ',
  selfDeclaration: 'ସ୍ୱୟଂ ଘୋଷଣା',
  selfDeclarationSub: 'ନିଜ ଦକ୍ଷତା ବିଷୟରେ ନିଜ ଭାଷାରେ କୁହନ୍ତୁ।',
  offlineReady: 'ଅଫଲାଇନ୍ ପ୍ରସ୍ତୁତ',
  step: 'ପଦକ୍ଷେପ',
  of: 'ରୁ',
  yourTrade: 'ଆପଣଙ୍କ ବୃତ୍ତି',
  experience: 'ଅନୁଭବ',
  evidence: 'ପ୍ରମାଣ',
  result: 'ଫଳାଫଳ',
  whatWork: 'ଆପଣ କଣ କାମ କରନ୍ତି?',
  tapPicture: 'ଆପଣଙ୍କ କାମ ସହ ମେଳ ଖାଉଥିବା ଛବିରେ ସ୍ପର୍ଶ କରନ୍ତୁ।',
  tellAboutWork: 'ଆପଣଙ୍କ କାମ ବିଷୟରେ କୁହନ୍ତୁ',
  pressAndSpeak: 'ଦବାନ୍ତୁ ଏବଂ କୁହନ୍ତୁ',
  speakAnyLang: 'ଯେକୌଣସି ଭାଷାରେ କୁହନ୍ତୁ',
  listening: '🔴 ଶୁଣୁଛୁ… ଏବେ କୁହନ୍ତୁ',
  howManyYears: 'ଆପଣ କେତେ ବର୍ଷ ଧରି ଏହି କାମ କରୁଛନ୍ତି?',
  whatTools: 'ଆପଣ କେଉଁ କେଉଁ ଯନ୍ତ୍ରପାତି ବ୍ୟବହାର କରନ୍ତି?',
  whatKindWork: 'ସାଧାରଣତଃ ଆପଣ କେଉଁ ପ୍ରକାରର କାମ କରନ୍ତି?',
  whereWork: 'ଆପଣ କେଉଁଠାରେ କାମ କରନ୍ତି?',
  showYourWork: 'ଆପଣଙ୍କ କାମ ଦେଖାନ୍ତୁ',
  evidenceSub: 'ଫଟୋ ଓ ଭିଡିଓ ପରୀକ୍ଷକଙ୍କୁ ଆପଣଙ୍କ ଦକ୍ଷତା ବୁଝିବାରେ ସାହାଯ୍ୟ କରେ।',
  takePhoto: 'ଫଟୋ ଉଠାନ୍ତୁ',
  takePhotoSub: 'ଆପଣଙ୍କ କାମର',
  recordVideo: 'ଭିଡିଓ କରନ୍ତୁ',
  recordVideoSub: 'ଗୋଟିଏ ଛୋଟ ଭିଡିଓ',
  uploadPaper: 'କାଗଜପତ୍ର ଅପଲୋଡ୍ କରନ୍ତୁ',
  uploadPaperSub: 'ପ୍ରମାଣପତ୍ର ବା ଅନୁଭବ ଚିଠି',
  dragFiles: 'କିମ୍ବା ଫାଇଲ୍ ଏଠାକୁ ଟାଣି ଆଣନ୍ତୁ',
  fileTypes: 'JPG, PNG, MP4, PDF — ୫୦ MB ପର୍ଯ୍ୟନ୍ତ',
  offlineUpload: 'ଇଣ୍ଟରନେଟ୍ ବିନା ମଧ୍ୟ ଆପଣ ଏହା କରିପାରିବେ।',
  offlineUploadSub: 'ଫାଇଲ୍ ଫୋନରେ ସୁରକ୍ଷିତ ରହିବ ଏବଂ ନେଟ୍ ଆସିଲେ ଅପଲୋଡ୍ ହେବ।',
  suggestedMatch: 'ପ୍ରସ୍ତାବିତ ମେଳ',
  match: 'ମେଳ',
  humanReview: 'ମାନବ ମୂଲ୍ୟାଙ୍କନକାରୀ ଯାଞ୍ଚ କରି ନିଷ୍ପତ୍ତି ନେବେ।',
  humanReviewSub: 'ଏହା କମ୍ପ୍ୟୁଟରର ପ୍ରାଥମିକ ସୂଚନା ମାତ୍ର। ପ୍ରମାଣିତ ପରୀକ୍ଷକ ଚୂଡ଼ାନ୍ତ ନିଷ୍ପତ୍ତି ନେବେ।',
  back: 'ପଛକୁ',
  next: 'ପରବର୍ତ୍ତୀ',
  submit: 'ଦାଖଲ କରନ୍ତୁ',
  orTypeBelow: 'ବଟନ୍ ଦବାଇ କୁହନ୍ତୁ କିମ୍ବା ତଳେ ଲେଖନ୍ତୁ।',
  electrician: 'ଇଲେକ୍ଟ୍ରିସିଆନ',
  plumber: 'ପ୍ଲମ୍ବର',
  welder: 'ୱେଲଡର',
  carpenter: 'ବଢ଼େଇ',
  mason: 'ରାଜମିସ୍ତ୍ରୀ',
  tailor: 'ଦର୍ଜୀ',
  cook: 'ରୋଷେୟା',
  driver: 'ଡ୍ରାଇଭର',
  other: 'ଅନ୍ୟାନ୍ୟ',
  performBasicWork: 'ମୌଳିକ ବୈଷୟିକ କାର୍ଯ୍ୟ କରିବା',
  readDrawings: 'ସରଳ ନକ୍ସା ବୁଝିବା',
  followSafety: 'କର୍ମକ୍ଷେତ୍ରର ସୁରକ୍ଷା ନିୟମ ପାଳନ କରିବା',
  footerDesc: 'ସ୍ମାର୍ଟ ଇଣ୍ଡିଆ ହାକାଥନ୍ ଅଧୀନରେ ପୂର୍ବ ଶିକ୍ଷଣର ସ୍ୱୀକୃତି (RPL) ପାଇଁ AI-ଆଧାରିତ ଦକ୍ଷତା ମୂଲ୍ୟାଙ୍କନ ଉପକରଣ।',
  sponsoredBy: 'ପ୍ରାୟୋଜକ',
  msdeFullName: 'ଦକ୍ଷତା ବିକାଶ ଓ ଉଦ୍ୟୋଗିତା ମନ୍ତ୍ରଣାଳୟ (MSDE)',
  ncvetFullName: 'ଜାତୀୟ ବୃତ୍ତିଗତ ଶିକ୍ଷା ଏବଂ ତାଲିମ ପରିଷଦ (NCVET)',
  project: 'ପ୍ରକଳ୍ପ',
  problemId: 'ସମସ୍ୟା ଆଇଡି: SIH26242',
  themeSmartEdu: 'ଥିମ୍: ସ୍ମାର୍ଟ ଶିକ୍ଷା',
  categorySoftware: 'ବର୍ଗ: ସଫ୍ଟୱେୟାର୍',
  footerCopyright: '© ୨୦୨୬ RPL AI ମୂଲ୍ୟାଙ୍କନ ଉପକରଣ — ଭାରତର କୁଶଳୀ ଶ୍ରମିକମାନଙ୍କ ପାଇଁ ନିର୍ମିତ'
};

export const mai = {
  navHome: 'होम',
  navSelfDeclaration: 'स्वघोषणा',
  navCandidate: 'उम्मीदवार',
  navAssessor: 'परीक्षक',
  govtInitiative: 'भारत सरकारक पहल',
  ministryName: 'कौशल विकास आ उद्यमिता मंत्रालय',
  rplAiAssessment: 'आरपीएल एआई कौशल मूल्यांकन',
  heroTitle: 'अपन कौशलक प्रमाणपत्र पाबू',
  heroSub: 'काजक दौरान सिखनिहार श्रमिक लोकनिक लेल। कोनो औपचारिक शिक्षाक आवश्यकता नहि।',
  portfolioHeroH1_1: 'कौशल परखु।',
  portfolioHeroH1_2: 'अनुभवक',
  portfolioHeroH1_3: ' प्रमाणीकरण करू।',
  portfolioHeroH1_4: 'आरपीएल विस्तार।',
  startAssessment: 'मूल्यांकन शुरू करू',
  assessorLogin: 'परीक्षक लॉगिन',
  makeItClear: '०१ — स्पष्ट आ पारदर्शी',
  buildShapeShip: 'सीखू / बनाबू / आगाँ बढ़ू',
  tickerAiAssisted: 'एआई-सहायता प्राप्त आरपीएल',
  tickerNsqf: 'एनएसक्यूएफ अनुरूप',
  tickerHumanLoop: 'मानवीय सत्यापन युक्त',
  tickerRegional: '२२ भारतीय भाषा',
  tickerOffline: 'ऑफलाइन-प्रथम सिंक',
  tickerMinistry: 'कौशल विकास मंत्रालय',
  ourWork: 'हमर काज',
  work1Title: 'सहज अनुभव मानचित्रण',
  work1Desc: 'श्रमिक लोकनिक लेल अपन भाषामे कौशल बतयबाक संवादात्मक इंटरफ़ेस।',
  work2Title: 'वीडियो आ फोटो मूल्यांकन',
  work2Desc: 'व्यावहारिक काजक आंकलन लेल दृश्य प्रमाण संग्रह।',
  work3Title: 'मानकीकृत स्कोरिंग',
  work3Desc: 'परीक्षक लोकनिक लेल एनएसक्यूएफ मानकक अनुरूप सटीक स्कोरिंग।',
  work4Title: 'कम इंटरनेटमे सेहो सक्षम',
  work4Desc: 'इंटरनेट नहि रहला परो डाटा फोनमे सुरक्षित रहैत अछि।',
  tagSelfDecl: 'स्वघोषणा',
  tagAiAssist: 'एआई सहायता',
  tagPractical: 'व्यावहारिक साधन',
  tagMedia: 'मीडिया प्रमाण',
  tagAssessor: 'परीक्षक सहयोग',
  tagNsqf: 'एनएसक्यूएफ मानक',
  tagOffline: 'ऑफलाइन सक्षम',
  tagSync: 'ऑटो सिंक',
  feat1Title: 'अपन अनुभव बाजी',
  feat1Desc: 'अपन क्षेत्रीय भाषामे आवाजसँ जानकारी दिअ',
  feat2Title: 'अपन काज देखाउ',
  feat2Desc: 'फ़ोटो, वीडियो आ काजक प्रमाण आसानीसँ अपलोड करू',
  feat3Title: 'एनएसक्यूएफसँ मिलान',
  feat3Desc: 'एआई अहाँक व्यावहारिक कौशलकेँ राष्ट्रीय मानकक संग जोड़ैत अछि',
  feat4Title: 'मानव परीक्षकक निर्णय',
  feat4Desc: 'एआई स्कोर सुझबैत अछि, प्रमाणित विशेषज्ञ अंतिम निर्णय लैत छथि',
  howItWorks: 'ई कोना काज करैत अछि',
  howItWorksSub: 'तीनटा सरल चरण। कोनो कठिन परीक्षा वा जटिल फ़ॉर्म नहि।',
  step1Title: 'अपन बारेमे बताउ',
  step1Desc: 'अपन पेशा चुनू। कोनो भाषामे अपन काजक अनुभवक संबंधमे बाजि कऽ बताउ।',
  step2Title: 'अपन काज देखाउ',
  step2Desc: 'अपन बनाओल वा ठीक कएल सामानक फोटो खींचू वा छोट वीडियो बनाउ।',
  step3Title: 'प्रमाणपत्र पाबू',
  step3Desc: 'एआई कौशल मिलान करैत अछि आ प्रमाणित परीक्षक राष्ट्रीय प्रमाणपत्र जारी करैत छथि।',
  ctaBannerTitlePortfolio: 'भारतक हुनरकेँ दिअ आधिकारिक पहचान।',
  ctaBannerTitleGovt: 'भारतक कार्यबलमे हुनर अछि। आउ एकरा प्रमाणित करी।',
  ctaBannerSub: 'असंगठित क्षेत्रक कामगार लोकनिक लेल विशेष रूपसँ बनाओल गेल।',
  beginSelfDeclaration: 'स्वघोषणा शुरू करू',
  welcomeCandidate: 'प्रणाम, रमेश 👋',
  candidateId: 'उम्मीदवार आईडी: RPL-2024-8842',
  allSynced: 'सब डाटा सिंक भऽ गेल',
  newDeclaration: 'नव घोषणा',
  newDeclarationSub: 'नव कौशल मूल्यांकन शुरू करू',
  uploadEvidence: 'प्रमाण अपलोड करू',
  uploadEvidenceSub: 'फोटो वा वीडियो जोड़ू',
  viewCertificate: 'प्रमाणपत्र देखू',
  viewCertificateSub: 'अपन एनएसक्यूएफ प्रमाणपत्र डाउनलोड करू',
  yourApplications: 'अहाँक आवेदन',
  underReview: 'समीक्षाधीन',
  needMoreInfo: 'आर जानकारी चाही',
  certified: 'प्रमाणित',
  nsqfLevel: 'एनएसक्यूएफ स्तर',
  submittedAgo: '२ दिन पहिने जमा कएल गेल',
  assessorReviewing: 'परीक्षक अहाँक प्रमाणक जांच कऽ रहल छथि…',
  needClearerVideo: 'परीक्षककेँ वायरिंग सुरक्षा जांचक स्पष्ट वीडियो चाही।',
  details: 'विवरण',
  uploadNow: 'एखने अपलोड करू',
  downloadPdf: 'पीडीएफ डाउनलोड करू',
  worksWithoutInternet: 'बिना इंटरनेट सेहो काज करैत अछि',
  worksWithoutInternetSub: 'इंटरनेट नहि रहला परो आवेदन देखू आ बनाउ। ऑनलाइन अएला पर अपने सिंक भऽ जाएत।',
  pendingReview: 'समीक्षा लेल लंबित',
  searchCandidate: 'उम्मीदवार खोजू…',
  aiDisclaimer: 'एआई केवल सुझाव दैत अछि। अंतिम प्रमाणीकरण निर्णय मानवीय परीक्षकक होइत अछि।',
  photos: 'तस्वीर',
  video: 'वीडियो',
  aiSuggestion: 'एआई सुझाव',
  competent: 'योग्य (सक्षम)',
  needsReview: 'पुनरावलोकन आवश्यक',
  lowMatch: 'कम मेल',
  yes: 'हँ',
  partial: 'आंशिक',
  no: 'नहि',
  saveDraft: 'ड्राफ्ट सहेजू',
  notYetCompetent: 'एखन योग्य नहि',
  requestEvidence: 'अतिरिक्त प्रमाण मांगू',
  recommendCert: 'प्रमाणनक सिफारिश करू',
  selfDeclaration: 'स्वघोषणा',
  selfDeclarationSub: 'अपन कौशलक बारेमे बताउ — अपन भाषामे।',
  offlineReady: 'ऑफलाइन सक्षम',
  step: 'चरण',
  of: 'क',
  yourTrade: 'अहाँक पेशा',
  experience: 'अनुभव',
  evidence: 'प्रमाण',
  result: 'परिणाम',
  whatWork: 'अहाँ की काज करैत छी?',
  tapPicture: 'ओहि चित्र पर टैप करू जे अहाँक काजसँ मेल खाइत अछि।',
  tellAboutWork: 'अपन काजक बारेमे बताउ',
  pressAndSpeak: 'दबाउ आ बाजु',
  speakAnyLang: 'कोनो भाषामे बाजु',
  listening: '🔴 सुनि रहल छी… आब बाजु',
  howManyYears: 'अहाँ कतेक वर्षसँ ई काज कऽ रहल छी?',
  whatTools: 'अहाँ कोन औजार प्रयोग करैत छी?',
  whatKindWork: 'अहाँ सामान्यतया कोना काज करैत छी?',
  whereWork: 'अहाँ कतय काज करैत छी?',
  showYourWork: 'अपन काज देखाउ',
  evidenceSub: 'फोटो आ वीडियो परीक्षककेँ अहाँक हुनर बुझबामे मदद करैत अछि।',
  takePhoto: 'फोटो लिअ',
  takePhotoSub: 'अपन काजक',
  recordVideo: 'वीडियो बनाउ',
  recordVideoSub: 'एकटा छोट वीडियो',
  uploadPaper: 'दस्तावेज़ अपलोड करू',
  uploadPaperSub: 'प्रमाणपत्र वा अनुभव पत्र',
  dragFiles: 'वा फ़ाइल एतय घींचू',
  fileTypes: 'JPG, PNG, MP4, PDF — ५० MB धरि',
  offlineUpload: 'अहाँ ई बिना इंटरनेट सेहो कऽ सकैत छी।',
  offlineUploadSub: 'फ़ाइल अहाँक फोनमे सुरक्षित रहत आ ऑनलाइन अएला पर अपलोड भऽ जाएत।',
  suggestedMatch: 'सुझाओल गेल मेल',
  match: 'मेल',
  humanReview: 'एकटा मानव परीक्षक समीक्षा कऽ निर्णय लेताह।',
  humanReviewSub: 'ई कंप्यूटरक प्रारंभिक सुझाव अछि। प्रमाणित परीक्षक समीक्षा कऽ अंतिम निर्णय लेताह।',
  back: 'पाछाँ',
  next: 'आगाँ',
  submit: 'जमा करू',
  orTypeBelow: 'बटन दबा कऽ बाजु वा नीचाँ लिखू।',
  electrician: 'इलेक्ट्रीशियन',
  plumber: 'प्लम्बर',
  welder: 'वेल्डर',
  carpenter: 'बढ़ई',
  mason: 'राजमिस्त्री',
  tailor: 'दर्जी',
  cook: 'रसोइया',
  driver: 'ड्राइवर',
  other: 'आन',
  performBasicWork: 'बुनियादी तकनीकी काज करब',
  readDrawings: 'सरल रेखाचित्र पढ़ब',
  followSafety: 'कार्यस्थल सुरक्षा नियमक पालन',
  footerDesc: 'स्मार्ट इंडिया हैकाथॉनक तहत पूर्व शिक्षणक मान्यता (RPL) लेल एआई-संचालित कौशल मूल्यांकन प्रणाली।',
  sponsoredBy: 'प्रायोजक',
  msdeFullName: 'कौशल विकास आ उद्यमिता मंत्रालय (MSDE)',
  ncvetFullName: 'राष्ट्रीय व्यावसायिक शिक्षा आ प्रशिक्षण परिषद (NCVET)',
  project: 'परियोजना',
  problemId: 'समस्या आईडी: SIH26242',
  themeSmartEdu: 'थीम: स्मार्ट शिक्षा',
  categorySoftware: 'श्रेणी: सॉफ्टवेयर',
  footerCopyright: '© २०२६ आरपीएल एआई मूल्यांकन उपकरण — भारतक कुशल कार्यबल लेल निर्मित'
};
