export const hi = {
  navHome: 'होम',
  navSelfDeclaration: 'स्वघोषणा',
  navCandidate: 'उम्मीदवार',
  navAssessor: 'मूल्यांकनकर्ता',
  govtInitiative: 'भारत सरकार की पहल',
  ministryName: 'कौशल विकास एवं उद्यमिता मंत्रालय',
  rplAiAssessment: 'आरपीएल एआई कौशल मूल्यांकन',
  heroTitle: 'अपने कौशल को प्रमाणित कराएं',
  heroSub: 'काम के दौरान सीखने वाले श्रमिकों के लिए। औपचारिक शिक्षा की आवश्यकता नहीं।',
  portfolioHeroH1_1: 'कौशल परखें।',
  portfolioHeroH1_2: 'अनुभव को',
  portfolioHeroH1_3: ' प्रमाणित करें।',
  portfolioHeroH1_4: 'आरपीएल विस्तार।',
  startAssessment: 'मूल्यांकन शुरू करें',
  assessorLogin: 'मूल्यांकनकर्ता लॉगिन',
  makeItClear: '०१ — स्पष्ट और पारदर्शी',
  buildShapeShip: 'सीखें / बनाएं / आगे बढ़ें',
  tickerAiAssisted: 'एआई-सहायता प्राप्त आरपीएल',
  tickerNsqf: 'एनएसक्यूएफ अनुरूप',
  tickerHumanLoop: 'मानवीय सत्यापन युक्त',
  tickerRegional: '२२ भारतीय भाषाएं',
  tickerOffline: 'ऑफ़लाइन-प्रथम सिंक',
  tickerMinistry: 'कौशल विकास मंत्रालय',
  ourWork: 'हमारा कार्य',
  work1Title: 'सहज अनुभव मानचित्रण',
  work1Desc: 'श्रमिकों के लिए अपनी भाषा में कौशल बताने हेतु संवादात्मक इंटरफ़ेस।',
  work2Title: 'वीडियो और फोटो मूल्यांकन',
  work2Desc: 'व्यावहारिक कार्य के आकलन हेतु दृश्य प्रमाण संग्रह।',
  work3Title: 'मानकीकृत स्कोरिंग',
  work3Desc: 'मूल्यांकनकर्ताओं के लिए एनएसक्यूएफ मानकों के अनुरूप सटीक स्कोरिंग।',
  work4Title: 'कम इंटरनेट में भी सक्षम',
  work4Desc: 'इंटरनेट न होने पर भी डेटा डिवाइस में सुरक्षित रहता है।',
  tagSelfDecl: 'स्वघोषणा',
  tagAiAssist: 'एआई सहायता',
  tagPractical: 'व्यावहारिक साधन',
  tagMedia: 'मीडिया प्रमाण',
  tagAssessor: 'परीक्षक सहयोग',
  tagNsqf: 'एनएसक्यूएफ मानक',
  tagOffline: 'ऑफ़लाइन सक्षम',
  tagSync: 'ऑटो सिंक',
  feat1Title: 'अपने अनुभव को बोलें',
  feat1Desc: 'अपनी क्षेत्रीय भाषा में बोलकर जानकारी दें',
  feat2Title: 'अपना काम दिखाएं',
  feat2Desc: 'फ़ोटो, वीडियो और कार्य प्रमाण आसानी से अपलोड करें',
  feat3Title: 'एनएसक्यूएफ से मिलान',
  feat3Desc: 'एआई आपके व्यावहारिक कौशल को राष्ट्रीय मानकों से जोड़ता है',
  feat4Title: 'मानव परीक्षक का निर्णय',
  feat4Desc: 'एआई स्कोर सुझाता है, प्रमाणित विशेषज्ञ अंतिम निर्णय लेते हैं',
  howItWorks: 'यह कैसे काम करता है',
  howItWorksSub: 'तीन आसान चरण। कोई कठिन परीक्षा या जटिल फॉर्म नहीं।',
  step1Title: 'अपने बारे में बताएं',
  step1Desc: 'अपना पेशा चुनें। किसी भी भाषा में अपने काम के अनुभव के बारे में बोलकर बताएं।',
  step2Title: 'अपना काम दिखाएं',
  step2Desc: 'अपने बनाए या ठीक किए गए सामान की फोटो खींचें या छोटा वीडियो रिकॉर्ड करें।',
  step3Title: 'प्रमाणपत्र पाएं',
  step3Desc: 'एआई कौशल मिलान करता है और प्रमाणित परीक्षक समीक्षा करके राष्ट्रीय प्रमाणपत्र जारी करता है।',
  ctaBannerTitlePortfolio: 'भारत के हुनर को दें आधिकारिक पहचान।',
  ctaBannerTitleGovt: 'भारत के कार्यबल में हुनर है। आइए इसे प्रमाणित करें।',
  ctaBannerSub: 'असंगठित क्षेत्र के कामगारों के लिए विशेष रूप से डिज़ाइन किया गया।',
  beginSelfDeclaration: 'स्वघोषणा शुरू करें',
  welcomeCandidate: 'नमस्ते, रमेश 👋',
  candidateId: 'उम्मीदवार आईडी: RPL-2024-8842',
  allSynced: 'सभी डेटा सिंक हो गया',
  newDeclaration: 'नई घोषणा',
  newDeclarationSub: 'नया कौशल मूल्यांकन शुरू करें',
  uploadEvidence: 'प्रमाण अपलोड करें',
  uploadEvidenceSub: 'फोटो या वीडियो जोड़ें',
  viewCertificate: 'प्रमाणपत्र देखें',
  viewCertificateSub: 'अपना एनएसक्यूएफ प्रमाणपत्र डाउनलोड करें',
  yourApplications: 'आपके आवेदन',
  underReview: 'समीक्षाधीन',
  needMoreInfo: 'अधिक जानकारी चाहिए',
  certified: 'प्रमाणित',
  nsqfLevel: 'एनएसक्यूएफ स्तर',
  submittedAgo: '२ दिन पहले जमा किया',
  assessorReviewing: 'मूल्यांकनकर्ता आपके प्रमाणों की जांच कर रहा है…',
  needClearerVideo: 'मूल्यांकनकर्ता को वायरिंग सुरक्षा जांच का स्पष्ट वीडियो चाहिए।',
  details: 'विवरण',
  uploadNow: 'अभी अपलोड करें',
  downloadPdf: 'पीडीएफ डाउनलोड करें',
  worksWithoutInternet: 'बिना इंटरनेट के भी काम करता है',
  worksWithoutInternetSub: 'इंटरनेट न होने पर भी आवेदन देखें व बनाएं। ऑनलाइन आने पर स्वतः सिंक होगा।',
  pendingReview: 'समीक्षा हेतु लंबित',
  searchCandidate: 'उम्मीदवार खोजें…',
  aiDisclaimer: 'एआई केवल सुझाव देता है। अंतिम प्रमाणीकरण निर्णय मानवीय परीक्षक का ही होता है।',
  photos: 'तस्वीरें',
  video: 'वीडियो',
  aiSuggestion: 'एआई सुझाव',
  competent: 'योग्य (सक्षम)',
  needsReview: 'पुनरावलोकन आवश्यक',
  lowMatch: 'कम मेल',
  yes: 'हाँ',
  partial: 'आंशिक',
  no: 'नहीं',
  saveDraft: 'ड्राफ्ट सहेजें',
  notYetCompetent: 'अभी योग्य नहीं',
  requestEvidence: 'अतिरिक्त प्रमाण मांगें',
  recommendCert: 'प्रमाणन की सिफारिश करें',
  selfDeclaration: 'स्वघोषणा',
  selfDeclarationSub: 'अपने कौशल के बारे में बताएं — अपनी भाषा में।',
  offlineReady: 'ऑफ़लाइन सक्षम',
  step: 'चरण',
  of: 'का',
  yourTrade: 'आपका पेशा',
  experience: 'अनुभव',
  evidence: 'प्रमाण',
  result: 'परिणाम',
  whatWork: 'आप क्या काम करते हैं?',
  tapPicture: 'उस चित्र पर टैप करें जो आपके काम से मेल खाता है।',
  tellAboutWork: 'अपने काम के बारे में बताएं',
  pressAndSpeak: 'दबाएं और बोलें',
  speakAnyLang: 'किसी भी भाषा में बोलें',
  listening: '🔴 सुन रहे हैं… अब बोलें',
  howManyYears: 'आप कितने वर्षों से यह काम कर रहे हैं?',
  whatTools: 'आप कौन से औजार इस्तेमाल करते हैं?',
  whatKindWork: 'आप आमतौर पर किस तरह का काम करते हैं?',
  whereWork: 'आप कहां काम करते हैं?',
  showYourWork: 'अपना काम दिखाएं',
  evidenceSub: 'फोटो और वीडियो से परीक्षक को आपका हुनर देखने में मदद मिलती है।',
  takePhoto: 'फोटो लें',
  takePhotoSub: 'अपने काम की',
  recordVideo: 'वीडियो बनाएं',
  recordVideoSub: 'एक छोटा वीडियो',
  uploadPaper: 'दस्तावेज़ अपलोड करें',
  uploadPaperSub: 'प्रमाणपत्र या अनुभव पत्र',
  dragFiles: 'या फ़ाइलें यहाँ खींचें',
  fileTypes: 'JPG, PNG, MP4, PDF — 50 MB तक',
  offlineUpload: 'आप यह बिना इंटरनेट के भी कर सकते हैं।',
  offlineUploadSub: 'फ़ाइलें आपके फोन में सुरक्षित रहेंगी और ऑनलाइन आने पर अपलोड होंगी।',
  suggestedMatch: 'सुझाया गया मेल',
  match: 'मेल',
  humanReview: 'एक मानव परीक्षक समीक्षा करके निर्णय लेगा।',
  humanReviewSub: 'यह कंप्यूटर का प्रारंभिक सुझाव है। प्रमाणित परीक्षक समीक्षा करके अंतिम निर्णय लेंगे।',
  back: 'पीछे',
  next: 'आगे',
  submit: 'जमा करें',
  orTypeBelow: 'बटन दबाकर बोलें या नीचे लिखें।',
  electrician: 'इलेक्ट्रीशियन',
  plumber: 'प्लम्बर',
  welder: 'वेल्डर',
  carpenter: 'बढ़ई',
  mason: 'राजमिस्त्री',
  tailor: 'दर्जी',
  cook: 'रसोइया',
  driver: 'ड्राइवर',
  other: 'अन्य',
  performBasicWork: 'बुनियादी तकनीकी काम करना',
  readDrawings: 'सरल रेखाचित्र पढ़ना',
  followSafety: 'कार्यस्थल सुरक्षा नियमों का पालन',
  footerDesc: 'स्मार्ट इंडिया हैकथॉन के तहत पूर्व शिक्षण की मान्यता (RPL) हेतु एआई-संचालित कौशल मूल्यांकन प्रणाली।',
  sponsoredBy: 'प्रायोजक',
  msdeFullName: 'कौशल विकास एवं उद्यमिता मंत्रालय (MSDE)',
  ncvetFullName: 'राष्ट्रीय व्यावसायिक शिक्षा एवं प्रशिक्षण परिषद (NCVET)',
  project: 'परियोजना',
  problemId: 'समस्या आईडी: SIH26242',
  themeSmartEdu: 'थीम: स्मार्ट शिक्षा',
  categorySoftware: 'श्रेणी: सॉफ्टवेयर',
  footerCopyright: '© २०२६ आरपीएल एआई मूल्यांकन उपकरण — भारत के कुशल कार्यबल के लिए निर्मित'
};

export const mr = {
  navHome: 'मुख्यपृष्ठ',
  navSelfDeclaration: 'स्वयंघोषणा',
  navCandidate: 'उमेदवार',
  navAssessor: 'मूल्यांकनकर्ता',
  govtInitiative: 'भारत सरकारचा उपक्रम',
  ministryName: 'कौशल्य विकास आणि उद्योजकता मंत्रालय',
  rplAiAssessment: 'आरपीएल एआय कौशल्य मूल्यांकन',
  heroTitle: 'आपल्या कौशल्यांचे प्रमाणीकरण करा',
  heroSub: 'कामातून शिकणाऱ्या कामगारांसाठी. औपचारिक शिक्षणाची गरज नाही.',
  portfolioHeroH1_1: 'कौशल्य परखा.',
  portfolioHeroH1_2: 'अनुभवाला',
  portfolioHeroH1_3: ' प्रमाणपत्र द्या.',
  portfolioHeroH1_4: 'आरपीएल विस्तार.',
  startAssessment: 'मूल्यांकन सुरू करा',
  assessorLogin: 'मूल्यांकनकर्ता लॉगिन',
  makeItClear: '०१ — स्पष्ट आणि पारदर्शक',
  buildShapeShip: 'शिका / घडवा / प्रगती करा',
  tickerAiAssisted: 'एआय-सहाय्यित आरपीएल',
  tickerNsqf: 'एनएसक्यूएफ सुसंगत',
  tickerHumanLoop: 'मानवी पडताळणीसह',
  tickerRegional: '२२ भारतीय भाषा',
  tickerOffline: 'ऑफलाइन-प्रथम सिंक',
  tickerMinistry: 'कौशल्य विकास मंत्रालय',
  ourWork: 'आमचे कार्य',
  work1Title: 'सुलभ अनुभव मॅपिंग',
  work1Desc: 'कामगारांना स्वतःच्या भाषेत कौशल्ये सांगण्यासाठी संवादात्मक इंटरफेस.',
  work2Title: 'व्हिडिओ व फोटो मूल्यांकन',
  work2Desc: 'प्रत्यक्ष कामाच्या मूल्यमापनासाठी दृश्य पुराव्यांचे संकलन.',
  work3Title: 'प्रमाणित स्कोअरिंग',
  work3Desc: 'मूल्यांकनकर्त्यांसाठी एनएसक्यूएफ मानकांनुसार अचूक गुणांकन.',
  work4Title: 'कमी इंटरनेटमध्येही सक्षम',
  work4Desc: 'इंटरनेट नसतानाही माहिती फोनमध्ये सुरक्षित राहते.',
  tagSelfDecl: 'स्वयंघोषणा',
  tagAiAssist: 'एआय सहाय्य',
  tagPractical: 'प्रत्यक्ष साधन',
  tagMedia: 'मीडिया पुरावा',
  tagAssessor: 'परीक्षक सहकार्य',
  tagNsqf: 'एनएसक्यूएफ मानक',
  tagOffline: 'ऑफलाइन सक्षम',
  tagSync: 'ऑटो सिंक',
  feat1Title: 'तुमचा अनुभव बोला',
  feat1Desc: 'तुमच्या स्वतःच्या प्रादेशिक भाषेत व्हॉइस इनपुट वापरा',
  feat2Title: 'तुमचे काम दाखवा',
  feat2Desc: 'फोटो, व्हिडिओ आणि कामाचे पुरावे सहज अपलोड करा',
  feat3Title: 'एनएसक्यूएफशी जुळणी',
  feat3Desc: 'एआय तुमच्या कौशल्यांचे राष्ट्रीय मानकांशी मॅपिंग करते',
  feat4Title: 'मानवी मूल्यांकनकर्त्याचा निर्णय',
  feat4Desc: 'एआय गुण सुचवते, प्रमाणित तज्ञ अंतिम निर्णय घेतात',
  howItWorks: 'हे कसे कार्य करते',
  howItWorksSub: 'तीन सोप्या पायऱ्या. कोणतीही कठीण परीक्षा किंवा फॉर्म नाही.',
  step1Title: 'तुमच्याबद्दल सांगा',
  step1Desc: 'तुमचा व्यवसाय निवडा. तुमच्या अनुभवाबद्दल कोणत्याही भाषेत बोला.',
  step2Title: 'तुमचे काम दाखवा',
  step2Desc: 'तुम्ही तयार केलेल्या वस्तूंचे फोटो काढा किंवा छोटा व्हिडिओ बनवा.',
  step3Title: 'प्रमाणपत्र मिळवा',
  step3Desc: 'एआय कौशल्ये तपासते आणि प्रमाणित परीक्षक राष्ट्रीय प्रमाणपत्र देतो.',
  ctaBannerTitlePortfolio: 'भारतातील कुशल हातांना द्या अधिकृत सन्मान.',
  ctaBannerTitleGovt: 'भारतातील कामगारांकडे कौशल्य आहे. त्याचे प्रमाणीकरण करूया.',
  ctaBannerSub: 'असंघटित क्षेत्रातील कामगारांसाठी विशेषतः विकसित.',
  beginSelfDeclaration: 'स्वयंघोषणा सुरू करा',
  welcomeCandidate: 'नमस्कार, रमेश 👋',
  candidateId: 'उमेदवार आयडी: RPL-2024-8842',
  allSynced: 'सर्व सिंक झाले',
  newDeclaration: 'नवीन घोषणा',
  newDeclarationSub: 'नवीन कौशल्य मॅपिंग सुरू करा',
  uploadEvidence: 'पुरावा अपलोड करा',
  uploadEvidenceSub: 'फोटो किंवा व्हिडिओ जोडा',
  viewCertificate: 'प्रमाणपत्र पहा',
  viewCertificateSub: 'तुमचे एनएसक्यूएफ प्रमाणपत्र डाउनलोड करा',
  yourApplications: 'तुमचे अर्ज',
  underReview: 'पुनरावलोकन चालू',
  needMoreInfo: 'अधिक माहिती हवी आहे',
  certified: 'प्रमाणित',
  nsqfLevel: 'एनएसक्यूएफ स्तर',
  submittedAgo: '२ दिवसांपूर्वी पाठवले',
  assessorReviewing: 'परीक्षक तुमच्या पुराव्यांची तपासणी करत आहेत…',
  needClearerVideo: 'परीक्षकाला वायरिंग सुरक्षिततेचा अधिक स्पष्ट व्हिडिओ हवा आहे.',
  details: 'तपशील',
  uploadNow: 'आता अपलोड करा',
  downloadPdf: 'पीडीएफ डाउनलोड करा',
  worksWithoutInternet: 'इंटरनेटशिवाय कार्य करते',
  worksWithoutInternetSub: 'इंटरनेट नसतानाही अर्ज पहा आणि तयार करा. ऑनलाइन आल्यावर आपोआप सिंक होईल.',
  pendingReview: 'समीक्षेसाठी प्रलंबित',
  searchCandidate: 'उमेदवार शोधा…',
  aiDisclaimer: 'एआय फक्त साहाय्य करते. अंतिम प्रमाणीकरणाचा निर्णय मानवी परीक्षकाचाच असतो.',
  photos: 'फोटो',
  video: 'व्हिडिओ',
  aiSuggestion: 'एआय सूचना',
  competent: 'सक्षम (योग्य)',
  needsReview: 'पुनरावलोकन आवश्यक',
  lowMatch: 'कमी जुळणी',
  yes: 'होय',
  partial: 'अंशतः',
  no: 'नाही',
  saveDraft: 'मसुदा जतन करा',
  notYetCompetent: 'अद्याप सक्षम नाही',
  requestEvidence: 'अधिक पुरावा मागा',
  recommendCert: 'प्रमाणपत्राची शिफारस करा',
  selfDeclaration: 'स्वयंघोषणा',
  selfDeclarationSub: 'तुमच्या कौशल्यांबद्दल सांगा — तुमच्या स्वतःच्या शब्दांत.',
  offlineReady: 'ऑफलाइन तयार',
  step: 'पायरी',
  of: 'पैकी',
  yourTrade: 'तुमचा व्यवसाय',
  experience: 'अनुभव',
  evidence: 'पुरावा',
  result: 'निकाल',
  whatWork: 'तुम्ही कोणते काम करता?',
  tapPicture: 'तुमच्या कामाशी जुळणाऱ्या चित्रावर टॅप करा.',
  tellAboutWork: 'तुमच्या कामाबद्दल सांगा',
  pressAndSpeak: 'बटण दाबून बोला',
  speakAnyLang: 'कोणत्याही भाषेत बोला',
  listening: '🔴 ऐकत आहे… आता बोला',
  howManyYears: 'तुम्ही हे काम किती वर्षांपासून करत आहात?',
  whatTools: 'तुम्ही कोणती साधने वापरता?',
  whatKindWork: 'तुम्ही सहसा कोणत्या प्रकारचे काम करता?',
  whereWork: 'तुम्ही कुठे काम करता?',
  showYourWork: 'तुमचे काम दाखवा',
  evidenceSub: 'फोटो आणि व्हिडिओंमुळे परीक्षकाला तुमचे कौशल्य समजण्यास मदत होते.',
  takePhoto: 'फोटो काढा',
  takePhotoSub: 'तुमच्या कामाचा',
  recordVideo: 'व्हिडिओ बनवा',
  recordVideoSub: 'एक लहान क्लिप',
  uploadPaper: 'कागदपत्र अपलोड करा',
  uploadPaperSub: 'प्रमाणपत्र किंवा अनुभव पत्र',
  dragFiles: 'किंवा फाइल्स येथे ओढा',
  fileTypes: 'JPG, PNG, MP4, PDF — कमाल ५० MB',
  offlineUpload: 'तुम्ही हे इंटरनेटशिवाय करू शकता.',
  offlineUploadSub: 'फाइल्स फोनमध्ये साठवल्या जातील आणि ऑनलाइन आल्यावर अपलोड होतील.',
  suggestedMatch: 'सुचवलेली जुळणी',
  match: 'जुळणी',
  humanReview: 'मानवी मूल्यांकनकर्ता तपासून निर्णय घेईल.',
  humanReviewSub: 'ही संगणकाची केवळ एक प्राथमिक सूचना आहे. प्रमाणित परीक्षक अंतिम निर्णय घेतील.',
  back: 'मागे',
  next: 'पुढे',
  submit: 'सादर करा',
  orTypeBelow: 'बटण दाबून बोला किंवा खाली लिहा.',
  electrician: 'इलेक्ट्रिशियन',
  plumber: 'प्लंबर',
  welder: 'वेल्डर',
  carpenter: 'सुतार',
  mason: 'गवंडी',
  tailor: 'शिंपी',
  cook: 'आचारी',
  driver: 'चालक',
  other: 'इतर',
  performBasicWork: 'मूलभूत तांत्रिक काम करणे',
  readDrawings: 'साधे नकाशे वाचणे',
  followSafety: 'कामाच्या ठिकाणी सुरक्षेचे नियम पाळणे',
  footerDesc: 'स्मार्ट इंडिया हॅकाथॉन अंतर्गत पूर्व शिक्षणाची मान्यता (RPL) साठी एआय-आधारित कौशल्य मूल्यांकन साधन.',
  sponsoredBy: 'प्रायोजक',
  msdeFullName: 'कौशल्य विकास आणि उद्योजकता मंत्रालय (MSDE)',
  ncvetFullName: 'राष्ट्रीय व्यावसायिक शिक्षण आणि प्रशिक्षण परिषद (NCVET)',
  project: 'प्रकल्प',
  problemId: 'समस्या आयडी: SIH26242',
  themeSmartEdu: 'थीम: स्मार्ट शिक्षण',
  categorySoftware: 'श्रेणी: सॉफ्टवेअर',
  footerCopyright: '© २०२६ आरपीएल एआय मूल्यांकन साधन — भारताच्या कुशल कामगारांसाठी निर्मित'
};

export const gu = {
  navHome: 'હોમ',
  navSelfDeclaration: 'સ્વ-ઘોષણા',
  navCandidate: 'ઉમેદવાર',
  navAssessor: 'મૂલ્યાંકનકાર',
  govtInitiative: 'ભારત સરકારની પહેલ',
  ministryName: 'કૌશલ્ય વિકાસ અને ઉદ્યોગસાહસિકતા મંત્રાલય',
  rplAiAssessment: 'RPL AI કૌશલ્ય મૂલ્યાંકન',
  heroTitle: 'તમારા કૌશલ્યનું પ્રમાણીકરણ મેળવો',
  heroSub: 'કામ દ્વારા શીખેલા કારીગરો માટે. કોઈ ઔપચારિક શિક્ષણની જરૂર નથી.',
  portfolioHeroH1_1: 'હુનર પારખો.',
  portfolioHeroH1_2: 'અનુભવને',
  portfolioHeroH1_3: ' પ્રમાણિત કરો.',
  portfolioHeroH1_4: 'RPL નો વિસ્તાર.',
  startAssessment: 'મૂલ્યાંકન શરૂ કરો',
  assessorLogin: 'મૂલ્યાંકનકાર લોગિન',
  makeItClear: '૦૧ — સ્પષ્ટ અને સચોટ',
  buildShapeShip: 'શીખો / ઘડો / આગળ વધો',
  tickerAiAssisted: 'AI-સંચાલિત RPL',
  tickerNsqf: 'NSQF આધારિત',
  tickerHumanLoop: 'માનવીય ચકાસણી સાથે',
  tickerRegional: '૨૨ ભારતીય ભાષાઓ',
  tickerOffline: 'ઓફલાઇન-પ્રથમ સિંક',
  tickerMinistry: 'કૌશલ્ય વિકાસ મંત્રાલય',
  ourWork: 'અમારું કાર્ય',
  work1Title: 'સરળ અનુભવ મેપિંગ',
  work1Desc: 'કારીગરો માટે પોતાની માતૃભાષામાં કુશળતા જણાવવાનું સંવાદાત્મક માધ્યમ.',
  work2Title: 'વિડિયો અને ફોટો મૂલ્યાંકન',
  work2Desc: 'પ્રાયોગિક કામગીરીની ચકાસણી માટે વિઝ્યુઅલ પુરાવા સંગ્રહ.',
  work3Title: 'પ્રમાણિત સ્કોરિંગ',
  work3Desc: 'મૂલ્યાંકનકારો માટે NSQF ધોરણો અનુસાર સચોટ ગુણાંકન.',
  work4Title: 'ઓછા ઇન્ટરનેટમાં પણ સક્ષમ',
  work4Desc: 'ઇન્ટરનેટ ન હોય તો પણ ડેટા ડિવાઇસમાં સુરક્ષિત રહે છે.',
  tagSelfDecl: 'સ્વ-ઘોષણા',
  tagAiAssist: 'AI સહાય',
  tagPractical: 'પ્રાયોગિક સાધન',
  tagMedia: 'મીડિયા પુરાવો',
  tagAssessor: 'પરીક્ષક સહયોગ',
  tagNsqf: 'NSQF ધોરણો',
  tagOffline: 'ઓફલાઇન સક્ષમ',
  tagSync: 'ઓટો સિંક',
  feat1Title: 'તમારો અનુભવ બોલીને કહો',
  feat1Desc: 'તમારી પોતાની પ્રાદેશિક ભાષામાં અવાજ દ્વારા ઇનપુટ આપો',
  feat2Title: 'તમારું કામ બતાવો',
  feat2Desc: 'ફોટા, વીડિયો અને કામના પુરાવા સરળતાથી અપલોડ કરો',
  feat3Title: 'NSQF સાથે સુમેળ',
  feat3Desc: 'AI તમારા વ્યવહારુ કૌશલ્યને રાષ્ટ્રીય ધોરણો સાથે જોડે છે',
  feat4Title: 'માનવ પરીક્ષકનો નિર્ણય',
  feat4Desc: 'AI સૂચનો આપે છે, પ્રમાણિત નિષ્ણાત આખરી નિર્ણય લે છે',
  howItWorks: 'આ કેવી રીતે કાર્ય કરે છે',
  howItWorksSub: 'ત્રણ સરળ પગલાં. કોઈ જટિલ પરીક્ષા કે ફોર્મ નહીં.',
  step1Title: 'તમારા વિશે જણાવો',
  step1Desc: 'તમારો વ્યવસાય પસંદ કરો. તમારા અનુભવ વિશે કોઈપણ ભાષામાં બોલો.',
  step2Title: 'તમારું કામ બતાવો',
  step2Desc: 'તમે બનાવેલી વસ્તુઓના ફોટા પાડો અથવા નાનો વીડિયો બનાવો.',
  step3Title: 'પ્રમાણપત્ર મેળવો',
  step3Desc: 'AI કૌશલ્ય મેળવે છે અને પ્રમાણિત નિરીક્ષક રાષ્ટ્રીય પ્રમાણપત્ર આપે છે.',
  ctaBannerTitlePortfolio: 'ભારતના કુશળ કારીગરોને આપો સત્તાવાર માન્યતા.',
  ctaBannerTitleGovt: 'ભારતના શ્રમિકો પાસે કુશળતા છે. ચાલો તેને પ્રમાણિત કરીએ.',
  ctaBannerSub: 'અસંગઠિત ક્ષેત્રના કામદારો માટે વિશેષ રૂપે નિર્મિત.',
  beginSelfDeclaration: 'સ્વ-ઘોષણા શરૂ કરો',
  welcomeCandidate: 'નમસ્તે, રમેશ 👋',
  candidateId: 'ઉમેદવાર આઈડી: RPL-2024-8842',
  allSynced: 'બધો ડેટા સિંક થયો',
  newDeclaration: 'નવી ઘોષણા',
  newDeclarationSub: 'નવું કૌશલ્ય મેપિંગ શરૂ કરો',
  uploadEvidence: 'પુરાવા અપલોડ કરો',
  uploadEvidenceSub: 'ફોટો અથવા વીડિયો ઉમેરો',
  viewCertificate: 'પ્રમાણપત્ર જુઓ',
  viewCertificateSub: 'તમારું NSQF પ્રમાણપત્ર ડાઉનલોડ કરો',
  yourApplications: 'તમારી અરજીઓ',
  underReview: 'સમીક્ષા હેઠળ',
  needMoreInfo: 'વધુ માહિતીની જરૂર છે',
  certified: 'પ્રમાણિત',
  nsqfLevel: 'NSQF સ્તર',
  submittedAgo: '૨ દિવસ પહેલાં મોકલ્યું',
  assessorReviewing: 'પરીક્ષક તમારા પુરાવા તપાસી રહ્યા છે…',
  needClearerVideo: 'વાયરિંગ સુરક્ષા તપાસનો સ્પષ્ટ વીડિયો મોકલો.',
  details: 'વિગતો',
  uploadNow: 'હમણાં અપલોડ કરો',
  downloadPdf: 'PDF ડાઉનલોડ કરો',
  worksWithoutInternet: 'ઇન્ટરનેટ વિના પણ કામ કરે છે',
  worksWithoutInternetSub: 'ઇન્ટરનેટ ન હોય ત્યારે પણ અરજી જુઓ અને બનાવો. ઓનલાઇન થતાં જ સિંક થશે.',
  pendingReview: 'સમીક્ષા માટે બાકી',
  searchCandidate: 'ઉમેદવાર શોધો…',
  aiDisclaimer: 'AI માત્ર સલાહ આપે છે. આખરી પ્રમાણીકરણ નિર્ણય માનવ પરીક્ષકનો જ રહે છે.',
  photos: 'ફોટા',
  video: 'વીડિયો',
  aiSuggestion: 'AI સૂચન',
  competent: 'સક્ષમ (યોગ્ય)',
  needsReview: 'પુનરાવલોકન જરૂરી',
  lowMatch: 'ઓછો મેળ',
  yes: 'હા',
  partial: 'આંશિક',
  no: 'ના',
  saveDraft: 'ડ્રાફ્ટ સાચવો',
  notYetCompetent: 'હજુ સક્ષમ નથી',
  requestEvidence: 'વધુ પુરાવા માંગો',
  recommendCert: 'પ્રમાણપત્રની ભલામણ કરો',
  selfDeclaration: 'સ્વ-ઘોષણા',
  selfDeclarationSub: 'તમારી આવડત વિશે કહો — તમારા પોતાના શબ્દોમાં.',
  offlineReady: 'ઓફલાઇન તૈયાર',
  step: 'પગલું',
  of: 'માંથી',
  yourTrade: 'તમારો વ્યવસાય',
  experience: 'અનુભવ',
  evidence: 'પુરાવો',
  result: 'પરિણામ',
  whatWork: 'તમે કયું કામ કરો છો?',
  tapPicture: 'તમારા કામ સાથે મેળ ખાતા ચિત્ર પર ટેપ કરો.',
  tellAboutWork: 'તમારા કામ વિશે જણાવો',
  pressAndSpeak: 'બટન દબાવો અને બોલો',
  speakAnyLang: 'કોઈપણ ભાષામાં બોલો',
  listening: '🔴 સાંભળી રહ્યા છીએ… હવે બોલો',
  howManyYears: 'તમે કેટલા વર્ષથી આ કામ કરી રહ્યા છો?',
  whatTools: 'તમે કયા સાધનો વાપરો છો?',
  whatKindWork: 'તમે સામાન્ય રીતે કેવા પ્રકારનું કામ કરો છો?',
  whereWork: 'તમે ક્યાં કામ કરો છો?',
  showYourWork: 'તમારું કામ બતાવો',
  evidenceSub: 'ફોટા અને વીડિયોથી પરીક્ષકને તમારું કૌશલ્ય જોવામાં મદદ મળે છે.',
  takePhoto: 'ફોટો પાડો',
  takePhotoSub: 'તમારા કામનો',
  recordVideo: 'વીડિયો બનાવો',
  recordVideoSub: 'એક નાની ક્લિપ',
  uploadPaper: 'કાગળ અપલોડ કરો',
  uploadPaperSub: 'પ્રમાણપત્ર કે પત્ર',
  dragFiles: 'અથવા ફાઇલો અહીં ખેંચો',
  fileTypes: 'JPG, PNG, MP4, PDF — 50 MB સુધી',
  offlineUpload: 'તમે આ ઇન્ટરનેટ વિના પણ કરી શકો છો.',
  offlineUploadSub: 'ફાઇલો તમારા ફોનમાં સુરક્ષિત રહેશે અને નેટ આવતાં અપલોડ થશે.',
  suggestedMatch: 'સૂચવેલ મેચ',
  match: 'મેચ',
  humanReview: 'માનવ મૂલ્યાંકનકાર સમીક્ષા કરીને નિર્ણય લેશે.',
  humanReviewSub: 'આ કમ્પ્યુટરનું પ્રાથમિક સૂચન છે. સર્ટિફાઇડ પરીક્ષક અંતિમ નિર્ણય કરશે.',
  back: 'પાછા',
  next: 'આગળ',
  submit: 'જમા કરો',
  orTypeBelow: 'બટન દબાવીને બોલો અથવા નીચે લખો.',
  electrician: 'ઇલેક્ટ્રિશિયન',
  plumber: 'પ્લમ્બર',
  welder: 'વેલ્ડર',
  carpenter: 'સુથાર',
  mason: 'કડિયો',
  tailor: 'દરજી',
  cook: 'રસોઇયો',
  driver: 'ડ્રાઇવર',
  other: 'અન્ય',
  performBasicWork: 'મૂળભૂત કામગીરી કરવી',
  readDrawings: 'સરળ નકશા સમજવા',
  followSafety: 'કાર્યસ્થળ સુરક્ષા નિયમોનું પાલન',
  footerDesc: 'સ્માર્ટ ઇન્ડિયા હેકાથોન અંતર્ગત પૂર્વ શિક્ષણની માન્યતા (RPL) માટે AI-આધારિત કૌશલ્ય મૂલ્યાંકન પદ્ધતિ.',
  sponsoredBy: 'પ્રાયોજક',
  msdeFullName: 'કૌશલ્ય વિકાસ અને ઉદ્યોગસાહસિકતા મંત્રાલય (MSDE)',
  ncvetFullName: 'રાષ્ટ્રીય વ્યવસાયિક શિક્ષણ અને તાલીમ પરિષદ (NCVET)',
  project: 'પ્રોજેક્ટ',
  problemId: 'સમસ્યા આઈડી: SIH26242',
  themeSmartEdu: 'થીમ: સ્માર્ટ શિક્ષણ',
  categorySoftware: 'શ્રેણી: સોફ્ટવેર',
  footerCopyright: '© ૨૦૨૬ RPL AI મૂલ્યાંકન સાધન — ભારતના કુશળ શ્રમિકો માટે સમર્પિત'
};

export const pa = {
  navHome: 'ਮੁੱਖ ਸਫ਼ਾ',
  navSelfDeclaration: 'ਸਵੈ-ਘੋਸ਼ਣਾ',
  navCandidate: 'ਉਮੀਦਵਾਰ',
  navAssessor: 'ਮੁਲਾਂਕਣਕਰਤਾ',
  govtInitiative: 'ਭਾਰਤ ਸਰਕਾਰ ਦਾ ਉਪਰਾਲਾ',
  ministryName: 'ਹੁਨਰ ਵਿਕਾਸ ਅਤੇ ਉੱਦਮਤਾ ਮੰਤਰਾਲਾ',
  rplAiAssessment: 'ਆਰਪੀਐਲ ਏਆਈ ਹੁਨਰ ਮੁਲਾਂਕਣ',
  heroTitle: 'ਆਪਣੇ ਹੁਨਰ ਦਾ ਸਰਟੀਫਿਕੇਟ ਪ੍ਰਾਪਤ ਕਰੋ',
  heroSub: 'ਕੰਮ ਕਰਦੇ ਹੋਏ ਸਿੱਖਣ ਵਾਲੇ ਕਾਮਿਆਂ ਲਈ। ਰਸਮੀ ਸਿੱਖਿਆ ਦੀ ਕੋਈ ਲੋੜ ਨਹੀਂ।',
  portfolioHeroH1_1: 'ਹੁਨਰ ਪਰਖੋ।',
  portfolioHeroH1_2: 'ਤਜਰਬੇ ਨੂੰ',
  portfolioHeroH1_3: ' ਪ੍ਰਮਾਣਿਤ ਕਰੋ।',
  portfolioHeroH1_4: 'RPL ਦਾ ਪਸਾਰ।',
  startAssessment: 'ਮੁਲਾਂਕਣ ਸ਼ੁਰੂ ਕਰੋ',
  assessorLogin: 'ਮੁਲਾਂਕਣਕਰਤਾ ਲੌਗਇਨ',
  makeItClear: '੦੧ — ਸਪਸ਼ਟ ਅਤੇ ਪਾਰਦਰਸ਼ੀ',
  buildShapeShip: 'ਸਿੱਖੋ / ਘੜੋ / ਵਧੋ',
  tickerAiAssisted: 'AI-ਸਹਾਇਤਾ ਪ੍ਰਾਪਤ RPL',
  tickerNsqf: 'NSQF ਅਨੁਕੂਲ',
  tickerHumanLoop: 'ਮਨੁੱਖੀ ਨਿਗਰਾਨੀ ਹੇਠ',
  tickerRegional: '੨੨ ਭਾਰਤੀ ਭਾਸ਼ਾਵਾਂ',
  tickerOffline: 'ਔਫਲਾਈਨ-ਪਹਿਲ ਸਿੰਕ',
  tickerMinistry: 'ਹੁਨਰ ਵਿਕਾਸ ਮੰਤਰਾਲਾ',
  ourWork: 'ਸਾਡਾ ਕੰਮ',
  work1Title: 'ਸੌਖਾ ਤਜਰਬਾ ਮੈਪਿੰਗ',
  work1Desc: 'ਕਾਮਿਆਂ ਲਈ ਆਪਣੀ ਮਾਤ-ਭਾਸ਼ਾ ਵਿੱਚ ਹੁਨਰ ਦੱਸਣ ਲਈ ਗੱਲਬਾਤ ਵਾਲਾ ਇੰਟਰਫੇਸ।',
  work2Title: 'ਵੀਡੀਓ ਅਤੇ ਤਸਵੀਰ ਮੁਲਾਂਕਣ',
  work2Desc: 'ਵਿਹਾਰਕ ਕੰਮ ਦੇ ਮੁਲਾਂਕਣ ਲਈ ਵਿਜ਼ੂਅਲ ਸਬੂਤ ਇਕੱਠੇ ਕਰਨਾ।',
  work3Title: 'ਮਿਆਰੀ ਸਕੋਰਿੰਗ',
  work3Desc: 'ਮੁਲਾਂਕਣਕਰਤਾਵਾਂ ਲਈ NSQF ਮਾਪਦੰਡਾਂ ਅਨੁਸਾਰ ਸਹੀ ਸਕੋਰਿੰਗ।',
  work4Title: 'ਘੱਟ ਇੰਟਰਨੈੱਟ ਵਿੱਚ ਵੀ ਸਮਰੱਥ',
  work4Desc: 'ਇੰਟਰਨੈੱਟ ਨਾ ਹੋਣ ਤੇ ਵੀ ਡਾਟਾ ਫੋਨ ਵਿੱਚ ਸੁਰੱਖਿਅਤ ਰਹਿੰਦਾ ਹੈ।',
  tagSelfDecl: 'ਸਵੈ-ਘੋਸ਼ਣਾ',
  tagAiAssist: 'AI ਸਹਾਇਤਾ',
  tagPractical: 'ਵਿਹਾਰਕ ਸਾਧਨ',
  tagMedia: 'ਮੀਡੀਆ ਸਬੂਤ',
  tagAssessor: 'ਪ੍ਰੀਖਿਅਕ ਸਹਿਯੋਗ',
  tagNsqf: 'NSQF ਮਿਆਰ',
  tagOffline: 'ਔਫਲਾਈਨ ਸਮਰੱਥ',
  tagSync: 'ਆਟੋ ਸਿੰਕ',
  feat1Title: 'ਆਪਣਾ ਤਜਰਬਾ ਬੋਲ ਕੇ ਦੱਸੋ',
  feat1Desc: 'ਆਪਣੀ ਖੇਤਰੀ ਭਾਸ਼ਾ ਵਿੱਚ ਬੋਲ ਕੇ ਜਾਣਕਾਰੀ ਦਿਓ',
  feat2Title: 'ਆਪਣਾ ਕੰਮ ਦਿਖਾਓ',
  feat2Desc: 'ਫੋਟੋਆਂ, ਵੀਡੀਓ ਅਤੇ ਕੰਮ ਦੇ ਸਬੂਤ ਆਸਾਨੀ ਨਾਲ ਅੱਪਲੋਡ ਕਰੋ',
  feat3Title: 'NSQF ਨਾਲ ਮੇਲ',
  feat3Desc: 'AI ਤੁਹਾਡੇ ਵਿਹਾਰਕ ਹੁਨਰ ਨੂੰ ਰਾਸ਼ਟਰੀ ਮਿਆਰਾਂ ਨਾਲ ਜੋੜਦਾ ਹੈ',
  feat4Title: 'ਮਨੁੱਖੀ ਮੁਲਾਂਕਣਕਰਤਾ ਦਾ ਫੈਸਲਾ',
  feat4Desc: 'AI ਸਕੋਰ ਸੁਝਾਉਂਦਾ ਹੈ, ਮਾਹਰ ਪ੍ਰੀਖਿਅਕ ਅੰਤਿਮ ਫੈਸਲਾ ਲੈਂਦੇ ਹਨ',
  howItWorks: 'ਇਹ ਕਿਵੇਂ ਕੰਮ ਕਰਦਾ ਹੈ',
  howItWorksSub: 'ਤਿੰਨ ਆਸਾਨ ਕਦਮ। ਕੋਈ ਔਖੀ ਪ੍ਰੀਖਿਆ ਜਾਂ ਲੰਮੇ ਫਾਰਮ ਨਹੀਂ।',
  step1Title: 'ਆਪਣੇ ਬਾਰੇ ਦੱਸੋ',
  step1Desc: 'ਆਪਣਾ ਕਿੱਤਾ ਚੁਣੋ। ਕਿਸੇ ਵੀ ਭਾਸ਼ਾ ਵਿੱਚ ਆਪਣੇ ਕੰਮ ਦੇ ਤਜਰਬੇ ਬਾਰੇ ਬੋਲੋ।',
  step2Title: 'ਆਪਣਾ ਕੰਮ ਦਿਖਾਓ',
  step2Desc: 'ਆਪਣੇ ਬਣਾਏ ਸਾਮਾਨ ਦੀਆਂ ਫੋਟੋਆਂ ਖਿੱਚੋ ਜਾਂ ਛੋਟਾ ਵੀਡੀਓ ਰਿਕਾਰਡ ਕਰੋ।',
  step3Title: 'ਸਰਟੀਫਿਕੇਟ ਪ੍ਰਾਪਤ ਕਰੋ',
  step3Desc: 'AI ਹੁਨਰ ਮਿਲਾਉਂਦਾ ਹੈ ਅਤੇ ਸਰਟੀਫਾਈਡ ਪ੍ਰੀਖਿਅਕ ਰਾਸ਼ਟਰੀ ਸਰਟੀਫਿਕੇਟ ਜਾਰੀ ਕਰਦਾ ਹੈ।',
  ctaBannerTitlePortfolio: 'ਭਾਰਤ ਦੇ ਹੁਨਰਮੰਦ ਹੱਥਾਂ ਨੂੰ ਦਿਓ ਅਧਿਕਾਰਤ ਮਾਨਤਾ।',
  ctaBannerTitleGovt: 'ਭਾਰਤ ਦੇ ਕਾਮਿਆਂ ਵਿੱਚ ਹੁਨਰ ਹੈ। ਆਓ ਇਸਨੂੰ ਪ੍ਰਮਾਣਿਤ ਕਰੀਏ।',
  ctaBannerSub: 'ਗੈਰ-ਰਸਮੀ ਖੇਤਰ ਦੇ ਕਾਮਿਆਂ ਲਈ ਵਿਸ਼ੇਸ਼ ਤੌਰ ਤੇ ਤਿਆਰ ਕੀਤਾ ਗਿਆ।',
  beginSelfDeclaration: 'ਸਵੈ-ਘੋਸ਼ਣਾ ਸ਼ੁਰੂ ਕਰੋ',
  welcomeCandidate: 'ਜੀ ਆਇਆਂ ਨੂੰ, ਰਮੇਸ਼ 👋',
  candidateId: 'ਉਮੀਦਵਾਰ ਆਈਡੀ: RPL-2024-8842',
  allSynced: 'ਸਭ ਸਿੰਕ ਹੋ ਗਿਆ',
  newDeclaration: 'ਨਵੀਂ ਘੋਸ਼ਣਾ',
  newDeclarationSub: 'ਨਵਾਂ ਹੁਨਰ ਮੈਪਿੰਗ ਸ਼ੁਰੂ ਕਰੋ',
  uploadEvidence: 'ਸਬੂਤ ਅੱਪਲੋਡ ਕਰੋ',
  uploadEvidenceSub: 'ਫੋਟੋ ਜਾਂ ਵੀਡੀਓ ਸ਼ਾਮਲ ਕਰੋ',
  viewCertificate: 'ਸਰਟੀਫਿਕੇਟ ਦੇਖੋ',
  viewCertificateSub: 'ਆਪਣਾ NSQF ਸਰਟੀਫਿਕੇਟ ਡਾਊਨਲੋਡ ਕਰੋ',
  yourApplications: 'ਤੁਹਾਡੀਆਂ ਅਰਜ਼ੀਆਂ',
  underReview: 'ਜਾਂਚ ਅਧੀਨ',
  needMoreInfo: 'ਹੋਰ ਜਾਣਕਾਰੀ ਦੀ ਲੋੜ ਹੈ',
  certified: 'ਪ੍ਰਮਾਣਿਤ',
  nsqfLevel: 'NSQF ਪੱਧਰ',
  submittedAgo: '੨ ਦਿਨ ਪਹਿਲਾਂ ਭੇਜਿਆ',
  assessorReviewing: 'ਮੁਲਾਂਕਣਕਰਤਾ ਤੁਹਾਡੇ ਸਬੂਤਾਂ ਦੀ ਜਾਂਚ ਕਰ ਰਿਹਾ ਹੈ…',
  needClearerVideo: 'ਵਾਇਰਿੰਗ ਸੁਰੱਖਿਆ ਜਾਂਚ ਦੀ ਹੋਰ ਸਾਫ਼ ਵੀਡੀਓ ਚਾਹੀਦੀ ਹੈ।',
  details: 'ਵੇਰਵੇ',
  uploadNow: 'ਹੁਣੇ ਅੱਪਲੋਡ ਕਰੋ',
  downloadPdf: 'PDF ਡਾਊਨਲੋਡ ਕਰੋ',
  worksWithoutInternet: 'ਇੰਟਰਨੈੱਟ ਤੋਂ ਬਿਨਾਂ ਵੀ ਚੱਲਦਾ ਹੈ',
  worksWithoutInternetSub: 'ਬਿਨਾਂ ਇੰਟਰਨੈੱਟ ਦੇ ਵੀ ਅਰਜ਼ੀਆਂ ਦੇਖੋ ਅਤੇ ਭਰੋ। ਆਨਲਾਈਨ ਹੋਣ ਤੇ ਆਪੇ ਸਿੰਕ ਹੋ ਜਾਵੇਗਾ।',
  pendingReview: 'ਜਾਂਚ ਲਈ ਬਕਾਇਆ',
  searchCandidate: 'ਉਮੀਦਵਾਰ ਖੋਜੋ…',
  aiDisclaimer: 'AI ਸਿਰਫ਼ ਸੁਝਾਅ ਦਿੰਦਾ ਹੈ। ਅੰਤਿਮ ਫੈਸਲਾ ਮਨੁੱਖੀ ਪ੍ਰੀਖਿਅਕ ਹੀ ਕਰਦਾ ਹੈ।',
  photos: 'ਤਸਵੀਰਾਂ',
  video: 'ਵੀਡੀਓ',
  aiSuggestion: 'AI ਸੁਝਾਅ',
  competent: 'ਯੋਗ (ਸਮਰੱਥ)',
  needsReview: 'ਮੁੜ ਵਿਚਾਰ ਦੀ ਲੋੜ',
  lowMatch: 'ਘੱਟ ਮੇਲ',
  yes: 'ਹਾਂ',
  partial: 'ਅੰਸ਼ਕ',
  no: 'ਨਹੀਂ',
  saveDraft: 'ਡਰਾਫਟ ਸੇਵ ਕਰੋ',
  notYetCompetent: 'ਅਜੇ ਯੋਗ ਨਹੀਂ',
  requestEvidence: 'ਹੋਰ ਸਬੂਤ ਮੰਗੋ',
  recommendCert: 'ਸਰਟੀਫਿਕੇਟ ਦੀ ਸਿਫ਼ਾਰਸ਼ ਕਰੋ',
  selfDeclaration: 'ਸਵੈ-ਘੋਸ਼ਣਾ',
  selfDeclarationSub: 'ਆਪਣੇ ਹੁਨਰ ਬਾਰੇ ਦੱਸੋ — ਆਪਣੀ ਬੋਲੀ ਵਿੱਚ।',
  offlineReady: 'ਔਫਲਾਈਨ ਤਿਆਰ',
  step: 'ਕਦਮ',
  of: 'ਦਾ',
  yourTrade: 'ਤੁਹਾਡਾ ਕਿੱਤਾ',
  experience: 'ਤਜਰਬਾ',
  evidence: 'ਸਬੂਤ',
  result: 'ਨਤੀਜਾ',
  whatWork: 'ਤੁਸੀਂ ਕੀ ਕੰਮ ਕਰਦੇ ਹੋ?',
  tapPicture: 'ਆਪਣੇ ਕੰਮ ਨਾਲ ਮਿਲਦੀ ਤਸਵੀਰ ਤੇ ਟੈਪ ਕਰੋ।',
  tellAboutWork: 'ਆਪਣੇ ਕੰਮ ਬਾਰੇ ਦੱਸੋ',
  pressAndSpeak: 'ਦਬਾਓ ਅਤੇ ਬੋਲੋ',
  speakAnyLang: 'ਕਿਸੇ ਵੀ ਭਾਸ਼ਾ ਵਿੱਚ ਬੋਲੋ',
  listening: '🔴 ਸੁਣ ਰਹੇ ਹਾਂ… ਹੁਣ ਬੋਲੋ',
  howManyYears: 'ਤੁਸੀਂ ਇਹ ਕੰਮ ਕਿੰਨੇ ਸਾਲਾਂ ਤੋਂ ਕਰ ਰਹੇ ਹੋ?',
  whatTools: 'ਤੁਸੀਂ ਕਿਹੜੇ ਸੰਦ ਵਰਤਦੇ ਹੋ?',
  whatKindWork: 'ਤੁਸੀਂ ਆਮ ਤੌਰ ਤੇ ਕਿਸ ਤਰ੍ਹਾਂ ਦਾ ਕੰਮ ਕਰਦੇ ਹੋ?',
  whereWork: 'ਤੁਸੀਂ ਕਿੱਥੇ ਕੰਮ ਕਰਦੇ ਹੋ?',
  showYourWork: 'ਆਪਣਾ ਕੰਮ ਦਿਖਾਓ',
  evidenceSub: 'ਫੋਟੋਆਂ ਅਤੇ ਵੀਡੀਓ ਨਾਲ ਪ੍ਰੀਖਿਅਕ ਤੁਹਾਡਾ ਹੁਨਰ ਚੰਗੀ ਤਰ੍ਹਾਂ ਦੇਖ ਸਕਦਾ ਹੈ।',
  takePhoto: 'ਫੋਟੋ ਖਿੱਚੋ',
  takePhotoSub: 'ਆਪਣੇ ਕੰਮ ਦੀ',
  recordVideo: 'ਵੀਡੀਓ ਬਣਾਓ',
  recordVideoSub: 'ਇੱਕ ਛੋਟੀ ਕਲਿੱਪ',
  uploadPaper: 'ਦਸਤਾਵੇਜ਼ ਅੱਪਲੋਡ ਕਰੋ',
  uploadPaperSub: 'ਸਰਟੀਫਿਕੇਟ ਜਾਂ ਚਿੱਠੀ',
  dragFiles: 'ਜਾਂ ਫਾਈਲਾਂ ਇੱਥੇ ਖਿੱਚੋ',
  fileTypes: 'JPG, PNG, MP4, PDF — 50 MB ਤੱਕ',
  offlineUpload: 'ਤੁਸੀਂ ਇਹ ਬਿਨਾਂ ਇੰਟਰਨੈੱਟ ਦੇ ਵੀ ਕਰ ਸਕਦੇ ਹੋ।',
  offlineUploadSub: 'ਫਾਈਲਾਂ ਫੋਨ ਵਿੱਚ ਸੁਰੱਖਿਅਤ ਰਹਿਣਗੀਆਂ ਅਤੇ ਆਨਲਾਈਨ ਹੋਣ ਤੇ ਅੱਪਲੋਡ ਹੋਣਗੀਆਂ।',
  suggestedMatch: 'ਸੁਝਾਇਆ ਗਿਆ ਮੇਲ',
  match: 'ਮੇਲ',
  humanReview: 'ਮਨੁੱਖੀ ਮੁਲਾਂਕਣਕਰਤਾ ਜਾਂਚ ਕਰਕੇ ਫੈਸਲਾ ਕਰੇਗਾ।',
  humanReviewSub: 'ਇਹ ਕੰਪਿਊਟਰ ਦਾ ਸੁਝਾਅ ਹੈ। ਪ੍ਰਮਾਣਿਤ ਪ੍ਰੀਖਿਅਕ ਸਮੀਖਿਆ ਕਰਕੇ ਅੰਤਿਮ ਫੈਸਲਾ ਲੈਣਗੇ।',
  back: 'ਪਿੱਛੇ',
  next: 'ਅੱਗੇ',
  submit: 'ਜਮ੍ਹਾਂ ਕਰੋ',
  orTypeBelow: 'ਬਟਨ ਦਬਾ ਕੇ ਬੋਲੋ ਜਾਂ ਹੇਠਾਂ ਲਿਖੋ।',
  electrician: 'ਇਲੈਕਟ੍ਰੀਸ਼ੀਅਨ',
  plumber: 'ਪਲੰਬਰ',
  welder: 'ਵੈਲਡਰ',
  carpenter: 'ਤਰਖਾਣ',
  mason: 'ਰਾਜਮਿਸਤਰੀ',
  tailor: 'ਦਰਜ਼ੀ',
  cook: 'ਰਸੋਈਆ',
  driver: 'ਡਰਾਈਵਰ',
  other: 'ਹੋਰ',
  performBasicWork: 'ਮੁੱਢਲਾ ਕੰਮ ਕਰਨਾ',
  readDrawings: 'ਸਧਾਰਨ ਨਕਸ਼ੇ ਪੜ੍ਹਨਾ',
  followSafety: 'ਵਰਕਸ਼ਾਪ ਸੁਰੱਖਿਆ ਨਿਯਮਾਂ ਦੀ ਪਾਲਣਾ',
  footerDesc: 'ਸਮਾਰਟ ਇੰਡੀਆ ਹੈਕਾਥੌਨ ਤਹਿਤ ਪੂਰਵ ਸਿੱਖਿਆ ਦੀ ਮਾਨਤਾ (RPL) ਲਈ AI-ਅਧਾਰਿਤ ਹੁਨਰ ਮੁਲਾਂਕਣ ਪ੍ਰਣਾਲੀ।',
  sponsoredBy: 'ਸਪਾਂਸਰ',
  msdeFullName: 'ਹੁਨਰ ਵਿਕਾਸ ਅਤੇ ਉੱਦਮਤਾ ਮੰਤਰਾਲਾ (MSDE)',
  ncvetFullName: 'ਨੈਸ਼ਨਲ ਕੌਂਸਲ ਫਾਰ ਵੋਕੇਸ਼ਨਲ ਐਜੂਕੇਸ਼ਨ ਐਂਡ ਟਰੇਨਿੰਗ (NCVET)',
  project: 'ਪ੍ਰੋਜੈਕਟ',
  problemId: 'ਸਮੱਸਿਆ ਆਈਡੀ: SIH26242',
  themeSmartEdu: 'ਥੀਮ: ਸਮਾਰਟ ਸਿੱਖਿਆ',
  categorySoftware: 'ਸ਼੍ਰੇਣੀ: ਸਾਫਟਵੇਅਰ',
  footerCopyright: '© ੨੦੨੬ RPL AI ਮੁਲਾਂਕਣ ਟੂਲ — ਭਾਰਤ ਦੇ ਹੁਨਰਮੰਦ ਕਾਮਿਆਂ ਲਈ ਤਿਆਰ ਕੀਤਾ ਗਿਆ'
};
