export const sa = {
  navHome: 'गृहम्',
  navSelfDeclaration: 'स्वघोषणा',
  navCandidate: 'प्रार्थी',
  navAssessor: 'परीक्षकः',
  govtInitiative: 'भारतसर्वकारस्य उपक्रमः',
  ministryName: 'कौशलविकास-उद्यमितामन्त्रालयः',
  rplAiAssessment: 'आरपीएल एआई कौशलमूल्याङ्कनम्',
  heroTitle: 'स्वकीयकौशलस्य प्रमाणीकरणं प्राप्नुवन्तु',
  heroSub: 'कर्मणा शिक्षितश्रमिकेभ्यः। औपचारिकशिक्षायाः आवश्यकता नास्ति।',
  portfolioHeroH1_1: 'कौशलं परीक्ष्यताम्।',
  portfolioHeroH1_2: 'अनुभवस्य',
  portfolioHeroH1_3: ' प्रमाणीकरणं कुरु।',
  portfolioHeroH1_4: 'RPL विस्तारः।',
  startAssessment: 'मूल्याङ्कनं प्रारभताम्',
  assessorLogin: 'परीक्षकप्रवेशः',
  makeItClear: '०१ — स्पष्टं पारदर्शकं च',
  buildShapeShip: 'शिक्षध्वम् / सृजध्वम् / वर्धध्वम्',
  tickerAiAssisted: 'AI-सहाय्यितं RPL',
  tickerNsqf: 'NSQF-अनुरूपम्',
  tickerHumanLoop: 'मानवीय-सत्यापन-सहितम्',
  tickerRegional: '२२ भारतीयभाषाः',
  tickerOffline: 'ऑफलाइन-प्रथम-समकालनम्',
  tickerMinistry: 'कौशलविकासमन्त्रालयः',
  ourWork: 'अस्माकं कार्यम्',
  work1Title: 'सुलभानुभवमानचित्रणम्',
  work1Desc: 'श्रमिकेभ्यः स्वमातृभाषायां कौशलनिवेदनाय संवादात्मकं माध्यमम्।',
  work2Title: 'चलच्चित्र-चित्र-मूल्याङ्कनम्',
  work2Desc: 'व्यावहारिककार्यस्य आकलनाय दृश्यप्रमाणानां सङ्ग्रहः।',
  work3Title: 'प्रमाणीकृत-अङ्कनम्',
  work3Desc: 'परीक्षकेभ्यः NSQF मानकानुरूपं यथार्थं मूल्याङ्कनम्।',
  work4Title: 'स्वल्प-अन्तर्जालेऽपि कार्यक्षमम्',
  work4Desc: 'अन्तर्जालस्य अभावेऽपि दत्तांशः दूरभाषे सुरक्षितः तिष्ठति।',
  tagSelfDecl: 'स्वघोषणा',
  tagAiAssist: 'AI-सहाय्यम्',
  tagPractical: 'व्यावहारिकसाधनम्',
  tagMedia: 'माध्यमप्रमाणम्',
  tagAssessor: 'परीक्षकसहयोगः',
  tagNsqf: 'NSQF मानकाः',
  tagOffline: 'ऑफलाइन सक्षमम्',
  tagSync: 'स्वचालितसमकालनम्',
  feat1Title: 'स्वकीयम् अनुभवं वदन्तु',
  feat1Desc: 'स्वकीयप्रादेशिकभाषायां ध्वनिनिवेशं प्रयुञ्जताम्',
  feat2Title: 'स्वकार्यं प्रदर्शयन्तु',
  feat2Desc: 'चित्राणि, चलच्चित्राणि, कार्यप्रमाणानि च सरलताया उपारोपयन्तु',
  feat3Title: 'NSQF मानकैः सह मेलनम्',
  feat3Desc: 'AI भवतः व्यावहारिककौशलं राष्ट्रियमूल्यैः सह संयोजयति',
  feat4Title: 'मानवपरीक्षकस्य निर्णयः',
  feat4Desc: 'AI केवलं परामर्शं ददाति, प्रमाणितविशेषज्ञः अन्तिमनिर्णयं करोति',
  howItWorks: 'एतत् कथं कार्यं करोति',
  howItWorksSub: 'त्रीणि सरलानि सोपानानि। कापि कठिना परीक्षा नास्ति।',
  step1Title: 'स्वविषये वदन्तु',
  step1Desc: 'स्वकीयं व्यवसायं चिनोतु। स्वकीयमनुभवं कस्यामपि भाषायां वदतु।',
  step2Title: 'स्वकार्यं प्रदर्शयन्तु',
  step2Desc: 'निर्मितानां वस्तूनां चित्राणि स्वीकुर्वन्तु अथवा लघु चलच्चित्रं रचयन्तु।',
  step3Title: 'प्रमाणपत्रं प्राप्नुवन्तु',
  step3Desc: 'AI कौशलमेलनं करोति प्रमाणितपरीक्षकश्च राष्ट्रियप्रमाणपत्रं प्रयच्छति।',
  ctaBannerTitlePortfolio: 'भारतस्य कुशलकारिकरेभ्यः आधिकारिकं सम्मानं यच्छन्तु।',
  ctaBannerTitleGovt: 'भारतस्य कर्मकरेभ्यः कौशलमस्ति। आगच्छन्तु तत् प्रमाणीकुर्मः।',
  ctaBannerSub: 'असंगठितक्षेत्रस्य कर्मकरेभ्यः विशेषरूपेण निर्मितम्।',
  beginSelfDeclaration: 'स्वघोषणां प्रारभताम्',
  welcomeCandidate: 'स्वागतम्, रमेश 👋',
  candidateId: 'प्रार्थी परिचयपत्रम्: RPL-2024-8842',
  allSynced: 'सर्वं समकालिकम् अभवत्',
  newDeclaration: 'नवीना घोषणा',
  newDeclarationSub: 'नवीनं कौशलमानचित्रणं प्रारभताम्',
  uploadEvidence: 'प्रमाणम् उपारोप्यताम्',
  uploadEvidenceSub: 'चित्राणि चलच्चित्राणि वा योजयन्तु',
  viewCertificate: 'प्रमाणपत्रं पश्यतु',
  viewCertificateSub: 'स्वकीयम् NSQF प्रमाणपत्रम् अवतरणिकां कुर्वन्तु',
  yourApplications: 'भवतः आवेदनानि',
  underReview: 'समीक्षाधीनं वर्तते',
  needMoreInfo: 'अधिकसूचना अपेक्षिता',
  certified: 'प्रमाणीकृतम्',
  nsqfLevel: 'NSQF स्तरः',
  submittedAgo: 'दिनद्वयात् पूर्वं समर्पितम्',
  assessorReviewing: 'परीक्षकः भवतः प्रमाणानां परीक्षणं करोति…',
  needClearerVideo: 'विद्युत्तन्त्रीसुरक्षापरीक्षणस्य स्पष्टं चलच्चित्रम् आवश्यकम्।',
  details: 'विवरणम्',
  uploadNow: 'अधुनैव उपारोपयतु',
  downloadPdf: 'PDF अवतरणं कुर्वन्तु',
  worksWithoutInternet: 'अन्तर्जालं विनापि कार्यं करोति',
  worksWithoutInternetSub: 'अन्तर्जालस्य अभावेऽपि आवेदनं पश्यन्तु कुर्वन्तु च। सञ्जाले आगते स्वयमेव समकालनं भविष्यति।',
  pendingReview: 'समीक्षार्थं प्रतीक्षितम्',
  searchCandidate: 'प्रार्थिनम् अन्विषन्तु…',
  aiDisclaimer: 'AI केवलं सहाय्यं करोति। अन्तिमः निर्णयस्तु मानवपरीक्षकस्यैव भवति।',
  photos: 'चित्राणि',
  video: 'चलच्चित्रम्',
  aiSuggestion: 'AI परामर्शः',
  competent: 'योग्यः (सक्षमः)',
  needsReview: 'पुनरावलोकनम् आवश्यकम्',
  lowMatch: 'अल्पमेलनम्',
  yes: 'आम्',
  partial: 'आंशिकम्',
  no: 'न',
  saveDraft: 'प्रारूपं रक्षतु',
  notYetCompetent: 'अधुना पूर्णतया न योग्यः',
  requestEvidence: 'अतिरिक्तप्रमाणं प्रार्थयताम्',
  recommendCert: 'प्रमाणीकरणस्य अनुशंसां करोतु',
  selfDeclaration: 'स्वघोषणा',
  selfDeclarationSub: 'स्वकीयकौशलविषये वदन्तु — स्वकीयशब्दैः।',
  offlineReady: 'ऑफलाइन सिद्धम्',
  step: 'सोपानम्',
  of: 'तः',
  yourTrade: 'भवतः व्यवसायः',
  experience: 'अनुभवः',
  evidence: 'प्रमाणम्',
  result: 'परिणामः',
  whatWork: 'भवान् किं कार्यं करोति?',
  tapPicture: 'स्वकार्यसम्बद्धे चित्रे स्पृशतु।',
  tellAboutWork: 'स्वकार्यविषये कथयतु',
  pressAndSpeak: 'नोदयित्वा वदतु',
  speakAnyLang: 'कस्यामपि भाषायां वदतु',
  listening: '🔴 शृण्वन् अस्ति… अधुना वदतु',
  howManyYears: 'कति वर्षेषु भवान् एतत् कार्यं कुर्वन् अस्ति?',
  whatTools: 'भवन्तः कानि उपकरणानि प्रयुञ्जते?',
  whatKindWork: 'सामान्यतया भवान् कीदृशं कार्यं करोति?',
  whereWork: 'भवान् कुत्र कार्यं करोति?',
  showYourWork: 'स्वकार्यं प्रदर्शयतु',
  evidenceSub: 'चित्राणि चलच्चित्राणि च परीक्षकं भवतः कौशलज्ञाने सहाय्यं कुर्वन्ति।',
  takePhoto: 'चित्रं स्वीकरोतु',
  takePhotoSub: 'स्वकार्यस्य',
  recordVideo: 'चलच्चित्रं रचयतु',
  recordVideoSub: 'लघुदृश्यखण्डम्',
  uploadPaper: 'पत्रम् उपारोपयतु',
  uploadPaperSub: 'प्रमाणपत्रम् अनुभवपत्रं वा',
  dragFiles: 'अथवा सञ्चिकाः अत्र आकर्षन्तु',
  fileTypes: 'JPG, PNG, MP4, PDF — ५० MB यावत्',
  offlineUpload: 'भवन्तः एतत् अन्तर्जालं विनापि कर्तुं शक्नुवन्ति।',
  offlineUploadSub: 'सञ्चिकाः दूरभाषे सुरक्षिताः स्थास्यन्ति, सञ्जाले आगते उपारोपिताः भविष्यन्ति।',
  suggestedMatch: 'प्रस्तावितमेलनम्',
  match: 'मेलनम्',
  humanReview: 'मानवपरीक्षकः समीक्ष्य निर्णयं करिष्यति।',
  humanReviewSub: 'एतत् सङ्गणकस्य प्राथमिकः परामर्शः। प्रमाणितपरीक्षकः अन्तिमनिर्णयं करिष्यति।',
  back: 'पृष्ठतः',
  next: 'अग्रिमम्',
  submit: 'समर्प्यताम्',
  orTypeBelow: 'पिञ्जं नोदयित्वा वदतु अथवा अधः लिखतु।',
  electrician: 'विद्युत्कारः',
  plumber: 'नलकारः',
  welder: 'सन्धानकारः',
  carpenter: 'तक्षा (काष्ठकारः)',
  mason: 'शिल्पी (लेपकः)',
  tailor: 'सौचिकः',
  cook: 'सूपकारः',
  driver: 'चालकः',
  other: 'अन्यत्',
  performBasicWork: 'मूलभूतं तान्त्रिककार्यं करणम्',
  readDrawings: 'सरलचित्राणां पठनम्',
  followSafety: 'कार्यस्थले सुरक्षाविधानानां पालनम्',
  footerDesc: 'स्मार्ट इंडिया हैकाथॉन अन्तर्गतं पूर्वशिक्षायाः मान्यतायै (RPL) AI-आधृतं कौशलमूल्याङ्कनोपकरणम्।',
  sponsoredBy: 'प्रायोजकाः',
  msdeFullName: 'कौशलविकास-उद्यमितामन्त्रालयः (MSDE)',
  ncvetFullName: 'व्यावसायिकशिक्षाप्रशिक्षणाय राष्ट्रियपरिषद (NCVET)',
  project: 'परियोजना',
  problemId: 'समस्या संङ्ख्या: SIH26242',
  themeSmartEdu: 'विषयः: स्मार्ट-शिक्षा',
  categorySoftware: 'वर्गः: तन्त्रांशः (Software)',
  footerCopyright: '© २०२६ RPL AI मूल्याङ्कनयन्त्रम् — भारतस्य कुशलकर्मकरेभ्यः समर्पितम्'
};

export const ne = {
  navHome: 'गृहपृष्ठ',
  navSelfDeclaration: 'स्वघोषणा',
  navCandidate: 'उम्मेदवार',
  navAssessor: 'मूल्यांकनकर्ता',
  govtInitiative: 'भारत सरकारको पहल',
  ministryName: 'कौशल विकास तथा उद्यमशीलता मन्त्रालय',
  rplAiAssessment: 'RPL AI सीप मूल्यांकन',
  heroTitle: 'आफ्नो सीपको सरकारी प्रमाणपत्र पाउनुहोस्',
  heroSub: 'काम गरेर सिकेका श्रमिकहरूका लागि। कुनै औपचारिक शिक्षाको आवश्यकता छैन।',
  portfolioHeroH1_1: 'सीप जाँच्नुहोस्।',
  portfolioHeroH1_2: 'अनुभवलाई',
  portfolioHeroH1_3: ' प्रमाणित गर्नुहोस्।',
  portfolioHeroH1_4: 'RPL विस्तार।',
  startAssessment: 'मूल्यांकन सुरु गर्नुहोस्',
  assessorLogin: 'मूल्यांकनकर्ता लगइन',
  makeItClear: '०१ — स्पष्ट र पारदर्शी',
  buildShapeShip: 'सिक्नुहोस् / बनाउनुहोस् / अघि बढ्नुहोस्',
  tickerAiAssisted: 'AI-सहायता प्राप्त RPL',
  tickerNsqf: 'NSQF अनुरूप',
  tickerHumanLoop: 'मानवीय प्रमाणीकरण सहित',
  tickerRegional: '२२ भारतीय भाषाहरू',
  tickerOffline: 'अफलाइन-पहिलो सिंक',
  tickerMinistry: 'कौशल विकास मन्त्रालय',
  ourWork: 'हाम्रो काम',
  work1Title: 'सजिलो अनुभव म्यापिङ',
  work1Desc: 'श्रमिकहरूका लागि आफ्नै भाषामा सीप बताउन संवादात्मक इन्टरफेस।',
  work2Title: 'भिडियो र फोटो मूल्यांकन',
  work2Desc: 'व्यावहारिक कामको मूल्यांकनका लागि प्रत्यक्ष प्रमाण संकलन।',
  work3Title: 'मानकीकृत स्कोरिङ',
  work3Desc: 'मूल्यांकनकर्ताहरूका लागि NSQF मापदण्ड अनुसार सटीक स्कोरिङ।',
  work4Title: 'कम इन्टरनेटमा पनि सक्षम',
  work4Desc: 'इन्टरनेट नहुँदा पनि डाटा फोनमा सुरक्षित रहन्छ।',
  tagSelfDecl: 'स्वघोषणा',
  tagAiAssist: 'AI सहयोग',
  tagPractical: 'व्यावहारिक साधन',
  tagMedia: 'मिडिया प्रमाण',
  tagAssessor: 'परीक्षक सहयोग',
  tagNsqf: 'NSQF मापदण्ड',
  tagOffline: 'अफलाइन सक्षम',
  tagSync: 'अटो सिंक',
  feat1Title: 'आफ्नो अनुभव बोल्नुहोस्',
  feat1Desc: 'आफ्नै भाषामा आवाज दिएर जानकारी भर्नुहोस्',
  feat2Title: 'आफ्नो काम देखाउनुहोस्',
  feat2Desc: 'तस्बिरहरू, भिडियोहरू र कामको प्रमाण सजिलै अपलोड गर्नुहोस्',
  feat3Title: 'NSQF सँग मेल',
  feat3Desc: 'AI ले तपाईंको व्यावहारिक सीपलाई राष्ट्रिय मापदण्डसँग जोड्छ',
  feat4Title: 'मानव मूल्यांकनकर्ताको निर्णय',
  feat4Desc: 'AI ले सुझाव दिन्छ, प्रमाणित विशेषज्ञले अन्तिम निर्णय लिन्छन्',
  howItWorks: 'यो कसरी काम गर्छ',
  howItWorksSub: 'तीन सरल चरणहरू। कुनै गाह्रो परीक्षा वा फारम छैन।',
  step1Title: 'आफ्नो बारेमा बताउनुहोस्',
  step1Desc: 'आफ्नो पेशा छान्नुहोस्। कुनै पनि भाषामा आफ्नो कामको अनुभव बोल्नुहोस्।',
  step2Title: 'आफ्नो काम देखाउनुहोस्',
  step2Desc: 'आफूले बनाएको सामानको तस्बिर खिच्नुहोस् वा छोटो भिडियो बनाउनुहोस्।',
  step3Title: 'प्रमाणपत्र पाउनुहोस्',
  step3Desc: 'AI ले सीप मिलाउँछ र प्रमाणित परीक्षकले राष्ट्रिय प्रमाणपत्र जारी गर्छ।',
  ctaBannerTitlePortfolio: 'भारतका दक्ष हातहरूलाई दिनुहोस् आधिकारिक मान्यता।',
  ctaBannerTitleGovt: 'भारतका श्रमिकहरूसँग सीप छ। आउनुहोस् यसलाई प्रमाणित गरौं।',
  ctaBannerSub: 'अनौपचारिक क्षेत्रका कामदारहरूका लागि विशेष रूपमा निर्मित।',
  beginSelfDeclaration: 'स्वघोषणा सुरु गर्नुहोस्',
  welcomeCandidate: 'नमस्ते, रमेश 👋',
  candidateId: 'उम्मेदवार आईडी: RPL-2024-8842',
  allSynced: 'सबै डाटा सिंक भयो',
  newDeclaration: 'नयाँ घोषणा',
  newDeclarationSub: 'नयाँ सीप म्यापिङ सुरु गर्नुहोस्',
  uploadEvidence: 'प्रमाण अपलोड गर्नुहोस्',
  uploadEvidenceSub: 'तस्बिर वा भिडियो थप्नुहोस्',
  viewCertificate: 'प्रमाणपत्र हेर्नुहोस्',
  viewCertificateSub: 'आफ्नो NSQF प्रमाणपत्र डाउनलोड गर्नुहोस्',
  yourApplications: 'तपाईंका आवेदनहरू',
  underReview: 'समीक्षाधीन',
  needMoreInfo: 'थप जानकारी चाहिन्छ',
  certified: 'प्रमाणित',
  nsqfLevel: 'NSQF स्तर',
  submittedAgo: '२ दिन अघि पेश गरिएको',
  assessorReviewing: 'मूल्यांकनकर्ताले तपाईंका प्रमाणहरू जाँच्दै हुनुहुन्छ…',
  needClearerVideo: 'वायरिङ सुरक्षा जाँचको स्पष्ट भिडियो पठाउनुहोस्।',
  details: 'विवरण',
  uploadNow: 'अहिले अपलोड गर्नुहोस्',
  downloadPdf: 'PDF डाउनलोड गर्नुहोस्',
  worksWithoutInternet: 'इन्टरनेट बिना पनि काम गर्छ',
  worksWithoutInternetSub: 'इन्टरनेट नहुँदा पनि आवेदन हेर्नुहोस् र बनाउनुहोस्। अनलाइन भएपछि आफैं सिंक हुनेछ।',
  pendingReview: 'समीक्षाका लागि बाँकी',
  searchCandidate: 'उम्मेदवार खोज्नुहोस्…',
  aiDisclaimer: 'AI ले केवल सुझाव दिन्छ। अन्तिम प्रमाणीकरण निर्णय मानव मूल्यांकनकर्ताकै हुन्छ।',
  photos: 'तस्बिरहरू',
  video: 'भिडियो',
  aiSuggestion: 'AI सुझाव',
  competent: 'योग्य (सक्षम)',
  needsReview: 'पुनरावलोकन आवश्यक',
  lowMatch: 'कम मेल',
  yes: 'हो',
  partial: 'आंशिक',
  no: 'होइन',
  saveDraft: 'ड्राफ्ट सुरक्षित गर्नुहोस्',
  notYetCompetent: 'अझै पूर्ण योग्य छैन',
  requestEvidence: 'थप प्रमाण माग्नुहोस्',
  recommendCert: 'प्रमाणीकरणको सिफारिस गर्नुहोस्',
  selfDeclaration: 'स्वघोषणा',
  selfDeclarationSub: 'आफ्नो सीपको बारेमा बताउनुहोस् — आफ्नै शब्दमा।',
  offlineReady: 'अफलाइन तयार',
  step: 'चरण',
  of: 'को',
  yourTrade: 'तपाईंको पेशा',
  experience: 'अनुभव',
  evidence: 'प्रमाण',
  result: 'नतिजा',
  whatWork: 'तपाईं के काम गर्नुहुन्छ?',
  tapPicture: 'आफ्नो कामसँग मिल्ने चित्रमा थिच्नुहोस्।',
  tellAboutWork: 'आफ्नो कामको बारेमा बताउनुहोस्',
  pressAndSpeak: 'थिच्नुहोस् र बोल्नुहोस्',
  speakAnyLang: 'कुनै पनि भाषामा बोल्नुहोस्',
  listening: '🔴 सुन्दैछ… अब बोल्नुहोस्',
  howManyYears: 'तपाईं कति वर्षदेखि यो काम गर्दै हुनुहुन्छ?',
  whatTools: 'तपाईं कुन औजारहरू प्रयोग गर्नुहुन्छ?',
  whatKindWork: 'सामान्यतया तपाईं कस्तो प्रकारको काम गर्नुहुन्छ?',
  whereWork: 'तपाईं कहाँ काम गर्नुहुन्छ?',
  showYourWork: 'आफ्नो काम देखाउनुहोस्',
  evidenceSub: 'तस्बिर र भिडियोले परीक्षकलाई तपाईंको सीप बुझ्न मद्दत गर्छ।',
  takePhoto: 'तस्बिर खिच्नुहोस्',
  takePhotoSub: 'आफ्नो कामको',
  recordVideo: 'भिडियो बनाउनुहोस्',
  recordVideoSub: 'एउटा छोटो भिडियो',
  uploadPaper: 'कागजात अपलोड गर्नुहोस्',
  uploadPaperSub: 'प्रमाणपत्र वा अनुभव पत्र',
  dragFiles: 'वा फाइलहरू यहाँ तान्नुहोस्',
  fileTypes: 'JPG, PNG, MP4, PDF — ५० MB सम्म',
  offlineUpload: 'तपाईं यो इन्टरनेट बिना पनि गर्न सक्नुहुन्छ।',
  offlineUploadSub: 'फाइलहरू फोनमा सुरक्षित रहनेछन् र नेट आउँदा अपलोड हुनेछन्।',
  suggestedMatch: 'सुझाइएको मेल',
  match: 'मेल',
  humanReview: 'मानव मूल्यांकनकर्ताले जाँचेर निर्णय गर्नुहुनेछ।',
  humanReviewSub: 'यो कम्प्युटरको प्रारम्भिक सुझाव हो। प्रमाणित परीक्षकले अन्तिम निर्णय लिनुहुनेछ।',
  back: 'पछाडि',
  next: 'अगाडि',
  submit: 'बुझाउनुहोस्',
  orTypeBelow: 'बटन थिचेर बोल्नुहोस् वा तल लेख्नुहोस्।',
  electrician: 'इलेक्ट्रीशियन',
  plumber: 'प्लम्बर',
  welder: 'वेल्डर',
  carpenter: 'सिकर्मी',
  mason: 'डकर्मी',
  tailor: 'दर्जी',
  cook: 'भान्से',
  driver: 'चालक',
  other: 'अन्य',
  performBasicWork: 'आधारभूत प्राविधिक काम गर्नु',
  readDrawings: 'सरल रेखाचित्र बुझ्नु',
  followSafety: 'कार्यस्थलको सुरक्षा नियमहरूको पालना गर्नु',
  footerDesc: 'स्मार्ट इन्डिया ह्याकाथन अन्तर्गत पूर्व सिकाइको मान्यता (RPL) का लागि AI सीप मूल्यांकन प्रणाली।',
  sponsoredBy: 'प्रायोजक',
  msdeFullName: 'कौशल विकास तथा उद्यमशीलता मन्त्रालय (MSDE)',
  ncvetFullName: 'राष्ट्रिय व्यावसायिक शिक्षा तथा तालिम परिषद् (NCVET)',
  project: 'परियोजना',
  problemId: 'समस्या आईडी: SIH26242',
  themeSmartEdu: 'थीम: स्मार्ट शिक्षा',
  categorySoftware: 'श्रेणी: सफ्टवेयर',
  footerCopyright: '© २०२६ RPL AI मूल्यांकन उपकरण — भारतका दक्ष श्रमिकहरूका लागि निर्मित'
};

export const kok = {
  navHome: 'घर',
  navSelfDeclaration: 'स्वयंघोषणा',
  navCandidate: 'उमेदवार',
  navAssessor: 'मूल्यांकनकार',
  govtInitiative: 'भारत सरकाराचो उपक्रम',
  ministryName: 'कौशल्य विकास आनी उद्योजकता मंत्रालय',
  rplAiAssessment: 'RPL AI कौशल्य मूल्यांकन',
  heroTitle: 'तुमच्या कौशल्याक सरकारी मान्यता मेळयात',
  heroSub: 'कामा वयल्यान शिकपी कामगारां खातीर. खंयच्याय औपचारिक शिक्षणाची गरज ना.',
  portfolioHeroH1_1: 'कौशल्य पारखात.',
  portfolioHeroH1_2: 'अणभवाक',
  portfolioHeroH1_3: ' प्रमाणपत्र दियात.',
  portfolioHeroH1_4: 'RPL विस्तार.',
  startAssessment: 'मूल्यांकन सुरू करात',
  assessorLogin: 'मूल्यांकनकार लॉगइन',
  makeItClear: '०१ — स्पश्ट आनी पारदर्शक',
  buildShapeShip: 'शिकात / घडायात / फुडें वचात',
  tickerAiAssisted: 'AI-सहाय्यित RPL',
  tickerNsqf: 'NSQF अनुरूप',
  tickerHumanLoop: 'मनीस तपासणे सयत',
  tickerRegional: '२२ भारतीय भासो',
  tickerOffline: 'ऑफलाइन-पयलीं सिंक',
  tickerMinistry: 'कौशल्य विकास मंत्रालय',
  ourWork: 'आमचें काम',
  work1Title: 'सोंपें अणभव मॅपिंग',
  work1Desc: 'कामगारांक आपल्याच भाशेंत कौशल्य सांगपा खातीर संवादात्मक इंटरफेस.',
  work2Title: 'व्हिडिओ आनी फोटो मूल्यांकन',
  work2Desc: 'प्रत्यक्ष कामाच्या तपासणे खातीर दृश्य पुराव्यांचो संग्रह.',
  work3Title: 'प्रमाणित स्कोरींग',
  work3Desc: 'मूल्यांकनकारां खातीर NSQF मानकां प्रमाण अचूक गूण.',
  work4Title: 'उण्या नेटारय सक्षम',
  work4Desc: 'इंटरनेट नाशिल्ल्या वेळारय म्हायती फोनार सुरक्षित उरता.',
  tagSelfDecl: 'स्वयंघोषणा',
  tagAiAssist: 'AI सहाय्य',
  tagPractical: 'प्रत्यक्ष साधन',
  tagMedia: 'मिडिया पुरावे',
  tagAssessor: 'परीक्षक सहकार्य',
  tagNsqf: 'NSQF मानकां',
  tagOffline: 'ऑफलाइन सक्षम',
  tagSync: 'ऑटो सिंक',
  feat1Title: 'तुमचो अणभव उलोवन सांगात',
  feat1Desc: 'तुमच्या प्रादेशिक भाशेंत आवाज इनपुट वापरा',
  feat2Title: 'तुमचें काम दाखयात',
  feat2Desc: 'फोटो, व्हिडिओ आनी कामाचे पुरावे सोंपेपणान अपलोड करात',
  feat3Title: 'NSQF कडेन जोडणी',
  feat3Desc: 'AI तुमचीं व्यावहारिक कौशल्यां राष्ट्रीय मानकांकडेन जोडता',
  feat4Title: 'मनीस परीक्षकाचो निर्णय',
  feat4Desc: 'AI सुचोवण्यो दिता, प्रमाणित तज्ञ निमाणो निर्णय घेतात',
  howItWorks: 'हें कशें काम करता',
  howItWorksSub: 'तीन सोंप्यो पावल्यो. कसलीय कठीण परीक्षा वा फॉर्म ना.',
  step1Title: 'तुमच्या विशीं सांगात',
  step1Desc: 'तुमचो वेवसाय वेचात. खंयचेय भाशेंत तुमच्या अणभवा विशीं उलययात.',
  step2Title: 'तुमचें काम दाखयात',
  step2Desc: 'तयार केल्ल्या वस्तूंचे फोटो काडात वा ल्हान व्हिडिओ बनवा.',
  step3Title: 'प्रमाणपत्र मेळयात',
  step3Desc: 'AI कौशल्यांची तपासणी करता आनी परीक्षक राष्ट्रीय प्रमाणपत्र दिता.',
  ctaBannerTitlePortfolio: 'भारताच्या हुशार हातांक दियात अधिकृत मान.',
  ctaBannerTitleGovt: 'भारताच्या कामगारां कडेन कसब आसा. ताका प्रमाणित करया.',
  ctaBannerSub: 'असंघटित क्षेत्रांतल्या कामगारां खातीर खास तयार केल्लें.',
  beginSelfDeclaration: 'स्वयंघोषणा सुरू करात',
  welcomeCandidate: 'येवकार, रमेश 👋',
  candidateId: 'उमेदवार आयडी: RPL-2024-8842',
  allSynced: 'सगळो डेटा सिंक जालो',
  newDeclaration: 'नवी घोषणा',
  newDeclarationSub: 'नवें कौशल्य मॅपिंग सुरू करात',
  uploadEvidence: 'पुरावे अपलोड करात',
  uploadEvidenceSub: 'फोटो वा व्हिडिओ जोडा',
  viewCertificate: 'प्रमाणपत्र पळयात',
  viewCertificateSub: 'तुमचें NSQF प्रमाणपत्र डाउनलोड करात',
  yourApplications: 'तुमचे अर्ज',
  underReview: 'तपासणे खाला',
  needMoreInfo: 'आणखीन म्हायती जाय',
  certified: 'प्रमाणित',
  nsqfLevel: 'NSQF पातळी',
  submittedAgo: '२ दिसां पयलीं धाडिल्लें',
  assessorReviewing: 'मूल्यांकनकार तुमचे पुरावे तपासता…',
  needClearerVideo: 'वायरिंग सुरक्षेचो स्पश्ट व्हिडिओ जाय.',
  details: 'तपशील',
  uploadNow: 'आतांच अपलोड करात',
  downloadPdf: 'PDF डाउनलोड करात',
  worksWithoutInternet: 'इंटरनेट नासतनाय काम करता',
  worksWithoutInternetSub: 'इंटरनेट नाशिल्ल्या वेळारय अर्ज पळयात आनी तयार करात. नेट येतकच सिंक जातलें.',
  pendingReview: 'तपासणे खातीर उरिल्लें',
  searchCandidate: 'उमेदवार सोदात…',
  aiDisclaimer: 'AI फक्त सल्लो दिता. निमाणो निर्णय मनीस परीक्षकाचोच आसता.',
  photos: 'फोटो',
  video: 'व्हिडिओ',
  aiSuggestion: 'AI सुचोवणी',
  competent: 'सक्षम (योग्य)',
  needsReview: 'पुनरावलोकन जाय',
  lowMatch: 'उणी जुळणी',
  yes: 'हय',
  partial: 'थोड्या प्रमाणांत',
  no: 'ना',
  saveDraft: 'मसुदो सांभाळात',
  notYetCompetent: 'अजून पुराय तयार ना',
  requestEvidence: 'आणखीन पुरावे मागा',
  recommendCert: 'प्रमाणपत्राची शिफारस करात',
  selfDeclaration: 'स्वयंघोषणा',
  selfDeclarationSub: 'तुमच्या कौशल्या विशीं सांगात — तुमच्याच उतरांनी.',
  offlineReady: 'ऑफलाइन तयार',
  step: 'पावली',
  of: 'तलें',
  yourTrade: 'तुमचो वेवसाय',
  experience: 'अणभव',
  evidence: 'पुरावे',
  result: 'निकाल',
  whatWork: 'तुमी कसले काम करतात?',
  tapPicture: 'तुमच्या कामाक जुळपी चित्राचेर टॅप करात.',
  tellAboutWork: 'तुमच्या कामा विशीं सांगात',
  pressAndSpeak: 'बटन दाबून उलययात',
  speakAnyLang: 'खंयचेय भाशेंत उलययात',
  listening: '🔴 आयकता… आतां उलययात',
  howManyYears: 'तुमी कितलीं वर्सां हें काम करतात?',
  whatTools: 'तुमी कसल्यो अवजारां वापरतात?',
  whatKindWork: 'सादारणपणान तुमी कसलें काम करतात?',
  whereWork: 'तुमी खंय काम करतात?',
  showYourWork: 'तुमचें काम दाखयात',
  evidenceSub: 'फोटो आनी व्हिडिओ वरवीं परीक्षकाक तुमचें कसब समजपाक मदत जाता.',
  takePhoto: 'फोटो काडात',
  takePhotoSub: 'तुमच्या कामाचो',
  recordVideo: 'व्हिडिओ काडात',
  recordVideoSub: 'एक ल्हान क्लिप',
  uploadPaper: 'कागदपत्र अपलोड करात',
  uploadPaperSub: 'प्रमाणपत्र वा अणभव पत्र',
  dragFiles: 'वा फायली हांगा ओडून हाडात',
  fileTypes: 'JPG, PNG, MP4, PDF — ५० MB मेरेन',
  offlineUpload: 'तुमी हें इंटरनेट नासतनाय करूं शकतात.',
  offlineUploadSub: 'फायली फोनार उरतलीं आनी नेट येतकच अपलोड जातलीं.',
  suggestedMatch: 'सुचयिल्ली जुळणी',
  match: 'जुळणी',
  humanReview: 'मनीस मूल्यांकनकार तपासून निर्णय घेतलो.',
  humanReviewSub: 'ही संगणकाची सुरवातीची सुचोवणी. प्रमाणित परीक्षक निमाणो निर्णय घेतलो.',
  back: 'फाटीं',
  next: 'फुडें',
  submit: 'सादर करात',
  orTypeBelow: 'बटन दाबून उलययात वा सकयल बरयात.',
  electrician: 'इलेक्ट्रिशियन',
  plumber: 'प्लंबर',
  welder: 'वेल्डर',
  carpenter: 'सुतार',
  mason: 'गवंडी',
  tailor: 'दर्जी',
  cook: 'रांदपी',
  driver: 'ड्रायव्हर',
  other: 'हेर',
  performBasicWork: 'बुन्यादी तांत्रिक काम करप',
  readDrawings: 'सादे नकाशे समजप',
  followSafety: 'कामाचे सुवातेर सुरक्षेच्या नियमांचें पालन',
  footerDesc: 'स्मार्ट इंडिया हॅकाथॉन अंतर्गत आदल्या शिक्षणाची मान्यताय (RPL) खातीर AI कौशल्य मूल्यांकन साधन.',
  sponsoredBy: 'प्रायोजक',
  msdeFullName: 'कौशल्य विकास आनी उद्योजकता मंत्रालय (MSDE)',
  ncvetFullName: 'राष्ट्रीय वेवसायिक शिक्षण आनी प्रशिक्षण परिषद (NCVET)',
  project: 'प्रकल्प',
  problemId: 'समस्या आयडी: SIH26242',
  themeSmartEdu: 'थीम: स्मार्ट शिक्षण',
  categorySoftware: 'वर्ग: सॉफ्टवेअर',
  footerCopyright: '© २०२६ RPL AI मूल्यांकन साधन — भारताच्या कुशल कामगारां खातीर तयार केल्लें'
};

export const doi = {
  navHome: 'मुख पृष्ठ',
  navSelfDeclaration: 'स्वै घोषणा',
  navCandidate: 'उम्मीदवार',
  navAssessor: 'मूल्यांकनकर्ता',
  govtInitiative: 'भारत सरकार दी पहल',
  ministryName: 'कौशल विकास ते उद्यमिता मंत्रालय',
  rplAiAssessment: 'RPL AI हुनर मूल्यांकन',
  heroTitle: 'अपने हुनर दा सरकारी प्रमाणपत्र लैओ',
  heroSub: 'कम करदे होई सिखने आह्ले कामेयां लेई। औपचारिक पढ़ाई दी कोई लोड़ नेईं।',
  portfolioHeroH1_1: 'हुनर परखो।',
  portfolioHeroH1_2: 'तजरबे गी',
  portfolioHeroH1_3: ' प्रमाणित करो।',
  portfolioHeroH1_4: 'RPL विस्तार।',
  startAssessment: 'मूल्यांकन शुरू करो',
  assessorLogin: 'परीक्षक लॉगिन',
  makeItClear: '०१ — साफ ते पारदर्शी',
  buildShapeShip: 'सिक्खो / बनाओ / अग्गें बधो',
  tickerAiAssisted: 'AI-सहाय्यित RPL',
  tickerNsqf: 'NSQF अनुरूप',
  tickerHumanLoop: 'इंसानी जांच कन्नै',
  tickerRegional: '२२ भारतीय भाषा',
  tickerOffline: 'ऑफलाइन-पहिलां सिंक',
  tickerMinistry: 'कौशल विकास मंत्रालय',
  ourWork: 'साह्ड़ा कम्म',
  work1Title: 'सौखा तजरबा मैपिंग',
  work1Desc: 'कामेयां लेई अपनी भाशा च हुनर दस्सने लेई संवादात्मक इंटरफेस।',
  work2Title: 'वीडियो ते फोटो मूल्यांकन',
  work2Desc: 'व्यावहारिक कम्म दी जांच लेई दृश्य सबूत कठ्ठे करना।',
  work3Title: 'मानकीकृत स्कोरिंग',
  work3Desc: 'मूल्यांकनकर्ताएं लेई NSQF मापदन अनुसार सटीक स्कोरिंग।',
  work4Title: 'घट्ट इंटरनेट च बी सक्षम',
  work4Desc: 'इंटरनेट नेईं होने पर बी डेटा फोन च सुरक्षित रौंह्दा ऐ।',
  tagSelfDecl: 'स्वै घोषणा',
  tagAiAssist: 'AI सहायता',
  tagPractical: 'व्यावहारिक साधन',
  tagMedia: 'मीडिया सबूत',
  tagAssessor: 'परीक्षक सहयोग',
  tagNsqf: 'NSQF मानक',
  tagOffline: 'ऑफलाइन सक्षम',
  tagSync: 'आटो सिंक',
  feat1Title: 'अपना तजरबा बोलियै दस्सो',
  feat1Desc: 'अपनी क्षेत्रीय भाशा च बोलियै जानकारी दिओ',
  feat2Title: 'अपना कम्म दस्सो',
  feat2Desc: 'फोटो, वीडियो ते कम्म दे सबूत सौखे तरीकै कन्नै अपलोड करो',
  feat3Title: 'NSQF कन्नै मिलान',
  feat3Desc: 'AI थुआढ़े व्यावहारिक हुनर गी राष्ट्रीय मानकां कन्नै जोड़दा ऐ',
  feat4Title: 'मानव परीक्षक दा फैसला',
  feat4Desc: 'AI स्कोर सुझांदा ऐ, प्रमाणित विशेषज्ञ आखरी फैसला लैंदे न',
  howItWorks: 'एह कियां कम्म करदा ऐ',
  howItWorksSub: 'त्रै सौखे चरण। कोई औखी परीक्षा या लंबा फार्म नेईं।',
  step1Title: 'अपने बारे च दस्सो',
  step1Desc: 'अपना पेशा चुनो। अपनी भाशा च अपने कम्म दे तजरबे बारे बोलो।',
  step2Title: 'अपना कम्म दस्सो',
  step2Desc: 'बनाई गेदी शैह् दी फोटो खिच्चो जां निक्का वीडियो बनाओ।',
  step3Title: 'सर्टिफिकेट लैओ',
  step3Desc: 'AI हुनर परखदा ऐ ते प्रमाणित परीक्षक राष्ट्रीय सर्टिफिकेट जारी करदा ऐ।',
  ctaBannerTitlePortfolio: 'भारत दे हुनरमंद हथें गी दिओ सरकारी पन्छान।',
  ctaBannerTitleGovt: 'भारत दे कामेएं कोल हुनर ऐ। आओ एह्गी प्रमाणित करचे।',
  ctaBannerSub: 'असंगठित क्षेत्र दे कामेयां लेई विशेष रूप कन्नै बनाया गेदा।',
  beginSelfDeclaration: 'स्वै घोषणा शुरू करो',
  welcomeCandidate: 'नमस्ते, रमेश 👋',
  candidateId: 'उम्मीदवार आईडी: RPL-2024-8842',
  allSynced: 'सब डेटा सिंक होई गेआ',
  newDeclaration: 'नवीं घोषणा',
  newDeclarationSub: 'नवां हुनर मैपिंग शुरू करो',
  uploadEvidence: 'सबूत अपलोड करो',
  uploadEvidenceSub: 'फोटो जां वीडियो जोड़ो',
  viewCertificate: 'सर्टिफिकेट दिक्खो',
  viewCertificateSub: 'अपना NSQF सर्टिफिकेट डाउनलोड करो',
  yourApplications: 'थुआह्ड़ी अर्जियां',
  underReview: 'समीक्षा अधीन',
  needMoreInfo: 'होर जानकारी चाहिदी',
  certified: 'प्रमाणित',
  nsqfLevel: 'NSQF स्तर',
  submittedAgo: '२ दिन पैह्ले जमा कीता',
  assessorReviewing: 'मूल्यांकनकर्ता थुआह्ड़े सबूत जांचदा पोरहा ऐ…',
  needClearerVideo: 'वायरिंग सुरक्षा जांच दी साफ वीडियो चाहिदी ऐ।',
  details: 'विवरण',
  uploadNow: 'हुने अपलोड करो',
  downloadPdf: 'PDF डाउनलोड करो',
  worksWithoutInternet: 'इंटरनेट बगैर बी कम्म करदा ऐ',
  worksWithoutInternetSub: 'इंटरनेट नेईं होने पर बी अर्जी दिक्खो ते बनाओ। ऑनलाइन औंदे ही सिंक होई जाग।',
  pendingReview: 'समीक्षा लेई लंबित',
  searchCandidate: 'उम्मीदवार खोभो…',
  aiDisclaimer: 'AI सिर्फ सलाह दिंदा ऐ। आखरी फैसला मानव परीक्षक दा ही रौंह्दा ऐ।',
  photos: 'तस्वीरां',
  video: 'वीडियो',
  aiSuggestion: 'AI सुझाव',
  competent: 'योग्य (सक्षम)',
  needsReview: 'पुनरावलोकन जरूरी',
  lowMatch: 'घट्ट मेल',
  yes: 'हां',
  partial: 'अधोआणा',
  no: 'ना',
  saveDraft: 'ड्राफ्ट सांभो',
  notYetCompetent: 'अजे पूर्ण योग्य नेईं',
  requestEvidence: 'होर सबूत मंगो',
  recommendCert: 'सर्टिफिकेट दी सिफारिश करो',
  selfDeclaration: 'स्वै घोषणा',
  selfDeclarationSub: 'अपने हुनर बारे दस्सो — अपने लफ्जां च।',
  offlineReady: 'ऑफलाइन तैयार',
  step: 'कदम',
  of: 'चा',
  yourTrade: 'थुआह्ड़ा पेशा',
  experience: 'तजरबा',
  evidence: 'सबूत',
  result: 'नतीजा',
  whatWork: 'तुस केह् कम्म करदे ओ?',
  tapPicture: 'अपने कम्म कन्नै मिलदी फोटो पर दबाओ।',
  tellAboutWork: 'अपने कम्म बारे दस्सो',
  pressAndSpeak: 'दबाओ ते बोलो',
  speakAnyLang: 'कुसै बी भाशा च बोलो',
  listening: '🔴 सुंदा ऐ… हुण बोलो',
  howManyYears: 'तुस कितने बरें शा एह कम्म करदे ओ?',
  whatTools: 'तुस केह्ड़े औजार इस्तेमाल करदे ओ?',
  whatKindWork: 'सामान्य तौर पर तुस केह्ड़ा कम्म करदे ओ?',
  whereWork: 'तुस कुत्थे कम्म करदे ओ?',
  showYourWork: 'अपना कम्म दस्सो',
  evidenceSub: 'फोटो ते वीडियो कन्नै परीक्षक गी थुआह्ड़ा हुनर समझने च मदद लब्भदी ऐ।',
  takePhoto: 'फोटो खिच्चो',
  takePhotoSub: 'अपने कम्म दी',
  recordVideo: 'वीडियो बनाओ',
  recordVideoSub: 'निक्का वीडियो क्लिप',
  uploadPaper: 'कागज अपलोड करो',
  uploadPaperSub: 'सर्टिफिकेट जां अनुभव पत्र',
  dragFiles: 'जां फाइलें इत्थे लैओ',
  fileTypes: 'JPG, PNG, MP4, PDF — ५० MB तगर',
  offlineUpload: 'तुस एह इंटरनेट बगैर बी करी सकदे ओ।',
  offlineUploadSub: 'फाइलें फोन च सुरक्षित रौनगियां ते नेट औंदे ही अपलोड होनगियां।',
  suggestedMatch: 'सुझाया गेदा मेल',
  match: 'मेल',
  humanReview: 'मानव मूल्यांकनकर्ता जांचियै फैसला लैग।',
  humanReviewSub: 'एह कंप्यूटर दा शुरुआती सुझाव ऐ। प्रमाणित परीक्षक आखरी फैसला लैग।',
  back: 'पिच्छें',
  next: 'अग्गें',
  submit: 'जमा करो',
  orTypeBelow: 'बटन दबायै बोलो जां थल्ले लिखो।',
  electrician: 'इलेक्ट्रीशियन',
  plumber: 'प्लम्बर',
  welder: 'वेल्डर',
  carpenter: 'तर्खान',
  mason: 'राजमिस्त्री',
  tailor: 'दर्जी',
  cook: 'रसोइया',
  driver: 'ड्राइवर',
  other: 'होर',
  performBasicWork: 'बुनियादी तकनीकी कम्म करना',
  readDrawings: 'सादे नक्शे पढ़ना',
  followSafety: 'कम्म दी जगह सुरक्षा नियम दा पालन',
  footerDesc: 'स्मार्ट इंडिया हैकाथॉन तहत पूर्व शिक्षण दी मान्यता (RPL) लेई AI कौशल मूल्यांकन प्रणाली।',
  sponsoredBy: 'प्रायोजक',
  msdeFullName: 'कौशल विकास ते उद्यमिता मंत्रालय (MSDE)',
  ncvetFullName: 'राष्ट्रीय व्यावसायिक शिक्षा ते प्रशिक्षण परिषद (NCVET)',
  project: 'प्रोजेक्ट',
  problemId: 'समस्या आईडी: SIH26242',
  themeSmartEdu: 'थीम: स्मार्ट शिक्षा',
  categorySoftware: 'श्रेणी: सॉफ्टवेयर',
  footerCopyright: '© २०२६ RPL AI मूल्यांकन उपकरण — भारत दे कुशल कामेयां लेई समर्पित'
};

export const brx = {
  navHome: 'न’खर',
  navSelfDeclaration: 'गाव-फोसावनाय',
  navCandidate: 'उम्मेदवार',
  navAssessor: 'आनजादगिरि',
  govtInitiative: 'भारत सरकारनि थांखि',
  ministryName: 'रंसार जौगाथाय आरो फालांगि मन्थ्रिह’लार',
  rplAiAssessment: 'RPL AI रंसार आनजाद',
  heroTitle: 'नोंथांनि रोंगोथिनि सरकारी फोरमान बिलाइ ला',
  heroSub: 'हाबायाव सोलोंनाय खामानि मावग्राफोरनि थाखाय। कोनो फरायसालि फरायनो गोनांथि गैया।',
  portfolioHeroH1_1: 'रोंगोथि आनजाद।',
  portfolioHeroH1_2: 'उदाहारनखौ',
  portfolioHeroH1_3: ' फोरमान खालाम।',
  portfolioHeroH1_4: 'RPL फुवारनाय।',
  startAssessment: 'आनजाद जागाय',
  assessorLogin: 'आनजादगिरि लगइन',
  makeItClear: '०१ — रोखा आरो गोगो',
  buildShapeShip: 'सोलों / बानाय / साबसिन जा',
  tickerAiAssisted: 'AI-मदद गोनां RPL',
  tickerNsqf: 'NSQF मान गोनां',
  tickerHumanLoop: 'मानसि आनजादजों लोगोसे',
  tickerRegional: '२२ भारतारि रावफोर',
  tickerOffline: 'अफलाइन सिंक सुबिदा',
  tickerMinistry: 'रंसार जौगाथाय मन्थ्रिह’लार',
  ourWork: 'जोंनि हाबा',
  work1Title: 'गोरलै महरै मैपिं',
  work1Desc: 'गावनि रावजों गावनि रोंगोथिखौ फोरमायनो गोरलै संवादात्मक इनटारफेस।',
  work2Title: 'भिडियो आरो फोटो आनजाद',
  work2Desc: 'थोंजों हाबानि नायबिजिरनाय थाखाय नुनाय फोरमान थुमसिननाय।',
  work3Title: 'मान गोनां नम्बर होनाय',
  work3Desc: 'आनजादगिरिनि थाखाय NSQF मानो बादियै थि नम्बर होनाय राहा।',
  work4Title: 'इन्टारनेट खमब्लाबो सालायना हायो',
  work4Desc: 'इन्टारनेट गैयि समावबो खारिखौ मोबाइलाव फोजाबो।',
  tagSelfDecl: 'गाव-फोसावनाय',
  tagAiAssist: 'AI मदद',
  tagPractical: 'हाबानि आयदा',
  tagMedia: 'मिडिया फोरमान',
  tagAssessor: 'आनजादगिरि मदद',
  tagNsqf: 'NSQF मानफोर',
  tagOffline: 'अफलाइन खालामनो हागौ',
  tagSync: 'गावनो सिंक जानाय',
  feat1Title: 'गावनि रोंगोथिखौ रायलाय',
  feat1Desc: 'गावनि रावावनो खोलोब होनानै खौरां हो',
  feat2Title: 'गावनि हाबाखौ दिन्थि',
  feat2Desc: 'फोटो, भिडियो आरो हाबानि फोरमान गोरलैयै अपलोड खालाम',
  feat3Title: 'NSQF जों गोरोबनाय',
  feat3Desc: 'AI आ नोंथांनि रोंगोथिखौ हादोरारि मानजों फोनांजाब होयो',
  feat4Title: 'मानसि आनजादगिरिनि सिधान्थ',
  feat4Desc: 'AI आ नेम दिन्थियो, रोंगौ मानसि आनजादगिरियासो जोबथा सिधान्थ लायो',
  howItWorks: 'बेयो माबोरै हाबा मावो',
  howItWorksSub: 'थाम गोरलै थाखो। कोनो गोब्राब आनजाद वा फोरम गैया।',
  step1Title: 'गावनि खोथा खोनथा',
  step1Desc: 'गावनि खामानिखौ सायख’। जेखुनो रावावनो गावनि हाबानि सोमोन्दै बुं।',
  step2Title: 'गावनि हाबाखौ दिन्थि',
  step2Desc: 'बानायनाय बेसादनि फोटो ला वा गुसुं भिडियो बानाय।',
  step3Title: 'फोरमान बिलाइ ला',
  step3Desc: 'AI आ रोंगोथि नायबिजिरो आरो आनजादगिरिया सरकारी बिलाइ होयो।',
  ctaBannerTitlePortfolio: 'भारतनि रोंगौ आखायफोरनो हो सरकारी मान।',
  ctaBannerTitleGovt: 'भारतनि मावफारिनि रोंगोथि दं। फै बेखौ फोरमान खालामनो।',
  ctaBannerSub: 'अनौपचारिक खाम्पानिफोरनि थाखाय गाहायै बानायनाय।',
  beginSelfDeclaration: 'गाव-फोसावनाय जागाय',
  welcomeCandidate: 'बरायबाय, रमेश 👋',
  candidateId: 'उम्मेदवार सिनायथि: RPL-2024-8842',
  allSynced: 'गासै खौरां सिंक जाबाय',
  newDeclaration: 'गोदान फोसावनाय',
  newDeclarationSub: 'गोदान रोंगोथि मैपिं जागाय',
  uploadEvidence: 'फोरमान अपलोड खालाम',
  uploadEvidenceSub: 'फोटो वा भिडियो दाजाब',
  viewCertificate: 'फोरमान बिलाइ नाय',
  viewCertificateSub: 'गावनि NSQF बिलाइखौ डाउनलोड खालाम',
  yourApplications: 'नोंथांनि आरज बिलाइफोर',
  underReview: 'नायबिजिरनाय सोलिगासिनो',
  needMoreInfo: 'गोबां मिथिनो गोनांथि दं',
  certified: 'फोरमान गोनां',
  nsqfLevel: 'NSQF थाखो',
  submittedAgo: '२ सान सिगां होनाय जाबाय',
  assessorReviewing: 'आनजादगिरिया नोंथांनि फोरमानखौ नायगासिनो दं…',
  needClearerVideo: 'वारिं रैखाथि आनजादनि साबसिन भिडियो नांगौ।',
  details: 'गुवारै',
  uploadNow: 'दानाव अपलोड खालाम',
  downloadPdf: 'PDF डाउनलोड खालाम',
  worksWithoutInternet: 'इन्टारनेट गैयिब्लाबो हाबा मावो',
  worksWithoutInternetSub: 'इन्टारनेट गैयिब्लाबो आरज बिलाइ नाय आरो बानाय। अनलाइन जानाय लोगो लोगोनो सिंक जागोन।',
  pendingReview: 'नायबिजिरनो थाखाय नेनाय',
  searchCandidate: 'उम्मेदवार नागिर…',
  aiDisclaimer: 'AI आ नेमखौल’ खन्थायो। जोबथा सिधान्था मानसि आनजादगिरियासो लायो।',
  photos: 'फोटोफोर',
  video: 'भिडियो',
  aiSuggestion: 'AI नेम',
  competent: 'गोगो (रोंगौ)',
  needsReview: 'फिन नायफिननो गोनां',
  lowMatch: 'खम गोरोबनाय',
  yes: 'नंगौ',
  partial: 'खमसे',
  no: 'नङा',
  saveDraft: 'द्राफ्ट दोनथुम',
  notYetCompetent: 'दाबो रोंफुं जायै',
  requestEvidence: 'गोबां फोरमान बि',
  recommendCert: 'फोरमान बिलाइ होनो नेम हो',
  selfDeclaration: 'गाव-फोसावनाय',
  selfDeclarationSub: 'गावनि रोंगोथिनि बागै बुं — गावनि रावाव।',
  offlineReady: 'अफलाइन थियारि जाबाय',
  step: 'थाखो',
  of: 'नि',
  yourTrade: 'नोंथांनि खामानि',
  experience: 'उदाहारन',
  evidence: 'फोरमान',
  result: 'फिथाय',
  whatWork: 'नोंथाङा मा हाबा मावो?',
  tapPicture: 'गावनि हाबाजों गोरोबनाय सावगारियाव थु।',
  tellAboutWork: 'गावनि हाबानि खोथा खोनथा',
  pressAndSpeak: 'थिउ आरो बुं',
  speakAnyLang: 'जेखुनो रावाव बुं',
  listening: '🔴 खोनासंगासिनो… दा बुं',
  howManyYears: 'नोंथाङा बे हाबाखौ बेसे बोसोर मावबोबाय?',
  whatTools: 'नोंथाङा मा मा हाथियार बाहायो?',
  whatKindWork: 'नोंथाङा सरासनस्रायै मा रोखोमनि हाबा मावो?',
  whereWork: 'नोंथाङा बबेयाव हाबा मावो?',
  showYourWork: 'गावनि हाबाखौ दिन्थि',
  evidenceSub: 'फोटो आरो भिडियोआ आनजादगिरिनो नोंथांनि रोंगोथिखौ बुजिनायाव मदद होयो।',
  takePhoto: 'फोटो ला',
  takePhotoSub: 'गावनि हाबानि',
  recordVideo: 'भिडियो बानाय',
  recordVideoSub: 'गुसुं क्लिप',
  uploadPaper: 'बिलाइ अपलोड खालाम',
  uploadPaperSub: 'फोरमान बिलाइ वा राफोद बिलाइ',
  dragFiles: 'वा फाइलफोरखौ बेयाव बोना बोखा',
  fileTypes: 'JPG, PNG, MP4, PDF — ५० MB सिम',
  offlineUpload: 'नोंथाङा बेखौ इन्टारनेट गैयिब्लाबो खालामनो हागोन।',
  offlineUploadSub: 'फाइलफोरा मोबाइलाव फोजाबाय थागोन आरो नेट मोननाय लोगो लोगो अपलोड जागोन।',
  suggestedMatch: 'गोरोबनाय नेम',
  match: 'गोरोबनाय',
  humanReview: 'मानसि आनजादगिरिया नायबिजिरनानै सिधान्थ लागोन।',
  humanReviewSub: 'बेयो कम्प्युटरनि सिगांनि नेमसेल’। मानसि आनजादगिरियासो जोबथा सिधान्थ लायो।',
  back: 'उनफारसे',
  next: 'थां',
  submit: 'गथाय',
  orTypeBelow: 'थिउ आरो बुं वा गाहायाव लिर।',
  electrician: 'इलेक्ट्रिशियन',
  plumber: 'प্লাম्बार',
  welder: 'वेल्डर',
  carpenter: 'बाथा',
  mason: 'दालान मिस्त्री',
  tailor: 'दर्जी',
  cook: 'रान्धुनी',
  driver: 'सालायग्रा (द्राइभार)',
  other: 'गुबुन',
  performBasicWork: 'गुदि हाबा मावनाय',
  readDrawings: 'गोरलै सावगारि बुजिनाय',
  followSafety: 'हाबानि जायगायाव रैखाथि नेम मानिनाय',
  footerDesc: 'स्मार्ट इण्डिया हॅकाथननि सिङाव RPL नि थाखाय AI रोंगोथि आनजाद आयदा।',
  sponsoredBy: 'मददगिरि',
  msdeFullName: 'रंसार जौगाथाय आरो फालांगि मन्थ्रिह’लार (MSDE)',
  ncvetFullName: 'हादोरारि फालांगि सोलोंथाय आरो फोरोंनाय काउन्सिल (NCVET)',
  project: 'हाबाफारि',
  problemId: 'जेंना सिनायथि: SIH26242',
  themeSmartEdu: 'थीम: स्मार्ट सोलोंथाय',
  categorySoftware: 'थाखो: सफ्टवेर',
  footerCopyright: '© २०२६ RPL AI आनजाद आयदा — भारतनि रोंगौ मावफारिफोरनि थाखाय'
};
