export const sat = {
  navHome: 'ᱚᱲᱟᱜ',
  navSelfDeclaration: 'ᱟᱯᱱᱟᱨ ᱩᱪᱷᱟᱹᱱ',
  navCandidate: 'ᱠᱟᱱᱰᱤᱰᱮᱴ',
  navAssessor: 'ᱵᱤᱰᱟᱹᱣᱤᱭᱟᱹ',
  govtInitiative: 'ᱵᱷᱟᱨᱚᱛ ᱥᱚᱨᱠᱟᱨᱟᱜ ᱮᱛᱚᱦᱚᱵ',
  ministryName: 'ᱦᱩᱱᱟᱹᱨ ᱩᱛᱱᱟᱹᱣ ᱟᱨ ᱩᱫᱽᱭᱚᱜᱽ ᱢᱚᱱᱛᱨᱟᱲᱚᱭ',
  rplAiAssessment: 'RPL AI ᱦᱩᱱᱟᱹᱨ ᱵᱤᱰᱟᱹᱣ',
  heroTitle: 'ᱟᱢᱟᱜ ᱦᱩᱱᱟᱹᱨ ᱨᱮᱱᱟᱜ ᱥᱚᱨᱠᱟᱨᱤ ᱥᱟᱠᱷᱤ ᱦᱟᱛᱟᱣ ᱢᱮ',
  heroSub: 'ᱠᱟᱹᱢᱤ ᱠᱟᱛᱮ ᱪᱮᱫ ᱟᱠᱟᱱ ᱠᱟᱹᱢᱤᱭᱟᱹ ᱠᱚ ᱞᱟᱹᱜᱤᱫ᱾ ᱪᱮᱫ ᱟᱥᱲᱟ ᱯᱟᱲᱦᱟᱣ ᱦᱚᱸ ᱵᱟᱝ ᱞᱟᱹᱠᱛᱤᱭᱟ᱾',
  portfolioHeroH1_1: 'ᱦᱩᱱᱟᱹᱨ ᱯᱟᱨᱠᱷᱟᱣ ᱢᱮ᱾',
  portfolioHeroH1_2: 'ᱩᱭᱦᱟᱹᱨ',
  portfolioHeroH1_3: ' ᱥᱟᱹᱵᱩᱛ ᱢᱮ᱾',
  portfolioHeroH1_4: 'RPL ᱯᱟᱥᱱᱟᱣ᱾',
  startAssessment: 'ᱵᱤᱰᱟᱹᱣ ᱮᱦᱚᱵ ᱢᱮ',
  assessorLogin: 'ᱵᱤᱰᱟᱹᱣᱤᱭᱟᱹ ᱞᱚᱜᱤᱱ',
  makeItClear: '᱐᱑ — ᱯᱷᱟᱨᱪᱟ ᱟᱨ ᱥᱟᱹᱨᱤ',
  buildShapeShip: 'ᱪᱮᱫᱚᱜ ᱢᱮ / ᱵᱮᱱᱟᱣ ᱢᱮ / ᱞᱟᱦᱟᱜ ᱢᱮ',
  tickerAiAssisted: 'AI ᱜᱚᱲᱚ RPL',
  tickerNsqf: 'NSQF ᱞᱮᱠᱟᱛᱮ',
  tickerHumanLoop: 'ᱢᱟᱹᱱᱢᱤ ᱵᱤᱰᱟᱹᱣ ᱥᱟᱶ',
  tickerRegional: '᱒᱒ ᱜᱚᱴᱟᱝ ᱥᱤᱧᱚᱛᱤᱭᱟᱹ ᱯᱟᱹᱨᱥᱤ',
  tickerOffline: 'ᱚᱯᱷᱞᱟᱭᱤᱱ ᱥᱤᱝᱠ ᱫᱟᱲᱮ',
  tickerMinistry: 'ᱦᱩᱱᱟᱹᱨ ᱩᱛᱱᱟᱹᱣ ᱢᱚᱱᱛᱨᱟᱲᱚᱭ',
  ourWork: 'ᱟᱵᱚᱣᱟᱜ ᱠᱟᱹᱢᱤ',
  work1Title: 'ᱟᱞᱜᱟ ᱩᱭᱦᱟᱹᱨ ᱢᱮᱯᱤᱝ',
  work1Desc: 'ᱠᱟᱹᱢᱤᱭᱟᱹ ᱠᱚ ᱞᱟᱹᱜᱤᱫ ᱟᱠᱚᱣᱟᱜ ᱯᱟᱹᱨᱥᱤ ᱛᱮ ᱦᱩᱱᱟᱹᱨ ᱞᱟᱹᱭ ᱞᱟᱹᱜᱤᱫ ᱨᱚᱲ ᱤᱱᱴᱟᱨᱯᱷᱮᱥ᱾',
  work2Title: 'ᱵᱷᱤᱰᱤᱭᱳ ᱟᱨ ᱪᱤᱛᱟᱹᱨ ᱵᱤᱰᱟᱹᱣ',
  work2Desc: 'ᱠᱟᱹᱢᱤ ᱵᱤᱰᱟᱹᱣ ᱞᱟᱹᱜᱤᱫ ᱧᱮᱞ ᱥᱟᱹᱵᱩᱛ ᱡᱟᱣᱨᱟ᱾',
  work3Title: 'ᱢᱟᱱᱚᱠ ᱥᱠᱳᱨᱤᱝ',
  work3Desc: 'ᱵᱤᱰᱟᱹᱣᱤᱭᱟᱹ ᱠᱚ ᱞᱟᱹᱜᱤᱫ NSQF ᱢᱟᱱ ᱞᱮᱠᱟᱛᱮ ᱥᱟᱹᱨᱤ ᱱᱚᱢᱵᱚᱨ ᱮᱢᱚᱜ ᱦᱚᱨᱟ᱾',
  work4Title: 'ᱠᱚᱢ ᱤᱱᱴᱟᱨᱱᱮᱴ ᱨᱮᱦᱚᱸ ᱠᱟᱹᱢᱤᱭᱟ',
  work4Desc: 'ᱤᱱᱴᱟᱨᱱᱮᱴ ᱵᱟᱝ ᱛᱟᱦᱮᱸᱱ ᱨᱮᱦᱚᱸ ᱰᱮᱴᱟ ᱯᱷᱳᱱ ᱨᱮ ᱨᱩᱠᱷᱤᱭᱟᱹ ᱛᱟᱦᱮᱸᱱᱟ᱾',
  tagSelfDecl: 'ᱟᱯᱱᱟᱨ ᱩᱪᱷᱟᱹᱱ',
  tagAiAssist: 'AI ᱜᱚᱲᱚ',
  tagPractical: 'ᱠᱟᱹᱢᱤ ᱦᱚᱨᱟ',
  tagMedia: 'ᱢᱤᱰᱤᱭᱟ ᱥᱟᱹᱵᱩᱛ',
  tagAssessor: 'ᱵᱤᱰᱟᱹᱣᱤᱭᱟᱹ ᱜᱚᱲᱚ',
  tagNsqf: 'NSQF ᱢᱟᱱ',
  tagOffline: 'ᱚᱯᱷᱞᱟᱭᱤᱱ ᱥᱟᱯᱲᱟᱣ',
  tagSync: 'ᱟᱡᱛᱮ ᱥᱤᱝᱠ',
  feat1Title: 'ᱟᱢᱟᱜ ᱠᱟᱹᱢᱤ ᱠᱟᱛᱷᱟ ᱨᱚᱲ ᱢᱮ',
  feat1Desc: 'ᱟᱢᱟᱜ ᱯᱟᱹᱨᱥᱤ ᱛᱮ ᱨᱚᱲ ᱠᱟᱛᱮ ᱞᱟᱹᱭ ᱢᱮ',
  feat2Title: 'ᱟᱢᱟᱜ ᱠᱟᱹᱢᱤ ᱩᱫᱩᱜ ᱢᱮ',
  feat2Desc: 'ᱪᱤᱛᱟᱹᱨ, ᱵᱷᱤᱰᱤᱭᱳ ᱟᱨ ᱠᱟᱹᱢᱤ ᱥᱟᱹᱵᱩᱛ ᱟᱞᱜᱟ ᱛᱮ ᱟᱯᱞᱳᱰ ᱢᱮ',
  feat3Title: 'NSQF ᱥᱟᱶ ᱡᱩᱲᱟᱹᱭ',
  feat3Desc: 'AI ᱟᱢᱟᱜ ᱦᱩᱱᱟᱹᱨ ᱫᱤᱥᱚᱢ ᱨᱮᱱᱟᱜ ᱢᱟᱱ ᱥᱟᱶ ᱡᱚᱲᱟᱣᱟ',
  feat4Title: 'ᱢᱟᱹᱱᱢᱤ ᱵᱤᱰᱟᱹᱣᱤᱭᱟᱹ ᱜᱮ ᱴᱷᱟᱹᱣᱠᱟᱹᱭᱟᱭ',
  feat4Desc: 'AI ᱫᱚ ᱥᱚᱞᱦᱟᱭ ᱮᱢᱟ, ᱥᱟᱹᱨᱤ ᱵᱤᱰᱟᱹᱣᱤᱭᱟᱹ ᱜᱮ ᱢᱩᱪᱟᱹᱫ ᱴᱷᱟᱹᱣᱠᱟᱹᱭ ᱦᱟᱛᱟᱣᱟ',
  howItWorks: 'ᱱᱚᱣᱟ ᱪᱮᱫ ᱞᱮᱠᱟᱛᱮ ᱠᱟᱹᱢᱤᱭᱟ',
  howItWorksSub: 'ᱯᱮᱭᱟ ᱟᱞᱜᱟ ᱫᱷᱟᱯ᱾ ᱪᱮᱫ ᱦᱟᱢᱟᱞ ᱵᱤᱱᱤᱰ ᱦᱚᱸ ᱵᱟᱹᱱᱩᱜᱼᱟ᱾',
  step1Title: 'ᱟᱢ ᱵᱟᱵᱚᱛ ᱞᱟᱹᱭ ᱢᱮ',
  step1Desc: 'ᱟᱢᱟᱜ ᱠᱟᱹᱢᱤ ᱵᱟᱪᱷᱟᱣ ᱢᱮ᱾ ᱡᱟᱦᱟᱸᱱ ᱯᱟᱹᱨᱥᱤ ᱛᱮᱜᱮ ᱟᱢᱟᱜ ᱠᱟᱹᱢᱤ ᱠᱟᱛᱷᱟ ᱨᱚᱲ ᱢᱮ᱾',
  step2Title: 'ᱟᱢᱟᱜ ᱠᱟᱹᱢᱤ ᱩᱫᱩᱜ ᱢᱮ',
  step2Desc: 'ᱵᱮᱱᱟᱣ ᱟᱠᱟᱫ ᱡᱤᱱᱤᱥ ᱨᱮᱱᱟᱜ ᱪᱤᱛᱟᱹᱨ ᱛᱩᱞᱟᱹᱣ ᱢᱮ ᱥᱮ ᱠᱷᱟᱴᱚ ᱵᱷᱤᱰᱤᱭᱳ ᱵᱮᱱᱟᱣ ᱢᱮ᱾',
  step3Title: 'ᱥᱟᱠᱷᱤ ᱥᱟᱠᱟᱢ ᱧᱟᱢ ᱢᱮ',
  step3Desc: 'AI ᱦᱩᱱᱟᱹᱨ ᱛᱩᱞᱟᱹᱡᱚᱠᱷᱟᱭᱟ ᱟᱨ ᱥᱚᱨᱠᱟᱨᱤ ᱵᱤᱰᱟᱹᱣᱤᱭᱟᱹ ᱥᱟᱹᱠᱷᱤ ᱥᱟᱠᱟᱢ ᱮᱢᱚᱜᱼᱟ᱾',
  ctaBannerTitlePortfolio: 'ᱥᱤᱧᱚᱛ ᱨᱤᱱ ᱠᱟᱹᱢᱤᱭᱟᱹ ᱠᱚᱣᱟᱜ ᱦᱩᱱᱟᱹᱨ ᱢᱟᱱ ᱮᱢᱟᱭ ᱢᱮ᱾',
  ctaBannerTitleGovt: 'ᱥᱤᱧᱚᱛᱤᱭᱟᱹ ᱠᱟᱹᱢᱤᱭᱟᱹ ᱠᱚ ᱴᱷᱮᱱ ᱦᱩᱱᱟᱹᱨ ᱢᱮᱱᱟᱜᱼᱟ᱾ ᱫᱮᱞᱟ ᱱᱚᱣᱟ ᱥᱟᱹᱵᱩᱛ ᱵᱚᱱ ᱮᱢᱟ᱾',
  ctaBannerSub: 'ᱵᱟᱝ ᱥᱟᱯᱲᱟᱣ ᱠᱟᱹᱢᱤᱭᱟᱹ ᱠᱚ ᱞᱟᱹᱜᱤᱫ ᱵᱤᱥᱮᱥ ᱛᱮᱭᱟᱨ ᱟᱠᱟᱱᱟ᱾',
  beginSelfDeclaration: 'ᱟᱯᱱᱟᱨ ᱩᱪᱷᱟᱹᱱ ᱮᱦᱚᱵ ᱢᱮ',
  welcomeCandidate: 'ᱡᱚᱦᱟᱨ, ᱨᱚᱢᱮᱥ 👋',
  candidateId: 'ᱠᱟᱱᱰᱤᱰᱮᱴ ID: RPL-2024-8842',
  allSynced: 'ᱡᱚᱛᱚ ᱰᱮᱴᱟ ᱥᱤᱝᱠ ᱮᱱᱟ',
  newDeclaration: 'ᱱᱟᱣᱟ ᱩᱪᱷᱟᱹᱱ',
  newDeclarationSub: 'ᱱᱟᱣᱟ ᱦᱩᱱᱟᱹᱨ ᱢᱮᱯᱤᱝ ᱮᱦᱚᱵ ᱢᱮ',
  uploadEvidence: 'ᱥᱟᱹᱵᱩᱛ ᱟᱯᱞᱳᱰ ᱢᱮ',
  uploadEvidenceSub: 'ᱪᱤᱛᱟᱹᱨ ᱥᱮ ᱵᱷᱤᱰᱤᱭᱳ ᱥᱮᱞᱮᱫ ᱢᱮ',
  viewCertificate: 'ᱥᱟᱠᱷᱤ ᱥᱟᱠᱟᱢ ᱧᱮᱞ ᱢᱮ',
  viewCertificateSub: 'ᱟᱢᱟᱜ NSQF ᱥᱟᱠᱟᱢ ᱰᱟᱣᱩᱱᱞᱳᱰ ᱢᱮ',
  yourApplications: 'ᱟᱢᱟᱜ ᱟᱨᱫᱟᱥ ᱠᱚ',
  underReview: 'ᱵᱤᱰᱟᱹᱣ ᱨᱮ ᱢᱮᱱᱟᱜᱼᱟ',
  needMoreInfo: 'ᱟᱨᱦᱚᱸ ᱠᱷᱚᱵᱚᱨ ᱞᱟᱹᱠᱛᱤ',
  certified: 'ᱯᱟᱨᱠᱷᱟᱣ ᱮᱱᱟ',
  nsqfLevel: 'NSQF ᱛᱷᱟᱠ',
  submittedAgo: '᱒ ᱢᱟᱦᱟᱸ ᱢᱟᱲᱟᱝ ᱮᱢ ᱟᱠᱟᱱᱟ',
  assessorReviewing: 'ᱵᱤᱰᱟᱹᱣᱤᱭᱟᱹ ᱟᱢᱟᱜ ᱥᱟᱹᱵᱩᱛ ᱮ ᱧᱮᱞ ᱮᱫᱟ…',
  needClearerVideo: 'ᱣᱟᱭᱨᱤᱝ ᱨᱩᱠᱷᱤᱭᱟᱹ ᱵᱤᱰᱟᱹᱣ ᱨᱮᱱᱟᱜ ᱯᱷᱟᱨᱪᱟ ᱵᱷᱤᱰᱤᱭᱳ ᱞᱟᱹᱠᱛᱤ᱾',
  details: 'ᱵᱤᱵᱚᱨᱚᱱ',
  uploadNow: 'ᱱᱤᱛᱚᱜ ᱟᱯᱞᱳᱰ ᱢᱮ',
  downloadPdf: 'PDF ᱰᱟᱣᱩᱱᱞᱳᱰ ᱢᱮ',
  worksWithoutInternet: 'ᱤᱱᱴᱟᱨᱱᱮᱴ ᱵᱮᱜᱚᱨ ᱦᱚᱸ ᱠᱟᱹᱢᱤᱭᱟ',
  worksWithoutInternetSub: 'ᱤᱱᱴᱟᱨᱱᱮᱴ ᱵᱟᱝ ᱨᱮᱦᱚᱸ ᱟᱨᱫᱟᱥ ᱧᱮᱞ ᱟᱨ ᱵᱮᱱᱟᱣ ᱢᱮ᱾ ᱱᱮᱴ ᱦᱤᱡᱩᱜ ᱥᱟᱶᱛᱮ ᱥᱤᱝᱠ ᱦᱩᱭᱩᱜᱼᱟ᱾',
  pendingReview: 'ᱵᱤᱰᱟᱹᱣ ᱞᱟᱹᱜᱤᱫ ᱛᱟᱺᱜᱤ',
  searchCandidate: 'ᱠᱟᱱᱰᱤᱰᱮᱴ ᱯᱟᱱᱛᱷᱟᱭ ᱢᱮ…',
  aiDisclaimer: 'AI ᱫᱚ ᱠᱷᱟᱹᱞᱤ ᱥᱚᱞᱦᱟᱭ ᱮᱢᱟ᱾ ᱢᱩᱪᱟᱹᱫ ᱴᱷᱟᱹᱣᱠᱟᱹ ᱫᱚ ᱢᱟᱹᱱᱢᱤ ᱵᱤᱰᱟᱹᱣᱤᱭᱟᱹ ᱜᱮ ᱦᱟᱛᱟᱣᱟᱭ᱾',
  photos: 'ᱪᱤᱛᱟᱹᱨ ᱠᱚ',
  video: 'ᱵᱷᱤᱰᱤᱭᱳ',
  aiSuggestion: 'AI ᱥᱚᱞᱦᱟ',
  competent: 'ᱫᱟᱲᱮᱭᱟᱱ (ᱡᱚᱜᱽ)',
  needsReview: 'ᱟᱨᱦᱚᱸ ᱧᱮᱞ ᱞᱟᱹᱠᱛᱤ',
  lowMatch: 'ᱠᱚᱢ ᱢᱤᱞ',
  yes: 'ᱦᱚᱭ',
  partial: 'ᱛᱷᱚᱲᱟ',
  no: 'ᱵᱟᱝ',
  saveDraft: 'ᱰᱨᱟᱯᱷᱴ ᱥᱟᱧᱪᱟᱣ ᱢᱮ',
  notYetCompetent: 'ᱱᱤᱛᱚᱜ ᱵᱟᱝ ᱡᱚᱜᱽ ᱜᱮᱭᱟ',
  requestEvidence: 'ᱟᱨᱦᱚᱸ ᱥᱟᱹᱵᱩᱛ ᱠᱷᱚᱡᱽ ᱢᱮ',
  recommendCert: 'ᱥᱟᱠᱷᱤ ᱥᱟᱠᱟᱢ ᱞᱟᱹᱜᱤᱫ ᱥᱚᱞᱦᱟ ᱮᱢ ᱢᱮ',
  selfDeclaration: 'ᱟᱯᱱᱟᱨ ᱩᱪᱷᱟᱹᱱ',
  selfDeclarationSub: 'ᱟᱢᱟᱜ ᱦᱩᱱᱟᱹᱨ ᱵᱟᱵᱚᱛ ᱟᱢᱟᱜ ᱟᱹᱲᱟᱹ ᱛᱮ ᱞᱟᱹᱭ ᱢᱮ᱾',
  offlineReady: 'ᱚᱯᱷᱞᱟᱭᱤᱱ ᱥᱟᱯᱲᱟᱣ ᱢᱮᱱᱟᱜᱼᱟ',
  step: 'ᱫᱷᱟᱯ',
  of: 'ᱠᱷᱚᱱ',
  yourTrade: 'ᱟᱢᱟᱜ ᱠᱟᱹᱢᱤ',
  experience: 'ᱩᱭᱦᱟᱹᱨ',
  evidence: 'ᱥᱟᱹᱵᱩᱛ',
  result: 'ᱚᱨᱡᱚ',
  whatWork: 'ᱟᱢ ᱪᱮᱫ ᱠᱟᱹᱢᱤ ᱟᱢ?',
  tapPicture: 'ᱟᱢᱟᱜ ᱠᱟᱹᱢᱤ ᱥᱟᱶ ᱢᱤᱞᱚᱜ ᱠᱟᱱ ᱪᱤᱛᱟᱹᱨ ᱨᱮ ᱚᱛᱟᱭ ᱢᱮ᱾',
  tellAboutWork: 'ᱟᱢᱟᱜ ᱠᱟᱹᱢᱤ ᱵᱟᱵᱚᱛ ᱞᱟᱹᱭ ᱢᱮ',
  pressAndSpeak: 'ᱚᱛᱟᱭ ᱢᱮ ᱟᱨ ᱨᱚᱲ ᱢᱮ',
  speakAnyLang: 'ᱡᱟᱦᱟᱸᱱ ᱯᱟᱹᱨᱥᱤ ᱛᱮᱜᱮ ᱨᱚᱲ ᱢᱮ',
  listening: '🔴 ᱟᱸᱡᱚᱢ ᱮᱫᱟᱭ… ᱱᱤᱛᱚᱜ ᱨᱚᱲ ᱢᱮ',
  howManyYears: 'ᱟᱢ ᱛᱤᱱᱟᱹᱜ ᱥᱮᱨᱢᱟ ᱠᱷᱚᱱ ᱱᱚᱣᱟ ᱠᱟᱹᱢᱤ ᱮᱫᱟᱢ?',
  whatTools: 'ᱟᱢ ᱪᱮᱫ ᱦᱟᱹᱛᱤᱭᱟᱹᱨ ᱮᱢ ᱵᱮᱵᱷᱟᱨᱟ?',
  whatKindWork: 'ᱟᱢ ᱥᱟᱫᱷᱟᱨᱚᱱ ᱛᱮ ᱪᱮᱫ ᱞᱮᱠᱟᱱ ᱠᱟᱹᱢᱤ ᱟᱢ?',
  whereWork: 'ᱟᱢ ᱚᱠᱟᱨᱮ ᱠᱟᱹᱢᱤ ᱟᱢ?',
  showYourWork: 'ᱟᱢᱟᱜ ᱠᱟᱹᱢᱤ ᱩᱫᱩᱜ ᱢᱮ',
  evidenceSub: 'ᱪᱤᱛᱟᱹᱨ ᱟᱨ ᱵᱷᱤᱰᱤᱭᱳ ᱛᱮ ᱵᱤᱰᱟᱹᱣᱤᱭᱟᱹ ᱟᱢᱟᱜ ᱦᱩᱱᱟᱹᱨ ᱵᱩᱡᱷᱟᱹᱣ ᱨᱮ ᱜᱚᱲᱚᱭ ᱧᱟᱢᱟ᱾',
  takePhoto: 'ᱪᱤᱛᱟᱹᱨ ᱛᱩᱞᱟᱹᱣ ᱢᱮ',
  takePhotoSub: 'ᱟᱢᱟᱜ ᱠᱟᱹᱢᱤ ᱨᱮᱱᱟᱜ',
  recordVideo: 'ᱵᱷᱤᱰᱤᱭᱳ ᱵᱮᱱᱟᱣ ᱢᱮ',
  recordVideoSub: 'ᱢᱤᱫᱴᱟᱝ ᱠᱷᱟᱴᱚ ᱵᱷᱤᱰᱤᱭᱳ',
  uploadPaper: 'ᱠᱟᱜᱚᱡᱽ ᱟᱯᱞᱳᱰ ᱢᱮ',
  uploadPaperSub: 'ᱥᱟᱠᱷᱤ ᱥᱟᱠᱟᱢ ᱥᱮ ᱪᱤᱴᱷᱤ',
  dragFiles: 'ᱥᱮ ᱯᱷᱟᱭᱤᱞ ᱱᱚᱸᱰᱮ ᱚᱨ ᱟᱹᱜᱩᱭ ᱢᱮ',
  fileTypes: 'JPG, PNG, MP4, PDF — ᱕᱐ MB ᱦᱟᱹᱵᱤᱡ',
  offlineUpload: 'ᱟᱢ ᱱᱚᱣᱟ ᱤᱱᱴᱟᱨᱱᱮᱴ ᱵᱮᱜᱚᱨ ᱦᱚᱸ ᱠᱚᱨᱟᱣ ᱫᱟᱲᱮᱭᱟᱜᱼᱟᱢ᱾',
  offlineUploadSub: 'ᱯᱷᱟᱭᱤᱞ ᱯᱷᱳᱱ ᱨᱮ ᱛᱟᱦᱮᱸᱱᱟ ᱟᱨ ᱱᱮᱴ ᱦᱤᱡᱩᱜ ᱥᱟᱶᱛᱮ ᱟᱯᱞᱳᱰ ᱦᱩᱭᱩᱜᱼᱟ᱾',
  suggestedMatch: 'ᱥᱚᱞᱦᱟ ᱟᱠᱟᱱ ᱢᱤᱞ',
  match: 'ᱢᱤᱞ',
  humanReview: 'ᱢᱟᱹᱱᱢᱤ ᱵᱤᱰᱟᱹᱣᱤᱭᱟᱹ ᱜᱮ ᱧᱮᱞ ᱠᱟᱛᱮ ᱴᱷᱟᱹᱣᱠᱟᱹᱭᱟᱭ᱾',
  humanReviewSub: 'ᱱᱚᱣᱟ ᱫᱚ ᱠᱚᱢᱯᱤᱭᱩᱴᱟᱨ ᱨᱮᱱᱟᱜ ᱮᱛᱚᱦᱚᱵ ᱥᱚᱞᱦᱟ ᱠᱟᱱᱟ᱾ ᱥᱟᱹᱨᱤ ᱵᱤᱰᱟᱹᱣᱤᱭᱟᱹ ᱜᱮ ᱢᱩᱪᱟᱹᱫ ᱴᱷᱟᱹᱣᱠᱟᱹ ᱦᱟᱛᱟᱣᱟᱭ᱾',
  back: 'ᱛᱟᱭᱚᱢ',
  next: 'ᱞᱟᱦᱟ',
  submit: 'ᱮᱢ ᱢᱮ',
  orTypeBelow: 'ᱵᱮᱴᱚᱱ ᱚᱛᱟ ᱠᱟᱛᱮ ᱨᱚᱲ ᱢᱮ ᱥᱮ ᱞᱟᱛᱟᱨ ᱨᱮ ᱚᱞ ᱢᱮ᱾',
  electrician: 'ᱤᱞᱮᱠᱴᱨᱤᱥᱤᱭᱟᱱ',
  plumber: 'ᱯᱞᱚᱢᱵᱚᱨ',
  welder: 'ᱣᱮᱞᱰᱟᱨ',
  carpenter: 'ᱵᱟᱹᱰᱷᱟᱹᱭ',
  mason: 'ᱨᱟᱡᱽ ᱢᱤᱥᱛᱨᱤ',
  tailor: 'ᱫᱚᱨᱡᱤ',
  cook: 'ᱤᱥᱤᱱᱤᱭᱟᱹ',
  driver: 'ᱰᱨᱟᱭᱵᱷᱟᱨ',
  other: 'ᱮᱴᱟᱜ',
  performBasicWork: 'ᱢᱩᱬᱩᱛ ᱠᱟᱹᱢᱤ ᱠᱚᱨᱟᱣ',
  readDrawings: 'ᱟᱞᱜᱟ ᱱᱚᱠᱥᱟ ᱯᱟᱲᱦᱟᱣ',
  followSafety: 'ᱠᱟᱹᱢᱤ ᱴᱷᱟᱶ ᱨᱩᱠᱷᱤᱭᱟᱹ ᱱᱤᱭᱚᱢ ᱢᱟᱱᱟᱣ',
  footerDesc: 'ᱥᱢᱟᱨᱴ ᱤᱱᱰᱤᱭᱟ ᱦᱮᱠᱟᱛᱷᱚᱱ ᱨᱮ RPL ᱞᱟᱹᱜᱤᱫ AI ᱦᱩᱱᱟᱹᱨ ᱵᱤᱰᱟᱹᱣ ᱦᱟᱹᱛᱤᱭᱟᱹᱨ᱾',
  sponsoredBy: 'ᱜᱚᱲᱚᱭᱤᱭᱟᱹ',
  msdeFullName: 'ᱦᱩᱱᱟᱹᱨ ᱩᱛᱱᱟᱹᱣ ᱟᱨ ᱩᱫᱽᱭᱚᱜᱽ ᱢᱚᱱᱛᱨᱟᱲᱚᱭ (MSDE)',
  ncvetFullName: 'ᱡᱟᱹᱛᱤᱭᱟᱹᱨᱤ ᱠᱟᱹᱢᱤᱦᱚᱨᱟ ᱥᱮᱪᱮᱫ ᱟᱨ ᱥᱮᱪᱮᱫ ᱵᱟᱹᱭᱥᱤ (NCVET)',
  project: 'ᱯᱨᱚᱡᱮᱠᱴ',
  problemId: 'ᱮᱴᱠᱮᱴᱚᱬᱮ ID: SIH26242',
  themeSmartEdu: 'ᱛᱷᱤᱢ: ᱥᱢᱟᱨᱴ ᱥᱮᱪᱮᱫ',
  categorySoftware: 'ᱛᱷᱟᱠ: ᱥᱚᱯᱷᱴᱣᱮᱭᱟᱨ',
  footerCopyright: '© ᱒᱐᱒᱖ RPL AI ᱵᱤᱰᱟᱹᱣ ᱦᱟᱹᱛᱤᱭᱟᱹᱨ — ᱥᱤᱧᱚᱛ ᱨᱤᱱ ᱠᱟᱹᱢᱤᱭᱟᱹ ᱠᱚ ᱞᱟᱹᱜᱤᱫ ᱥᱟᱯᱲᱟᱣ'
};

export const mni = {
  navHome: 'ꯌꯨꯝ',
  navSelfDeclaration: 'ꯏꯁꯥꯅ ꯂꯥꯎꯊꯣꯛꯆꯕ',
  navCandidate: 'ꯀꯦꯟꯗꯤꯗꯦꯠ',
  navAssessor: 'ꯌꯦꯡꯁꯤꯅꯕ',
  govtInitiative: 'ꯚꯥꯔꯠ ꯁꯔꯀꯥꯔꯒꯤ ꯈꯣꯡꯊꯥꯡ',
  ministryName: 'ꯍꯩꯁꯤꯡꯕ ꯆꯥꯎꯈꯠꯍꯟꯕ ꯑꯃꯁꯨꯡ ꯏꯟꯇꯔꯞꯔꯤꯅꯔꯁꯤꯞ ꯃꯟꯠꯔꯥꯂꯌ',
  rplAiAssessment: 'RPL AI ꯍꯩꯁꯤꯡꯕ ꯌꯦꯡꯁꯤꯅꯕ',
  heroTitle: 'ꯅꯍꯥꯛꯀꯤ ꯍꯩꯁꯤꯡꯕꯒꯤ ꯁꯔꯀꯥꯔꯤ ꯁꯔꯇꯤꯐꯤꯀꯦꯠ ꯐꯪꯂꯨ',
  heroSub: 'ꯊꯕꯛ ꯇꯧꯗꯨꯅ ꯇꯝꯈ꯭ꯔꯕ ꯁꯤꯟꯃꯤꯁꯤꯡꯒꯤꯗꯃꯛ꯫ ꯑꯈꯟꯅꯕ ꯂꯥꯏꯔꯤꯛ ꯍꯩꯕ ꯃꯊꯧ ꯇꯥꯗꯦ꯫',
  portfolioHeroH1_1: 'ꯍꯩꯁꯤꯡꯕ ꯌꯦꯡꯁꯤꯜꯂꯨ꯫',
  portfolioHeroH1_2: 'ꯑꯣꯖꯥ ꯊꯕꯛꯄꯨ',
  portfolioHeroH1_3: ' ꯁꯥꯛꯈꯣꯡꯕ ꯄꯤꯌꯨ꯫',
  portfolioHeroH1_4: 'RPL ꯄꯥꯛꯊꯣꯛ-ꯆꯥꯎꯊꯣꯛꯄ꯫',
  startAssessment: 'ꯌꯦꯡꯁꯤꯟꯕ ꯍꯧꯔꯣ',
  assessorLogin: 'ꯌꯦꯡꯁꯤꯟꯕ ꯂꯣꯒꯏꯟ',
  makeItClear: '꯰꯱ — ꯃꯌꯦꯛ ꯁꯦꯡꯅ ꯎꯕ',
  buildShapeShip: 'ꯇꯝꯃꯨ / ꯁꯦꯝꯃꯨ / ꯃꯥꯡꯖꯤꯜ ꯊꯥꯔꯣ',
  tickerAiAssisted: 'AI-ꯃꯇꯦꯡ ꯌꯥꯎꯕ RPL',
  tickerNsqf: 'NSQF ꯃꯇꯨꯡ ꯏꯟꯅ',
  tickerHumanLoop: 'ꯃꯤꯑꯣꯏꯕꯅ ꯌꯦꯡꯁꯤꯟꯕꯒ ꯂꯣꯏꯅꯅ',
  tickerRegional: 'ꯏꯟꯗꯤꯌꯥꯒꯤ ꯂꯣꯟ ꯲꯲',
  tickerOffline: 'ꯑꯣꯐꯂꯥꯏꯟ ꯁꯤꯡꯛ ꯈꯨꯗꯣꯡꯆꯥꯕ',
  tickerMinistry: 'ꯍꯩꯁꯤꯡꯕ ꯆꯥꯎꯈꯠꯍꯟꯕ ꯃꯟꯠꯔꯥꯂꯌ',
  ourWork: 'ꯑꯩꯈꯣꯏꯒꯤ ꯊꯕꯛ',
  work1Title: 'ꯂꯥꯏꯕ ꯑꯣꯖꯥ ꯃꯦꯞꯄꯤꯡ',
  work1Desc: 'ꯁꯤꯟꯃꯤꯁꯤꯡꯅ ꯃꯁꯥꯒꯤ ꯂꯣꯟꯗ ꯍꯩꯁꯤꯡꯕ ꯐꯣꯡꯗꯣꯛꯅꯕ ꯏꯟꯇꯔꯐꯦꯁ꯫',
  work2Title: 'ꯚꯤꯗꯤꯑꯣ ꯑꯃꯁꯨꯡ ꯐꯣꯇꯣ ꯌꯦꯡꯁꯤꯟꯕ',
  work2Desc: 'ꯊꯕꯛ ꯇꯧꯕꯒꯤ ꯈꯨꯗꯝ ꯈꯣꯃꯖꯤꯟꯕ꯫',
  work3Title: 'ꯃꯒꯨꯟ ꯂꯩꯕ ꯁ꯭ꯀꯣꯔꯤꯡ',
  work3Desc: 'ꯌꯦꯡꯁꯤꯟꯕꯁꯤꯡꯒꯤꯗꯃꯛ NSQF ꯒꯤ ꯃꯇꯨꯡ ꯏꯟꯅ ꯆꯨꯝꯅ ꯁ꯭ꯀꯣꯔ ꯄꯤꯕ꯫',
  work4Title: 'ꯏꯟꯇꯔꯅꯦꯠ ꯆꯠꯇꯕꯗꯁꯨ ꯊꯕꯛ ꯇꯧꯕ',
  work4Desc: 'ꯏꯟꯇꯔꯅꯦꯠ ꯂꯩꯇ꯭ꯔꯕꯁꯨ ꯃꯆꯥꯛꯁꯤꯡ ꯐꯣꯟꯗ ꯀꯟꯗꯨꯅ ꯊꯝꯃꯤ꯫',
  tagSelfDecl: 'ꯏꯁꯥꯅ ꯂꯥꯎꯊꯣꯛꯆꯕ',
  tagAiAssist: 'AI ꯃꯇꯦꯡ',
  tagPractical: 'ꯊꯕꯛ ꯇꯧꯕ ꯈꯨꯠꯂꯥꯏ',
  tagMedia: 'ꯃꯤꯗꯤꯌꯥ ꯈꯨꯗꯝ',
  tagAssessor: 'ꯌꯦꯡꯁꯤꯟꯕꯒꯤ ꯃꯇꯦꯡ',
  tagNsqf: 'NSQF ꯃꯒꯨꯟ',
  tagOffline: 'ꯑꯣꯐꯂꯥꯏꯟ ꯊꯕꯛ',
  tagSync: 'ꯑꯣꯇꯣ ꯁꯤꯡꯛ',
  feat1Title: 'ꯅꯍꯥꯛꯀꯤ ꯊꯕꯛ ꯂꯣꯟꯗ ꯍꯥꯏꯔꯣ',
  feat1Desc: 'ꯅꯍꯥꯛꯀꯤ ꯃꯐꯝꯒꯤ ꯂꯣꯟꯗ ꯈꯣꯟꯊꯣꯛꯅ ꯍꯥꯏꯔꯨ',
  feat2Title: 'ꯅꯍꯥꯛꯀꯤ ꯊꯕꯛ ꯎꯠꯂꯨ',
  feat2Desc: 'ꯐꯣꯇꯣ, ꯚꯤꯗꯤꯑꯣ ꯑꯃꯁꯨꯡ ꯊꯕꯛꯀꯤ ꯈꯨꯗꯝ ꯂꯥꯏꯅ ꯑꯄꯂꯣꯗ ꯇꯧ',
  feat3Title: 'NSQF ꯒ ꯆꯨꯅꯁꯤꯟꯕ',
  feat3Desc: 'AI ꯅ ꯅꯍꯥꯛꯀꯤ ꯍꯩꯁꯤꯡꯕ ꯂꯩꯕꯥꯛꯀꯤ ꯃꯒꯨꯟꯒ ꯄꯨꯟꯁꯤꯜꯂꯤ',
  feat4Title: 'ꯌꯦꯡꯁꯤꯟꯕꯅ ꯋꯥꯔꯦꯞ ꯂꯧꯕ',
  feat4Desc: 'AI ꯅ ꯄꯥꯎꯇꯥꯛ ꯄꯤ, ꯁꯔꯇꯤꯐꯥꯏꯗ ꯑꯦꯛꯁꯄꯔꯠꯅ ꯑꯔꯣꯏꯕ ꯋꯥꯔꯦꯞ ꯂꯧꯏ',
  howItWorks: 'ꯃꯁꯤꯅ ꯀꯔꯝꯅ ꯊꯕꯛ ꯇꯧꯕꯒꯦ',
  howItWorksSub: 'ꯂꯥꯏꯔꯕ ꯈꯣꯡꯊꯥꯡ  অহꯨꯝ꯫ ꯀꯟꯅ ꯆꯠꯊꯕ ꯄꯔꯤꯛꯁꯥ ꯂꯩꯇꯦ꯫',
  step1Title: 'ꯅꯍꯥꯛꯀꯤ ꯃꯇꯥꯡꯗ ꯍꯥꯏꯔꯨ',
  step1Desc: 'ꯅꯍꯥꯛꯀꯤ ꯊꯕꯛ ꯈꯟꯂꯨ꯫ ꯀꯔꯤᱜꯨꯝꯕ ꯂꯣꯟ ꯑꯃꯗ ꯅꯍꯥꯛꯀꯤ ꯊꯕꯛꯀꯤ ꯃꯔꯝꯗ ꯉꯥꯡꯎ꯫',
  step2Title: 'ꯅꯍꯥꯛꯀꯤ ꯊꯕꯛ ꯎꯠꯂꯨ',
  step2Desc: 'ꯅꯍꯥꯛꯅ ꯁꯦꯝꯈ꯭ꯔꯕ ꯄꯣꯠꯁꯤꯡꯒꯤ ꯐꯣꯇꯣ ꯅꯝꯃꯨ ꯅꯠꯇ꯭ꯔꯒ ꯇꯦꯟꯕ ꯚꯤꯗꯤꯑꯣ ꯁꯦꯝꯃꯨ꯫',
  step3Title: 'ꯁꯔꯇꯤꯐꯤꯀꯦꯠ ꯐꯪꯂꯨ',
  step3Desc: 'AI ꯅ ꯍꯩꯁꯤꯡꯕ ꯌꯦꯡꯁꯤꯜꯂꯤ ꯑꯃꯁꯨꯡ ꯌꯦꯡꯁꯤꯟꯕꯅ ꯂꯩꯕꯥꯛꯀꯤ ꯁꯔꯇꯤꯐꯤꯀꯦꯠ ꯄꯤ꯫',
  ctaBannerTitlePortfolio: 'ꯏꯟꯗꯤꯌꯥꯒꯤ ꯍꯩꯊꯣꯏꯕ ꯁꯤꯟꯃꯤꯁꯤꯡꯗ ꯁꯔꯀꯥꯔꯤ ꯁꯥꯛꯈꯣꯡꯕ ꯄꯤꯌꯨ꯫',
  ctaBannerTitleGovt: 'ꯏꯟꯗꯤꯌꯥꯒꯤ ꯁꯤꯟꯃꯤꯁꯤꯡꯗ ꯍꯩꯁꯤꯡꯕ ꯂꯩ꯫ ꯂꯥꯛꯎ ꯃꯁꯤꯕꯨ ꯁꯥꯛꯈꯣꯡꯕ ꯄꯤꯔꯁꯤ꯫',
  ctaBannerSub: 'ꯑꯅꯑꯣꯔꯒꯥꯅꯥꯏꯖ꯭ꯗ ꯁꯤꯟꯃꯤꯁꯤꯡꯒꯤꯗꯃꯛ ꯈꯨꯗꯣꯡꯆꯥꯅ ꯁꯦꯝꯕ꯫',
  beginSelfDeclaration: 'ꯏꯁꯥꯅ ꯂꯥꯎꯊꯣꯛꯆꯕ ꯍꯧꯔꯣ',
  welcomeCandidate: 'ꯇꯔꯥꯝꯅ ꯑꯣꯛꯆꯔꯤ, ꯔꯃꯦꯁ 👋',
  candidateId: 'ꯀꯦꯟꯗꯤꯗꯦꯠ ID: RPL-2024-8842',
  allSynced: 'ꯄꯨꯝꯅꯃꯛ ꯁꯤꯡꯛ ꯇꯧꯔꯦ',
  newDeclaration: 'ꯑꯅꯧꯕ ꯂꯥꯎꯊꯣꯛꯄ',
  newDeclarationSub: 'ꯑꯅꯧꯕ ꯍꯩꯁꯤꯡꯕ ꯃꯦꯞꯄꯤꯡ ꯍꯧꯔꯣ',
  uploadEvidence: 'ꯈꯨꯗꯝ ꯑꯄꯂꯣꯗ ꯇꯧ',
  uploadEvidenceSub: 'ꯐꯣꯇꯣ ꯅꯠꯇ꯭ꯔꯒ ꯚꯤꯗꯤꯑꯣ ꯍꯥꯞꯆꯤꯜꯂꯨ',
  viewCertificate: 'ꯁꯔꯇꯤꯐꯤꯀꯦꯠ ꯌꯦꯡꯉꯨ',
  viewCertificateSub: 'ꯅꯍꯥꯛꯀꯤ NSQF ꯁꯔꯇꯤꯐꯤꯀꯦꯠ ꯗꯥꯎꯟꯂꯣꯗ ꯇꯧ',
  yourApplications: 'ꯅꯍꯥꯛꯀꯤ ꯑꯄ꯭ꯂꯤꯀꯦꯁꯟꯁꯤꯡ',
  underReview: 'ꯌꯦꯡꯁꯤꯜꯂꯤ',
  needMoreInfo: 'ꯑꯍꯦꯟꯕ ꯄꯥꯎ ꯃꯊꯧ ꯇꯥꯏ',
  certified: 'ꯁꯥꯛꯈꯣꯡꯈ꯭ꯔꯦ',
  nsqfLevel: 'NSQF ꯊꯥꯛ',
  submittedAgo: 'ꯅꯨꯃꯤꯠ ꯲ ꯒꯤ ꯃꯃꯥꯡꯗ ꯄꯤꯁꯤꯟꯈꯤꯕ',
  assessorReviewing: 'ꯌꯦꯡꯁꯤꯟꯕꯅ ꯅꯍꯥꯛꯀꯤ ꯈꯨꯗꯝꯁꯤꯡ ꯌꯦꯡꯂꯤ…',
  needClearerVideo: 'ꯋꯥꯌꯔꯤꯡ ꯏꯉꯥꯎ-ꯁꯉꯥꯎ ꯌꯦꯡꯕꯒꯤ ꯃꯌꯦꯛ ꯁꯦꯡꯕ ꯚꯤꯗꯤꯑꯣ ꯃꯊꯧ ꯇꯥꯏ꯫',
  details: 'ꯑꯀꯨꯞꯄ ꯃꯔꯣꯜ',
  uploadNow: 'ꯍꯧꯖꯤꯛ ꯑꯄꯂꯣꯗ ꯇꯧ',
  downloadPdf: 'PDF ꯗꯥꯎꯟꯂꯣꯗ ꯇꯧ',
  worksWithoutInternet: 'ꯏꯟꯇꯔꯅꯦꯠ ꯌꯥꯎꯗꯅꯁꯨ ꯊꯕꯛ ꯇꯧꯏ',
  worksWithoutInternetSub: 'ꯏꯟꯇꯔꯅꯦꯠ ꯂꯩꯇ꯭ꯔꯕꯁꯨ ꯑꯄ꯭ꯂꯤꯀꯦꯁꯟ ꯌꯦꯡꯎ ꯑꯃꯁꯨꯡ ꯁꯦꯝꯃꯨ꯫ ꯑꯣꯟꯂꯥꯏꯟ ꯑꯣꯏꯔꯛꯄꯗ ꯃꯁꯥꯃꯊꯟꯇ ꯁꯤꯡꯛ ꯑꯣꯏꯒꯅꯤ꯫',
  pendingReview: 'ꯌꯦꯡꯁꯤꯟꯅꯕ ꯉꯥꯏꯔꯤ',
  searchCandidate: 'ꯀꯦꯟꯗꯤꯗꯦꯠ ꯊꯤꯔꯣ…',
  aiDisclaimer: 'AI ꯅ ꯄꯥꯎꯇꯥꯛ ꯈꯛꯇꯃꯛ ꯄꯤ꯫ ꯑꯔꯣꯏꯕ ꯋꯥꯔꯦꯞꯇꯤ ꯃꯤꯑꯣꯏꯕ ꯌꯦꯡꯁꯤꯟꯕꯒꯤꯅꯤ꯫',
  photos: 'ꯐꯣꯇꯣꯁꯤꯡ',
  video: 'ꯚꯤꯗꯤꯑꯣ',
  aiSuggestion: 'AI ꯄꯥꯎꯇꯥꯛ',
  competent: 'ꯍꯩꯊꯣꯏ-ꯁꯤꯡꯊꯣꯏꯕ',
  needsReview: 'ꯑꯃꯨꯛ ꯍꯟꯅ ꯌꯦꯡꯕ ꯃꯊꯧ ꯇꯥꯏ',
  lowMatch: 'ꯆꯨꯅꯕ ꯍꯟꯊꯕ',
  yes: 'ꯍꯣꯏ',
  partial: 'ꯈꯔꯥ',
  no: 'ꯅꯠꯇꯦ',
  saveDraft: 'ꯗ꯭ꯔꯥꯐꯠ ꯊꯝꯃꯨ',
  notYetCompetent: 'ꯍꯧꯖꯤꯛ ꯃꯄꯨꯡ ꯐꯥꯗ꯭ꯔꯤ',
  requestEvidence: 'ꯑꯍꯦꯟꯕ ꯈꯨꯗꯝ ꯇꯛꯁꯤꯜꯂꯨ',
  recommendCert: 'ꯁꯔꯇꯤꯐꯤꯀꯦꯠ ꯄꯤꯅꯕ ꯄꯥꯎꯇꯥꯛ ꯄꯤꯌꯨ',
  selfDeclaration: 'ꯏꯁꯥꯅ ꯂꯥꯎꯊꯣꯛꯆꯕ',
  selfDeclarationSub: 'ꯅꯍꯥꯛꯀꯤ ꯍꯩꯁꯤꯡꯕꯒꯤ ꯃꯇꯥꯡꯗ ꯅꯍꯥꯛꯀꯤ ꯋꯥꯍꯩꯗ ꯍꯥꯏꯔꯨ꯫',
  offlineReady: 'ꯑꯣꯐꯂꯥꯏꯟ ꯁꯦꯝ-ꯁꯥꯔꯦ',
  step: 'ꯈꯣꯡꯊꯥꯡ',
  of: 'ꯒꯤ',
  yourTrade: 'ꯅꯍꯥꯛꯀꯤ ꯊꯕꯛ',
  experience: 'ꯑꯣꯖꯥ ꯊꯕꯛ',
  evidence: 'ꯈꯨꯗꯝ',
  result: 'ꯃꯍꯩ',
  whatWork: 'ꯅꯍꯥꯛꯅ ꯀꯔꯤ ꯊꯕꯛ ꯇꯧꯔꯤꯕগে?',
  tapPicture: 'ꯅꯍꯥꯛꯀꯤ ꯊꯕꯛꯀ ꯆꯨꯅꯕ ꯐꯣꯇꯣꯗ ꯅꯝꯃꯨ꯫',
  tellAboutWork: 'ꯅꯍꯥꯛꯀꯤ ꯊꯕꯛꯀꯤ ꯃꯇꯥꯡꯗ ꯍꯥꯏꯔꯨ',
  pressAndSpeak: 'ꯅꯝꯃꯨ ꯑꯃꯁꯨꯡ ꯉꯥꯡꯎ',
  speakAnyLang: 'ꯀꯔꯤᱜꯨꯝꯕ ꯂꯣꯟꯗ ꯉꯥꯡꯎ',
  listening: '🔴 ꯇꯥꯔꯤ… ꯍꯧꯖꯤꯛ ꯉꯥꯡꯎ',
  howManyYears: 'ꯅꯍꯥꯛꯅ ꯆꯍꯤ ꯀꯌꯥ ꯊꯕꯛ ꯑꯁꯤ ꯇꯧꯔꯛꯂꯕগে?',
  whatTools: 'ꯅꯍꯥꯛꯅ ꯀꯔꯤ ꯈꯨꯠꯂꯥꯏꯁꯤꯡ ꯁꯤꯖꯤꯟꯅꯔꯤꯕগে?',
  whatKindWork: 'ꯇꯣꯏꯅ ꯅꯍꯥꯛꯅ ꯀꯔꯤ ꯃꯈꯜꯒꯤ ꯊꯕꯛ ꯇꯧꯔꯤꯕগে?',
  whereWork: 'ꯅꯍꯥꯛꯅ ꯀꯗꯥꯏꯗ ꯊꯕꯛ ꯇꯧꯔꯤꯕগে?',
  showYourWork: 'ꯅꯍꯥꯛꯀꯤ ꯊꯕꯛ ꯎꯠꯂꯨ',
  evidenceSub: 'ꯐꯣꯇꯣ ꯑꯃꯁꯨꯡ ꯚꯤꯗꯤꯑꯣꯅ ꯌꯦꯡꯁꯤꯟꯕꯗ ꯅꯍꯥꯛꯀꯤ ꯍꯩꯁꯤꯡꯕ ꯈꯪꯕꯗ ꯃꯇꯦꯡ ꯑꯣꯏ꯫',
  takePhoto: 'ꯐꯣꯇꯣ ꯅꯝꯃꯨ',
  takePhotoSub: 'ꯅꯍꯥꯛꯀꯤ ꯊꯕꯛꯀꯤ',
  recordVideo: 'ꯚꯤꯗꯤꯑꯣ ꯁꯦꯝꯃꯨ',
  recordVideoSub: 'ꯇꯦꯟꯕ ꯚꯤꯗꯤꯑꯣ ꯑꯃ',
  uploadPaper: 'ꯆꯦ-ꯆꯥꯡ ꯑꯄꯂꯣꯗ ꯇꯧ',
  uploadPaperSub: 'ꯁꯔꯇꯤꯐꯤꯀꯦꯠ ꯅꯠꯇ꯭ꯔꯒ ꯆꯤꯊꯤ',
  dragFiles: 'ꯅꯠꯇ꯭ꯔꯒ ꯐꯥꯏꯜꯁꯤꯡ ꯃꯐꯝꯁꯤꯗ ꯆꯤꯡꯁꯤꯜꯂꯨ',
  fileTypes: 'JPG, PNG, MP4, PDF — 50 MB ꯐꯥꯎꯕ',
  offlineUpload: 'ꯏꯟꯇꯔꯅꯦꯠ ꯂꯩꯇ꯭ꯔꯕꯁꯨ ꯇꯧꯕ ꯌꯥꯏ꯫',
  offlineUploadSub: 'ꯐꯥꯏꯜꯁꯤꯡ ꯐꯣꯟꯗ ꯂꯩꯍꯧꯒꯅꯤ ꯑꯃꯁꯨꯡ ꯅꯦꯠ ꯌꯧꯔꯛꯄꯗ ꯑꯄꯂꯣꯗ ꯑꯣꯏꯒꯅꯤ꯫',
  suggestedMatch: 'ꯄꯥꯎꯇꯥꯛ ꯄꯤꯔꯕ ꯆꯨꯅꯕ',
  match: 'ꯆꯨꯅꯕ',
  humanReview: 'ꯃꯤꯑꯣꯏꯕ ꯌꯦꯡꯁꯤꯟꯕꯅ ꯌꯦꯡꯂꯒ ꯋꯥꯔꯦꯞ ꯂꯧꯒꯅꯤ꯫',
  humanReviewSub: 'ꯃꯁꯤ ꯀꯝꯄ꯭ꯌꯨꯇꯔꯒꯤ ꯑꯍꯥꯟꯕ ꯄꯥꯎꯇꯥꯛꯅꯤ꯫ ꯁꯔꯇꯤꯐꯥꯏꯗ ꯑꯦꯛꯁꯄꯔꯠꯅ ꯑꯔꯣꯏꯕ ꯋꯥꯔꯦꯞ ꯂꯧꯒꯅꯤ꯫',
  back: 'ꯃꯇꯨꯡ',
  next: 'ꯃꯥꯡ',
  submit: 'ꯄꯤꯁꯤꯜꯂꯨ',
  orTypeBelow: 'ꯕꯇꯟ ꯅꯝꯃꯨ ꯑꯃꯁꯨꯡ ꯉꯥꯡꯎ ꯅꯠꯇ꯭ꯔꯒ ꯃꯈꯥꯗ ꯏꯌꯨ꯫',
  electrician: 'ꯏꯂꯦꯛꯇ꯭ꯔꯤꯁꯤꯌꯥꯟ',
  plumber: 'ꯄ꯭ꯂꯝꯕꯔ',
  welder: 'ꯋꯦꯜꯗꯔ',
  carpenter: 'ꯎ-ꯁꯨꯕ (ꯀꯥꯔꯄꯦꯟꯇꯔ)',
  mason: 'ꯌꯨꯝ ꯁꯥꯕ ꯃꯤꯁ꯭ꯇ꯭ꯔꯤ',
  tailor: 'ꯐꯤ ꯁꯥꯕ (ꯇꯦꯂꯔ)',
  cook: 'ꯆꯥꯛ-ꯊꯣꯡꯕ',
  driver: 'ꯒꯥꯔꯤ ꯊꯧꯕ',
  other: 'ꯑꯇꯣꯞꯄ',
  performBasicWork: 'ꯃꯔꯨꯑꯣꯏꯕ ꯊꯕꯛ ꯇꯧꯕ',
  readDrawings: 'ꯂꯥꯏꯔꯕ ꯅꯛꯁꯥ ꯄꯥꯕ',
  followSafety: 'ꯊꯕꯛ ꯃꯐꯝꯒꯤ ꯉꯥꯛ-ꯁꯦꯟ ꯆꯠꯅ-ꯀꯥꯡꯂꯣꯟ ꯉꯥꯛꯄ',
  footerDesc: 'ꯁ꯭ꯃꯥꯔꯠ ꯏꯟꯗꯤꯌꯥ ꯍꯦꯀꯥꯊꯣꯟꯒꯤ ꯃꯈꯥꯗ RPL ꯒꯤꯗꯃꯛ AI ꯍꯩꯁꯤꯡꯕ ꯌꯦꯡꯁꯤꯟꯕ ꯈꯨꯠꯂꯥꯏ꯫',
  sponsoredBy: 'ꯁ꯭ꯄꯣꯟꯁꯔ',
  msdeFullName: 'ꯍꯩꯁꯤꯡꯕ ꯆꯥꯎꯈꯠꯍꯟꯕ ꯑꯃꯁꯨꯡ ꯏꯟꯇꯔꯞꯔꯤꯅꯔꯁꯤꯞ ꯃꯟꯠꯔꯥꯂꯌ (MSDE)',
  ncvetFullName: 'ꯂꯩꯕꯥꯛꯀꯤ ꯊꯕꯛ ꯇꯝꯕ ꯑꯃꯁꯨꯡ ꯇ꯭ꯔꯦꯅꯤꯡ ꯀꯥꯎꯟꯁꯤꯜ (NCVET)',
  project: 'ꯄ꯭ꯔꯣꯖꯦꯛ꯭ꯇ',
  problemId: 'ꯋꯥꯐꯝ ID: SIH26242',
  themeSmartEdu: 'ꯊꯤꯝ: ꯁ꯭ꯃꯥꯔꯠ ꯂꯥꯏꯔꯤꯛ ꯇꯝꯕ',
  categorySoftware: 'ꯃꯈꯜ: ꯁꯣꯐ꯭ꯇꯋꯦꯌꯥꯔ',
  footerCopyright: '© ꯲꯰꯲꯶ RPL AI ꯌꯦꯡꯁꯤꯟꯕ ꯈꯨꯠꯂꯥꯏ — ꯏꯟꯗꯤꯌꯥꯒꯤ ꯍꯩꯊꯣꯏꯕ ꯁꯤꯟꯃꯤꯁꯤꯡꯒꯤꯗꯃꯛ ꯁꯦꯝꯕ'
};
