export const ur = {
  navHome: 'ہوم',
  navSelfDeclaration: 'خود توثیق',
  navCandidate: 'امیدوار',
  navAssessor: 'جانچ کنندہ',
  govtInitiative: 'حکومت ہند کی پیش قدمی',
  ministryName: 'وزارت برائے فروغ ہنر و صنعت کاری',
  rplAiAssessment: 'آر پی ایل اے آئی مہارت کی جانچ',
  heroTitle: 'اپنی صلاحیتوں کا سرکاری سرٹیفکیٹ حاصل کریں',
  heroSub: 'کام کے دوران سیکھنے والے کاریگروں کے لیے۔ کسی رسمی تعلیم کی ضرورت نہیں۔',
  portfolioHeroH1_1: 'مہارت پرکھیں۔',
  portfolioHeroH1_2: 'تجربے کی',
  portfolioHeroH1_3: ' توثیق کریں۔',
  portfolioHeroH1_4: 'آر پی ایل کی وسعت۔',
  startAssessment: 'جانچ شروع کریں',
  assessorLogin: 'جانچ کنندہ لاگ ان',
  makeItClear: '۰۱ — واضح اور شفاف',
  buildShapeShip: 'سیکھیں / بنائیں / آگے بڑھیں',
  tickerAiAssisted: 'اے آئی معاونت یافتہ RPL',
  tickerNsqf: 'NSQF کے مطابق',
  tickerHumanLoop: 'انسانی تصدیق کے ساتھ',
  tickerRegional: '۲۲ ہندوستانی زبانیں',
  tickerOffline: 'آف لائن مطابقت پذیری',
  tickerMinistry: 'وزارت برائے فروغ ہنر',
  ourWork: 'ہمارا کام',
  work1Title: 'آسان تجرباتی نقشہ سازی',
  work1Desc: 'کاریگروں کے لیے اپنی مادری زبان میں مہارت بیان کرنے کا مکالماتی انٹرفیس۔',
  work2Title: 'ویڈیو اور تصویری جانچ',
  work2Desc: 'عملی کام کی پیمائش کے لیے بصری شواہد کا باآسانی اندراج۔',
  work3Title: 'معیاری اسکورنگ',
  work3Desc: 'جانچ کنندگان کے لیے NSQF معیارات کے مطابق درست نمبرات کا نظام۔',
  work4Title: 'کم انٹرنیٹ میں بھی کارآمد',
  work4Desc: 'انٹرنیٹ نہ ہونے پر بھی معلومات فون میں محفوظ رہتی ہیں۔',
  tagSelfDecl: 'خود توثیق',
  tagAiAssist: 'اے آئی معاونت',
  tagPractical: 'عملی طریقہ',
  tagMedia: 'میڈیا ثبوت',
  tagAssessor: 'جانچ کنندہ معاونت',
  tagNsqf: 'NSQF معیارات',
  tagOffline: 'آف لائن فعال',
  tagSync: 'خودکار سنک',
  feat1Title: 'اپنے تجربے کو بول کر بتائیں',
  feat1Desc: 'اپنی مادری زبان میں صوتی ان پٹ کا استعمال کریں',
  feat2Title: 'اپنا کام دکھائیں',
  feat2Desc: 'تصاویر، ویڈیوز اور کام کے ثبوت باآسانی اپ لوڈ کریں',
  feat3Title: 'NSQF کے ساتھ مطابقت',
  feat3Desc: 'اے آئی آپ کی عملی صلاحیتوں کو قومی معیارات سے جوڑتا ہے',
  feat4Title: 'ماہر جانچ کنندہ کا فیصلہ',
  feat4Desc: 'اے آئی تجویز کرتا ہے، مصدقہ ماہر حتمی فیصلہ لیتا ہے',
  howItWorks: 'یہ کیسے کام کرتا ہے',
  howItWorksSub: 'تین آسان مراحل۔ کوئی مشکل امتحان یا طویل فارم نہیں۔',
  step1Title: 'اپنے بارے میں بتائیں',
  step1Desc: 'اپنا پیشہ منتخب کریں۔ کسی بھی زبان میں اپنے تجربے کے بارے میں بولیں۔',
  step2Title: 'اپنا کام دکھائیں',
  step2Desc: 'اپنے بنائے ہوئے کام کی تصاویر لیں یا ایک مختصر ویڈیو بنائیں۔',
  step3Title: 'سرٹیفکیٹ حاصل کریں',
  step3Desc: 'اے آئی مہارت کی جانچ کرتا ہے اور بااختیار جانچ کنندہ قومی سرٹیفکیٹ جاری کرتا ہے۔',
  ctaBannerTitlePortfolio: 'ہندوستان کے ہنر مند ہاتھوں کو دیں سرکاری شناخت۔',
  ctaBannerTitleGovt: 'ہندوستان کے کارکنوں کے پاس ہنر ہے۔ آئیے اس کی تصدیق کریں۔',
  ctaBannerSub: 'غیر منظم شعبے کے کارکنوں کے لیے خصوصی طور پر تیار کردہ۔',
  beginSelfDeclaration: 'خود توثیق شروع کریں',
  welcomeCandidate: 'خوش آمدید، رمیش 👋',
  candidateId: 'امیدوار کا شناختی نمبر: RPL-2024-8842',
  allSynced: 'تمام ڈیٹا سنک ہو گیا',
  newDeclaration: 'نئی توثیق',
  newDeclarationSub: 'نئی مہارت کی جانچ شروع کریں',
  uploadEvidence: 'ثبوت اپ لوڈ کریں',
  uploadEvidenceSub: 'تصاویر یا ویڈیو شامل کریں',
  viewCertificate: 'سرٹیفکیٹ دیکھیں',
  viewCertificateSub: 'اپنا NSQF سرٹیفکیٹ ڈاؤن لوڈ کریں',
  yourApplications: 'آپ کی درخواستیں',
  underReview: 'زیرِ جائزہ',
  needMoreInfo: 'مزید معلومات درکار ہیں',
  certified: 'تصدیق شدہ (سرٹیفائیڈ)',
  nsqfLevel: 'NSQF درجہ',
  submittedAgo: '۲ دن پہلے جمع کرایا گیا',
  assessorReviewing: 'جانچ کنندہ آپ کے ثبوت کا معائنہ کر رہا ہے…',
  needClearerVideo: 'وائرنگ سیفٹی چیک کی مزید واضح ویڈیو درکار ہے۔',
  details: 'تفصیلات',
  uploadNow: 'ابھی اپ لوڈ کریں',
  downloadPdf: 'پی ڈی ایف ڈاؤن لوڈ کریں',
  worksWithoutInternet: 'انٹرنیٹ کے بغیر بھی کام کرتا ہے',
  worksWithoutInternetSub: 'انٹرنیٹ کے بغیر بھی درخواستیں دیکھیں اور بنائیں۔ آن لائن ہونے پر خودکار طور پر سنک ہو جائے گا۔',
  pendingReview: 'جائزہ کے لیے زیر التواء',
  searchCandidate: 'امیدوار تلاش کریں…',
  aiDisclaimer: 'اے آئی صرف رہنمائی کرتا ہے۔ حتمی فیصلہ انسانی جانچ کنندہ کا ہی ہوتا ہے۔',
  photos: 'تصاویر',
  video: 'ویڈیو',
  aiSuggestion: 'اے آئی تجویز',
  competent: 'اہل (ماہر)',
  needsReview: 'نظرثانی درکار ہے',
  lowMatch: 'کم مطابقت',
  yes: 'ہاں',
  partial: 'جزوی',
  no: 'نہیں',
  saveDraft: 'ڈرافٹ محفوظ کریں',
  notYetCompetent: 'ابھی مکمل اہل نہیں',
  requestEvidence: 'مزید ثبوت طلب کریں',
  recommendCert: 'سرٹیفکیٹ کی سفارش کریں',
  selfDeclaration: 'خود توثیق',
  selfDeclarationSub: 'اپنی مہارت کے بارے میں بتائیں — اپنے الفاظ میں۔',
  offlineReady: 'آف لائن تیار',
  step: 'مرحلہ',
  of: 'از',
  yourTrade: 'آپ کا پیشہ',
  experience: 'تجربہ',
  evidence: 'ثبوت',
  result: 'نتیجہ',
  whatWork: 'آپ کیا کام کرتے ہیں؟',
  tapPicture: 'اپنے کام سے مطابقت رکھنے والی تصویر پر کلک کریں۔',
  tellAboutWork: 'اپنے کام کی تفصیل بتائیں',
  pressAndSpeak: 'دبائیں اور بولیں',
  speakAnyLang: 'کسی بھی زبان میں بولیں',
  listening: '🔴 سن رہا ہے… اب بولیں',
  howManyYears: 'آپ کتنے سالوں سے یہ کام کر رہے ہیں؟',
  whatTools: 'آپ کون سے اوزار استعمال کرتے ہیں؟',
  whatKindWork: 'عام طور پر آپ کس طرح کا کام کرتے ہیں؟',
  whereWork: 'آپ کہاں کام کرتے ہیں؟',
  showYourWork: 'اپنا کام دکھائیں',
  evidenceSub: 'تصاویر اور ویڈیوز جانچ کنندہ کو آپ کی مہارت سمجھنے میں مدد دیتے ہیں۔',
  takePhoto: 'تصویر لیں',
  takePhotoSub: 'اپنے کام کی',
  recordVideo: 'ویڈیو بنائیں',
  recordVideoSub: 'ایک مختصر کلپ',
  uploadPaper: 'دستاویز اپ لوڈ کریں',
  uploadPaperSub: 'سرٹیفکیٹ یا تجربے کا خط',
  dragFiles: 'یا فائلیں یہاں کھینچ کر لائیں',
  fileTypes: 'JPG, PNG, MP4, PDF — ۵۰ MB تک',
  offlineUpload: 'آپ یہ انٹرنیٹ کے بغیر بھی کر سکتے ہیں۔',
  offlineUploadSub: 'فائلیں آپ کے فون میں محفوظ رہیں گی اور نیٹ آنے پر اپ لوڈ ہوں گی۔',
  suggestedMatch: 'تجویز کردہ مطابقت',
  match: 'مطابقت',
  humanReview: 'انسانی جانچ کنندہ تصدیق کر کے فیصلہ کرے گا۔',
  humanReviewSub: 'یہ کمپیوٹر کی ابتدائی تجویز ہے۔ سند یافتہ جانچ کنندہ ثبوت دیکھ کر حتمی فیصلہ کرے گا۔',
  back: 'پیچھے',
  next: 'آگے',
  submit: 'جمع کرائیں',
  orTypeBelow: 'بٹن دبا کر بولیں یا نیچے تحریر کریں۔',
  electrician: 'الیکٹریشن',
  plumber: 'پلمبر',
  welder: 'ویلڈر',
  carpenter: 'بڑھئی',
  mason: 'راج مزدور (معمار)',
  tailor: 'درزی',
  cook: 'باورچی',
  driver: 'ڈرائیور',
  other: 'دیگر',
  performBasicWork: 'بنیادی تکنیکی کام انجام دینا',
  readDrawings: 'سادہ نقشے یا ڈرائنگ پڑھنا',
  followSafety: 'ورکشاپ کے حفاظتی اصولوں پر عمل کرنا',
  footerDesc: 'سمارٹ انڈیا ہیکاتھون کے تحت سابقہ تعلیم و تجربے کے اعتراف (RPL) کے لیے اے آئی کی مدد سے مہارت کی جانچ کا ٹول۔',
  sponsoredBy: 'سرپرست ادارے',
  msdeFullName: 'وزارت برائے فروغ ہنر و صنعت کاری (MSDE)',
  ncvetFullName: 'نیشنل کونسل فار ووکیشنل ایجوکیشن اینڈ ٹریننگ (NCVET)',
  project: 'منصوبہ',
  problemId: 'مسئلہ کوڈ: SIH26242',
  themeSmartEdu: 'تھیم: اسمارٹ تعلیم',
  categorySoftware: 'زمرہ: سافٹ ویئر',
  footerCopyright: '© ۲۰۲۶ آر پی ایل اے آئی جانچ ٹول — ہندوستان کے ہنر مند کاریگروں کے لیے مخصوص'
};

export const ks = {
  navHome: 'ہوم',
  navSelfDeclaration: 'پَنٕنؠ جانچ',
  navCandidate: 'امیدوار',
  navAssessor: 'جانچ کرن وول',
  govtInitiative: 'حکومتِ ہندُک اَکھ قَدم',
  ministryName: 'وزارتِ ہنرمندی و صنعت کاری',
  rplAiAssessment: 'RPL AI ہُنَر جانچ',
  heroTitle: 'پَننِس ہُنرَس حٲصل کٔریو سَرکٲری سَنَد',
  heroSub: 'کٲمؠ کٔرِتھ ہؠچھَن والؠن کھٲترٕ۔ کانٛہہ رَسمی پٔرَن لٲزمی نہٕ۔',
  portfolioHeroH1_1: 'ہُنَر پرکھِو۔',
  portfolioHeroH1_2: 'تجربَس',
  portfolioHeroH1_3: ' سند دیِو۔',
  portfolioHeroH1_4: 'RPL وسعت۔',
  startAssessment: 'جانچ کٔریو شۆروٗع',
  assessorLogin: 'جانچ کَرَن وٲلؠ سُنٛد لاگ اِن',
  makeItClear: '۰۱ — صاف تہٕ پٲدَر',
  buildShapeShip: 'ہؠچھِو / بنٲوِو / بَڑِھو',
  tickerAiAssisted: 'AI معاونت یافتہ RPL',
  tickerNsqf: 'NSQF مُطٲبِق',
  tickerHumanLoop: 'اِنسٲنی نِگرٲنی سٕتی',
  tickerRegional: '۲۲ ہِندوستٲنؠ زَبانہٕ',
  tickerOffline: 'آف لائن سِنک سَہوٗلِیَتھ',
  tickerMinistry: 'وزارتِ ہنرمندی',
  ourWork: 'سون کٲم',
  work1Title: 'سَہَل تَجرباتی نقشہٕ',
  work1Desc: 'کٲم کرن والؠن پَننہِ زَبانہِ مَنٛز ہُنَر وَننہٕ خٲطرٕ مکالمٲتی انٹرفیس۔',
  work2Title: 'ویڈیو تہٕ فۆٹو جانچ',
  work2Desc: 'عملی کٲمؠ ہٕنٛدی جانچ خٲطرٕ ویڈیو ثبوت۔',
  work3Title: 'معیٲری سکورِنٛگ',
  work3Desc: 'NSQF معیاراتن مُطٲبِق نَمبَر دِنُک نِظام۔',
  work4Title: 'کم اِنٹرنیٹس پؠٹھ تہِ کارآمد',
  work4Desc: 'انٹرنیٹ وَرٲے تہِ معلوٗمات فونَس مَنٛز مَحفوٗظ۔',
  tagSelfDecl: 'پَنٕنؠ جانچ',
  tagAiAssist: 'AI مَدَتھ',
  tagPractical: 'عملی مَدَتھ',
  tagMedia: 'میڈیا ثبوٗت',
  tagAssessor: 'جانچ مَدَتھ',
  tagNsqf: 'NSQF معیارات',
  tagOffline: 'آف لائن تَیار',
  tagSync: 'آٹو سِنک',
  feat1Title: 'پَنُن تَجرُبہٕ کٔریو بَیان',
  feat1Desc: 'پَننہِ علاقٲیی زَبانہِ مَنٛز کَتھ کٔرِتھ مَعلوٗمات دیِو',
  feat2Title: 'پَنُن کٲم ہٲویو',
  feat2Desc: 'فۆٹو، ویڈیو تہٕ کٲمؠ ہٕنٛد ثبوٗت سَہلِیَتھ سٕتی اپلوڈ کٔریو',
  feat3Title: 'NSQF سٕتی جوڑُن',
  feat3Desc: 'AI چھُ تُہنٛدی عملی ہُنر قومی معیاراتن سٕتی جوڈان',
  feat4Title: 'اِنسٲنی جانچ کَرَن وٲلؠ سُنٛد فَیصلہٕ',
  feat4Desc: 'AI چھُ مَشوَرَہ دِوان، ماہر جانچ کَرَن وول چھُ حَتمی فَیصلہٕ کران',
  howItWorks: 'یہِ کِتھ پٲٹھؠ چھُ کٲم کَران',
  howItWorksSub: 'ترے سَہَل مَراحِل۔ کانٛہہ مُشکِل اِمتِحان نہٕ۔',
  step1Title: 'پَننِس بارَس مَنٛز وَنیو',
  step1Desc: 'پَنُن پیشہٕ ژٲریو۔ پَننہِ زَبانہِ مَنٛز پَننِس کٲمؠ مُتعلِق کَتھ کٔریو۔',
  step2Title: 'پَنُن کٲم ہٲویو',
  step2Desc: 'پَننہِ بَنٲومٕژ چِیزَن ہٕنٛد فۆٹو تُلِو یا اَکھ لۄکُٹ ویڈیو بَنٲوِو۔',
  step3Title: 'سَنَد حٲصل کٔریو',
  step3Desc: 'AI چھُ ہُنَر پرکھان تہٕ مَنظوٗر شُدہ پَرکھَن وول چھُ سَنَد جٲری کران۔',
  ctaBannerTitlePortfolio: 'ہِندوستان کؠن ہُنرمَند دَستکارَن دیِو سَرکٲری مَنظوٗری۔',
  ctaBannerTitleGovt: 'ہِندوستان کؠن مَزدورَن نِش چھُ ہُنَر۔ اَچِھو اَمیُک ثبوٗت دِمو۔',
  ctaBannerSub: 'غٲر مَنظَم شُعبَس مَنٛز کٲم کَرَن والؠن خٲطرٕ خَصوصی تَیار کَرنہٕ آمُت۔',
  beginSelfDeclaration: 'پَنٕنؠ جانچ کٔریو شۆروٗع',
  welcomeCandidate: 'خوش آمدید، رمیش 👋',
  candidateId: 'امیدوار سُنٛد ID: RPL-2024-8842',
  allSynced: 'سۄروے ڈیٹا سِنک گۆو',
  newDeclaration: 'نٔو جانچ',
  newDeclarationSub: 'نَو ہُنَر میپِنٛگ کٔریو شۆروٗع',
  uploadEvidence: 'ثبوٗت کٔریو اَپلوڈ',
  uploadEvidenceSub: 'فۆٹو یا ویڈیو شٲمِل کٔریو',
  viewCertificate: 'سَنَد وِچِھو',
  viewCertificateSub: 'پَنٕنؠ NSQF سَنَد کٔریو ڈاؤنلوڈ',
  yourApplications: 'تُہنٛدؠ دَرخواست',
  underReview: 'زیرِ جائزہٕ',
  needMoreInfo: 'مَزید مَعلوٗمات چِھہ ضروٗری',
  certified: 'تصدیق شُدہ',
  nsqfLevel: 'NSQF درَجہٕ',
  submittedAgo: '۲ دۄہ برٛونٛہہ پیش کَرنہٕ آمُت',
  assessorReviewing: 'جانچ کَرَن وول چھُ تُہنٛزؠ ثبوٗت پَرکھان…',
  needClearerVideo: 'وائرنگ سِکیورٹی چَیکُک صَفا ویڈیو گَژھی۔',
  details: 'تفصیٖل',
  uploadNow: 'وۄنؠ کٔریو اَپلوڈ',
  downloadPdf: 'PDF ڈاؤنلوڈ کٔریو',
  worksWithoutInternet: 'انٹرنیٹ وَرٲے تہِ چھُ کٲم کَران',
  worksWithoutInternetSub: 'انٹرنیٹ نَہ آسِتھ تہِ وِچِھو دَرخواست۔ آن لائن یِتھے گَژھِو، پانہٕ سِنک گَژھِ۔',
  pendingReview: 'جائزَس خٲطرٕ پینڈِنٛگ',
  searchCandidate: 'امیدوار ژھانٛڈیو…',
  aiDisclaimer: 'AI چھُ صِرف مَشوَرَہ دِوان۔ حَتمی فَیصلہٕ چھُ اِنسٲنی پَرکھَن وول کَران۔',
  photos: 'فۆٹو',
  video: 'ویڈیو',
  aiSuggestion: 'AI مَشوَرَہ',
  competent: 'اہل (ماہِر)',
  needsReview: 'دوبارہ جانچ ضروٗری',
  lowMatch: 'کم جوڑ',
  yes: 'آ',
  partial: 'کؠنٛہہ حَدَس تام',
  no: 'نہٕ',
  saveDraft: 'ڈرافٹ مَحفوٗظ کٔریو',
  notYetCompetent: 'وۄنؠ تام پوٗرٕ اہل نہٕ',
  requestEvidence: 'مَزید ثبوٗت مَنٛگیو',
  recommendCert: 'سَنَد دِنُک مَشوَرَہ دیِو',
  selfDeclaration: 'پَنٕنؠ جانچ',
  selfDeclarationSub: 'پَننِس ہُنرَس بارَس مَنٛز وَنیو — پَننؠن لَفظَن مَنٛز۔',
  offlineReady: 'آف لائن تَیار',
  step: 'مَرحلہٕ',
  of: 'مَنٛزٕ',
  yourTrade: 'تُہُنٛد پیشَہ',
  experience: 'تَجرُبہٕ',
  evidence: 'ثبوٗت',
  result: 'نَتیجہٕ',
  whatWork: 'تۆہی کۄس کٲم چھِو کَران؟',
  tapPicture: 'پَننہِ کٲمؠ ہٕنٛزِ تصویرِ پؠٹھ کٔریو کِلِک۔',
  tellAboutWork: 'پَننہِ کٲمؠ بارَس مَنٛز وَنیو',
  pressAndSpeak: 'دَبٲوِو تہٕ بولِو',
  speakAnyLang: 'کانٛسہِ تہِ زَبانہِ مَنٛز بولِو',
  listening: '🔴 بوزان چھُ… وۄنؠ بولِو',
  howManyYears: 'تۆہی کٔژَن ؤرؠ یَن پؠٹھ چھِو یہِ کٲم کَران؟',
  whatTools: 'تۆہی کۄس اَوزار چھِو بَرور کَران؟',
  whatKindWork: 'تۆہی عام طور پٲٹھؠ کۄس کٲم چھِو کَران؟',
  whereWork: 'تۆہی کَتہِ چھِو کٲم کَران؟',
  showYourWork: 'پَنُن کٲم ہٲویو',
  evidenceSub: 'فۆٹو تہٕ ویڈیو سٕتی چھُ پَرکھَن وٲلِس تُہُنٛد ہُنَر سَمجھَن مَنٛز مَدَتھ مِلان۔',
  takePhoto: 'فۆٹو تُلِو',
  takePhotoSub: 'پَننہِ کٲمؠ ہُنٛد',
  recordVideo: 'ویڈیو بَنٲوِو',
  recordVideoSub: 'اَکھ لۄکُٹ ویڈیو',
  uploadPaper: 'کاغَذ اَپلوڈ کٔریو',
  uploadPaperSub: 'سَنَد یا تجربے چِٹھی',
  dragFiles: 'یا فائِل ییٚتین لٔمِتھ آوریو',
  fileTypes: 'JPG, PNG, MP4, PDF — ۵۰ MB تام',
  offlineUpload: 'تۆہی ہؠکِو یہِ اِنٹرنیٹ وَرٲے تہِ کٔرِتھ۔',
  offlineUploadSub: 'فائلہٕ رۆزن فونَس مَنٛز مَحفوٗظ تہٕ نؠٹ یِنَس پؠٹھ گَژھَن اپلوڈ۔',
  suggestedMatch: 'تجویز کَرنہٕ آمُت میچ',
  match: 'میچ',
  humanReview: 'اِنسٲنی جانچ کَرَن وول کٔرِ جانچ تہٕ کٔرِ فَیصلہٕ۔',
  humanReviewSub: 'یہِ چھُ کمپیوٹرُک اِبتِدٲیی مَشوَرَہ۔ بااَختیار جانچ کَرَن وول کٔرِ حَتمی فَیصلہٕ۔',
  back: 'پَتھ کُن',
  next: 'برٛونٛہہ کُن',
  submit: 'پیش کٔریو',
  orTypeBelow: 'بَٹَن دَبٲوِو تہٕ کَتھ کٔریو یا بۄن کَن لؠکِھو۔',
  electrician: 'الیکٹریشن',
  plumber: 'پلمبر',
  welder: 'ویلڈر',
  carpenter: 'چھان (بڑھئی)',
  mason: 'دَیزی گَر (راج مزدور)',
  tailor: 'سوٗژؠ (درزی)',
  cook: 'وازَہ (باورچی)',
  driver: 'ڈرائیور',
  other: 'باقی',
  performBasicWork: 'بُنیٲدی تَقنیٖکی کٲم کَرٕنؠ',
  readDrawings: 'سادٕ نَقشہٕ سَمجھُن',
  followSafety: 'کٲمؠ کُن حِفٲظتی قواعِدَن پؠٹھ عَمَل کَرٕنؠ',
  footerDesc: 'سمارٹ انڈیا ہیکاتھونک تحت RPL خٲطرٕ AI ہُنَر جانچ سَہوٗلِیَتھ۔',
  sponsoredBy: 'سرپرست',
  msdeFullName: 'وزارتِ ہنرمندی و صنعت کاری (MSDE)',
  ncvetFullName: 'نیشنل کونسل فار ووکیشنل ایجوکیشن اینڈ ٹریننگ (NCVET)',
  project: 'منصوبہٕ',
  problemId: 'مسئلہٕ کوڈ: SIH26242',
  themeSmartEdu: 'تھیم: سمارٹ تعلیم',
  categorySoftware: 'شعبہٕ: سافٹ ویئر',
  footerCopyright: '© ۲۰۲۶ RPL AI جانچ ٹوٗل — ہِندوستان کؠن ہُنرمَند کاریگَرَن خٲطرٕ تَیار کَرنہٕ آمُت'
};

export const sd = {
  navHome: 'مکي صفحو',
  navSelfDeclaration: 'پاڻمرادو تصديق',
  navCandidate: 'اميدوار',
  navAssessor: 'جانچيندڙ',
  govtInitiative: 'حڪومت هند جي پيشقدمي',
  ministryName: 'مهارتن جي ترقي ۽ صنعتڪاري واري وزارت',
  rplAiAssessment: 'RPL AI مهارت جي جانچ',
  heroTitle: 'پنهنجي ڪاريگري ۽ مهارت جو سرڪاري سرٽيفڪيٽ حاصل ڪريو',
  heroSub: 'ڪم دوران سکندڙ ڪاريگرن لاءِ۔ بنا ڪنهن رسمي تعليم جي۔',
  portfolioHeroH1_1: 'مهارت پرکيو۔',
  portfolioHeroH1_2: 'تجربي جي',
  portfolioHeroH1_3: ' تصديق ڪريو۔',
  portfolioHeroH1_4: 'RPL کي وڌايو۔',
  startAssessment: 'جانچ شروع ڪريو',
  assessorLogin: 'جانچيندڙ لاگ ان',
  makeItClear: '۰۱ — صاف ۽ شفاف',
  buildShapeShip: 'سکيو / ٺاهيو / ترقي ڪريو',
  tickerAiAssisted: 'AI سهائتا يافته RPL',
  tickerNsqf: 'NSQF معيارن مطابق',
  tickerHumanLoop: 'انساني تصديق سان',
  tickerRegional: '۲۲ هندوستاني ٻوليون',
  tickerOffline: 'آف لائن سنڪ سهولت',
  tickerMinistry: 'مهارتن جي ترقي واري وزارت',
  ourWork: 'اسان جو ڪم',
  work1Title: 'آسان تجربي جي نقشي سازي',
  work1Desc: 'ڪاريگرن لاءِ پنهنجي مادري ٻوليءَ ۾ مهارت ٻڌائڻ جو گفتگو وارو انٽرفيس۔',
  work2Title: 'ويڊيو ۽ فوٽو جانچ',
  work2Desc: 'عملي ڪم جي آزمائش لاءِ تصويري ۽ ويڊيو ثبوت۔',
  work3Title: 'معياري اسڪورنگ',
  work3Desc: 'جانچيندڙن لاءِ NSQF معيارن مطابق درست نمبر ڏيڻ جو نظام۔',
  work4Title: 'گھٽ انٽرنيٽ تي به ڪارآمد',
  work4Desc: 'انٽرنيٽ نه هئڻ باوجود سڀ ڊيٽا فون ۾ محفوظ رهندي۔',
  tagSelfDecl: 'پاڻمرادو تصديق',
  tagAiAssist: 'AI سهائتا',
  tagPractical: 'عملي طريقو',
  tagMedia: 'ميڊيا ثبوت',
  tagAssessor: 'جانچيندڙ جي مدد',
  tagNsqf: 'NSQF معيار',
  tagOffline: 'آف لائن فعال',
  tagSync: 'پاڻمرادو سنڪ',
  feat1Title: 'پنهنجي تجربي بابت ڳالهايو',
  feat1Desc: 'پنهنجي مادري ٻوليءَ ۾ آواز ذريعي ڳالهايو',
  feat2Title: 'پنهنجو ڪم ڏيکاريو',
  feat2Desc: 'تصويرون، ويڊيوز ۽ ڪم جا ثبوت آساني سان اپ لوڊ ڪريو',
  feat3Title: 'NSQF معيارن سان برابري',
  feat3Desc: 'AI توهان جي عملي مهارت کي قومي معيارن سان ملائي ٿي',
  feat4Title: 'ماهر جانچيندڙ جو حتمي فيصلو',
  feat4Desc: 'AI تجويز ڏئي ٿي، بااختيار ماهر آخري فيصلو ڪري ٿو',
  howItWorks: 'هي ڪيئن ڪم ڪري ٿو',
  howItWorksSub: 'ٽي سولا مرحلا۔ ڪابه ڏکي امتحان يا وڏا فارم ناهن۔',
  step1Title: 'پنهنجي باري ۾ ٻڌايو',
  step1Desc: 'پنهنجو پيشو چونڊيو۔ ڪنهن به ٻوليءَ ۾ پنهنجي ڪم جي تجربي بابت ڳالهايو۔',
  step2Title: 'پنهنجو ڪم ڏيکاريو',
  step2Desc: 'پنهنجي ٺاهيل ڪم جون تصويرون ڪڍو يا ننڍڙو ويڊيو ٺاهيو۔',
  step3Title: 'سرٽيفڪيٽ حاصل ڪريو',
  step3Desc: 'AI مهارت پرکي ٿي ۽ بااختيار ماهر سرڪاري سند جاري ڪري ٿو۔',
  ctaBannerTitlePortfolio: 'هندستان جي باصلاحيت هٿن کي ڏيو سرڪاري مڃتا۔',
  ctaBannerTitleGovt: 'هندستان جي پورهيتن وٽ مهارت آهي۔ اچو ان جي تصديق ڪريون۔',
  ctaBannerSub: 'غير منظم پورهيت طبقي لاءِ خاص تيار ڪيل۔',
  beginSelfDeclaration: 'پاڻمرادو تصديق شروع ڪريو',
  welcomeCandidate: 'ڀلي ڪري آيا، رميش 👋',
  candidateId: 'اميدوار شناختي نمبر: RPL-2024-8842',
  allSynced: 'سڀ ڊيٽا سنڪ ٿي ويو',
  newDeclaration: 'نئي تصديق',
  newDeclarationSub: 'نئين مهارت جي جانچ شروع ڪريو',
  uploadEvidence: 'ثبوت اپ لوڊ ڪريو',
  uploadEvidenceSub: 'تصويرون يا ويڊيو شامل ڪريو',
  viewCertificate: 'سرٽيفڪيٽ ڏسو',
  viewCertificateSub: 'پنهنجو NSQF سرٽيفڪيٽ ڊائون لوڊ ڪريو',
  yourApplications: 'توهان جون درخواستون',
  underReview: 'جاچ هيٺ',
  needMoreInfo: 'وڌيڪ معلومات گهربل آهي',
  certified: 'تصديق ٿيل (سرٽيفائيڊ)',
  nsqfLevel: 'NSQF درجو',
  submittedAgo: '۲ ڏينهن اڳ پيش ڪيل',
  assessorReviewing: 'جانچيندڙ توهان جي ثبوتن جي جاچ ڪري رهيو آهي…',
  needClearerVideo: 'وائرنگ سيڪيورٽي چيڪ جي وڌيڪ چٽي ويڊيو موڪليو۔',
  details: 'تفصيل',
  uploadNow: 'هاڻي اپ لوڊ ڪريو',
  downloadPdf: 'PDF ڊائون لوڊ ڪريو',
  worksWithoutInternet: 'انٽرنيٽ بنا به ڪم ڪري ٿو',
  worksWithoutInternetSub: 'انٽرنيٽ نه هجڻ باوجود درخواست ڏسو ۽ ٺاهيو۔ آن لائن ٿيڻ سان خودڪار سنڪ ٿيندو۔',
  pendingReview: 'جائزي لاءِ انتظار ۾',
  searchCandidate: 'اميدوار ڳوليو…',
  aiDisclaimer: 'AI رڳو سهائتا ڪري ٿي۔ آخري فيصلو انساني ماهر جو ئي هوندو آهي۔',
  photos: 'تصويرون',
  video: 'ويڊيو',
  aiSuggestion: 'AI تجويز',
  competent: 'قابل (ماهر)',
  needsReview: 'ٻيهر جاچ گهربل',
  lowMatch: 'گھٽ برابري',
  yes: 'ها',
  partial: 'ڪجھ حد تائين',
  no: 'نه',
  saveDraft: 'ڊرافٽ محفوظ ڪريو',
  notYetCompetent: 'في الحال پورو تيار ناهي',
  requestEvidence: 'وڌيڪ ثبوت گھرو',
  recommendCert: 'سرٽيفڪيشن جي سفارش ڪريو',
  selfDeclaration: 'پاڻمرادو تصديق',
  selfDeclarationSub: 'پنهنجي مهارت بابت ٻڌايو — پنهنجن لفظن ۾۔',
  offlineReady: 'آف لائن تيار',
  step: 'مرحلو',
  of: 'مان',
  yourTrade: 'توهان جو پيشو',
  experience: 'تجربو',
  evidence: 'ثبوت',
  result: 'نتيجو',
  whatWork: 'توهان ڪهڙو ڪم ڪندا آهيو؟',
  tapPicture: 'پنهنجي ڪم واري تصوير تي ٽيپ ڪريو۔',
  tellAboutWork: 'پنهنجي ڪم بابت ٻڌايو',
  pressAndSpeak: 'دٻايو ۽ ڳالهايو',
  speakAnyLang: 'ڪنهن به ٻوليءَ ۾ ڳالهايو',
  listening: '🔴 ٻڌي رهيو آهي… هاڻي ڳالهايو',
  howManyYears: 'توهان ڪيترن سالن کان هي ڪم ڪري رهيا آهيو؟',
  whatTools: 'توهان ڪهڙا اوزار استعمال ڪندا آهيو؟',
  whatKindWork: 'عام طور توهان ڪهڙي نموني جو ڪم ڪندا آهيو؟',
  whereWork: 'توهان ڪٿي ڪم ڪندا آهيو؟',
  showYourWork: 'پنهنجو ڪم ڏيکاريو',
  evidenceSub: 'تصويرون ۽ ويڊيوز جانچيندڙ کي توهان جي مهارت سمجهڻ ۾ مدد ڪن ٿا.',
  takePhoto: 'تصوير ڪڍو',
  takePhotoSub: 'پنهنجي ڪم جي',
  recordVideo: 'ويڊيو ٺاهيو',
  recordVideoSub: 'هڪ مختصر ڪلپ',
  uploadPaper: 'دستاويز اپ لوڊ ڪريو',
  uploadPaperSub: 'سرٽيفڪيٽ يا تجربي جو خط',
  dragFiles: 'يا فائلون هتي آڻيو',
  fileTypes: 'JPG, PNG, MP4, PDF — ۵۰ MB تائين',
  offlineUpload: 'توهان هي انٽرنيٽ بنا به ڪري سگھو ٿا.',
  offlineUploadSub: 'فائلون فون ۾ محفوظ رهنديون ۽ آن لائن ٿيڻ تي اپ لوڊ ٿينديون.',
  suggestedMatch: 'تجويز ڪيل برابري',
  match: 'برابري',
  humanReview: 'انساني ماهر جائزي وٺي فيصلو ڪندو.',
  humanReviewSub: 'هي ڪمپيوٽر جي ابتدائي تجويز آهي. بااختيار جانچيندڙ ئي حتمي فيصلو ڪندو.',
  back: 'پوئتي',
  next: 'اڳتي',
  submit: 'پيش ڪريو',
  orTypeBelow: 'بٽڻ دٻائي ڳالهايو يا هيٺ لکو.',
  electrician: 'اليڪٽريشن',
  plumber: 'پلمبر',
  welder: 'ويلڊر',
  carpenter: 'واڍو (سٽار)',
  mason: 'راڄو (معمار)',
  tailor: 'درزي',
  cook: 'بورچي',
  driver: 'ڊرائيور',
  other: 'ٻيو',
  performBasicWork: 'بنيادي فني ڪم سرانجام ڏيڻ',
  readDrawings: 'سولا نقشا يا ڊرائنگ سمجهڻ',
  followSafety: 'ڪم واري هنڌ حفاظت جا اصول اپنائڻ',
  footerDesc: 'سمارٽ انڊيا هيڪاٿون تحت اڳوڻي سکيا جي مڃتا (RPL) لاءِ AI وسيلي مهارت جانچڻ جو نظام.',
  sponsoredBy: 'سرپرست',
  msdeFullName: 'مهارتن جي ترقي ۽ صنعتڪاري واري وزارت (MSDE)',
  ncvetFullName: 'قومي ڪائونسل براءِ پروفيشنل تعليم ۽ تربيت (NCVET)',
  project: 'منصوبو',
  problemId: 'مسئلو ڪوڊ: SIH26242',
  themeSmartEdu: 'موضوع: سمارٽ تعليم',
  categorySoftware: 'شعبو: سافٽ ويئر',
  footerCopyright: '© ۲۰۲۶ RPL AI جانچ جو اوزار — هندستان جي ڪاريگر پورهيتن لاءِ مخصوص'
};
